import React from "react";

const A='#22c55e',G='#f9fafb',T='#111827',M='#4b5563',B='#e5e7eb',W='#fff',O='#f97316';
const page:React.CSSProperties={width:419,minHeight:812,margin:'0 auto',background:G,color:T,fontFamily:'Inter,Arial,sans-serif',position:'relative',overflow:'hidden'};
const head=(title:string,sub?:string,accent=A)=><div style={{padding:'18px 20px 8px',background:W}}><div style={{fontSize:24,fontWeight:800,color:T}}>{title}</div>{sub&&<div style={{fontSize:14,color:M,marginTop:4}}>{sub}</div>}</div>;
const btn=(label:string,color=A,outline=false)=><button style={{width:'100%',height:48,borderRadius:10,border:`1px solid ${color}`,background:outline?W:color,color:outline?color:W,fontWeight:700,fontSize:14}}>{label}</button>;
const field=(label:string,value:string,accent?:string)=><div style={{marginBottom:14}}><div style={{fontSize:13,fontWeight:700,color:M,marginBottom:7}}>{label}</div><div style={{background:W,border:`1px solid ${accent||B}`,borderRadius:10,minHeight:48,padding:'0 14px',display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:14}}>{value}<span style={{color:M}}>⌄</span></div></div>;
const card=(children:React.ReactNode)=><div style={{background:W,borderRadius:14,boxShadow:'0 4px 10px rgba(0,0,0,.04)',padding:16,marginBottom:12}}>{children}</div>;
const nav=(active='Home')=><div style={{position:'absolute',left:0,right:0,bottom:0,height:78,background:W,borderTop:`1px solid ${B}`,display:'flex',justifyContent:'space-around',alignItems:'center'}}>{['Home','Plots','Market','Finance','Profile'].map(x=><div key={x} style={{textAlign:'center',fontSize:11,fontWeight:x===active?700:500,color:x===active?A:'#9ca3af'}}><div style={{fontSize:20,marginBottom:3}}>{x==='Home'?'⌂':x==='Plots'?'⌖':x==='Market'?'◫':x==='Finance'?'◈':'◉'}</div>{x}</div>)}</div>;

function MyPlots(){const plots=[['North Field','2.5 acres • Soil: Loam','Growing','Chilli (Teja)','60%',A],['South Field','1.8 acres • Soil: Clay','Harvesting','Cotton','92%',O],['West Patch','3.0 acres • Soil: Sandy','Fallow','','',' #9ca3af']];return <div style={page}><div style={{padding:'14px 20px',background:W,display:'flex',justifyContent:'space-between'}}><div><div style={{fontSize:23,fontWeight:800}}>‹&nbsp; My Plots</div><div style={{fontSize:14,color:M,marginTop:4}}>You have 3 plots</div></div><div style={{fontSize:28,color:A}}>＋</div></div><div style={{padding:20}}>{plots.map((p,i)=>card(<div key={p[0]}><div style={{display:'flex',justifyContent:'space-between'}}><div><div style={{fontWeight:700,fontSize:15}}>{p[0]}</div><div style={{fontSize:12,color:M,marginTop:3}}>{p[1]}</div></div><span style={{padding:'4px 10px',borderRadius:16,background:i===0?'#dcfce7':i===1?'#ffedd5':'#e5e7eb',color:i===0?A:i===1?O:M,fontSize:12,fontWeight:700}}>{p[2]}</span></div>{i<2?<><div style={{display:'flex',justifyContent:'space-between',marginTop:14,fontSize:13}}><span style={{color:M}}>Current: <b style={{color:T}}>{p[3]}</b></span><b style={{color:A}}>{p[4]}</b></div><div style={{height:4,borderRadius:3,background:'#f3f4f6',marginTop:6}}><div style={{width:p[4],height:'100%',background:A,borderRadius:3}}/></div></>:<div style={{marginTop:12}}>{btn('+ Add Crop',A,true)}</div>}</div>))}</div>{nav('Plots')}</div>}
function Finance(){return <div style={page}><div style={{padding:'14px 20px 8px',background:W}}><div style={{fontSize:22,fontWeight:800}}>‹&nbsp; Finance</div></div><div style={{padding:16}}>{card(<><div style={{fontSize:14,fontWeight:700,color:M}}>Request Advance</div>{field('Select Commission Agent','Priya Agencies, Guntur Market Yard')}{field('Link to Token','TRD-CHL-089234 • Chilli 2500kg')}<div style={{fontSize:12,color:M,marginBottom:12}}>Estimated sale proceeds: <b style={{color:T}}>Rs 4,00,000</b></div><div style={{display:'flex',justifyContent:'space-between',fontSize:14,color:M,marginBottom:8}}><b>Advance Amount</b><span>Max Rs 75,000</span></div><div style={{background:W,border:`1px solid ${B}`,borderRadius:10,height:56,display:'flex',alignItems:'center',padding:'0 14px',fontWeight:800,fontSize:20}}>₹&nbsp;50,000</div><div style={{marginTop:12,display:'inline-block',background:'#dcfce7',color:A,padding:'8px 10px',borderRadius:16,fontSize:12,fontWeight:700}}>✦ AI suggests up to Rs 50,000 based on token</div>{field('Purpose (Optional)','Seeds purchase')}{btn('Send Request',O)}</>)}{card(<><div style={{fontWeight:800,marginBottom:12}}>Previous Requests</div><div style={{display:'flex',justifyContent:'space-between',padding:12,border:`1px solid ${B}`,borderRadius:10}}><div><div style={{fontWeight:700,fontSize:13}}>Advance Rs 25,000</div><div style={{fontSize:11,color:M}}>Oct 12, 2023 • PA Guntur</div></div><span style={{background:'#dcfce7',color:A,padding:'4px 8px',borderRadius:6,fontSize:10,fontWeight:700}}>APPROVED</span></div></>)} </div>{nav('Finance')}</div>}

function ProduceDashboard(){return <div style={page}>{head('Kisan Producer','Smart commodity trading workspace')}<div style={{padding:16}}>{card(<><div style={{display:'flex',justifyContent:'space-between'}}><div><div style={{fontSize:14,color:M}}>Current Production Value</div><div style={{fontSize:28,fontWeight:800}}>₹12.4L</div></div><span style={{color:A,fontWeight:700}}>+8.4%</span></div></>)}{card(<><div style={{fontWeight:800,marginBottom:12}}>Quick Actions</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}>{['Add Plot','Log Activity','Add Crop','View Market'].map(x=><div key={x} style={{border:`1px solid ${B}`,borderRadius:10,padding:12,textAlign:'center',fontSize:12,fontWeight:700}}>{x}</div>)}</div></>)}</div>{nav('Home')}</div>}

export default function Producer55Screens({screen}:{screen?:string}){switch(screen){case 'plots':return <MyPlots/>;case 'finance':return <Finance/>;default:return <ProduceDashboard/>;}}
