import React from 'react';

type Props={screen?:string};
const base:React.CSSProperties={width:375,minHeight:812,margin:'0 auto',boxSizing:'border-box',background:'#f8fafc',color:'#0f172a',fontFamily:'Arial, sans-serif'};
const header=(title:string,right?:React.ReactNode)=> <><div style={{height:44,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',boxSizing:'border-box',fontSize:15,fontWeight:700}}>9:41 <span style={{fontSize:14}}>⌁ ◔ ▣</span></div><div style={{height:56,padding:'0 16px',display:'flex',alignItems:'center',justifyContent:'space-between',boxSizing:'border-box'}}><div style={{display:'flex',alignItems:'center',gap:12}}><span style={{fontSize:28}}>‹</span><h1 style={{fontSize:20,margin:0}}>{title}</h1></div>{right}</div></>;
const pill=(active:boolean)=>({padding:'6px 12px',borderRadius:20,border:'1px solid #e2e8f0',background:active?'#0f172a':'#fff',color:active?'#fff':'#64748b',fontSize:13,fontWeight:600});
const btn=(bg:string,color='#fff',border='none')=>({width:'100%',height:48,borderRadius:12,border,background:bg,color,fontWeight:700,fontSize:14});
const card:React.CSSProperties={background:'#fff',border:'1px solid #e2e8f0',borderRadius:12,padding:16,boxSizing:'border-box'};

export default function BillDiscounting5ScreensAlt({screen='2041:174'}:Props){
 const id=screen;
 return <div style={base} data-node-id={id}>
 {id==='2041:174'&&<BillDiscounting/>}
 {id==='2041:175'&&<Financiers/>}
 {id==='2041:176'&&<RequestPurchase/>}
 {id==='2041:177'&&<DiscountOffer/>}
 {id==='2041:178'&&<Receipt/>}
 </div>
}

function BillDiscounting(){return <>{header('Bill Discounting',<span style={{fontSize:22}}>ⓘ</span>)}<div style={{padding:16}}><div style={{...card, padding:20}}><div style={{fontSize:14,color:'#64748b'}}>Total Outstanding</div><div style={{fontSize:28,fontWeight:800,marginTop:4}}>₹4,28,500</div><div style={{background:'#f0f9ff',padding:12,borderRadius:8,marginTop:16,fontSize:13}}>✣ Eligible for discount: <b>₹3,20,000</b> (3 invoices)</div><button style={{...btn('#fff','#f97316','1px solid #f97316'),marginTop:16}}>Request Bulk Discount</button></div><div style={{display:'flex',gap:16,margin:'20px 0 16px'}}><div style={{color:'#f97316',fontWeight:700,fontSize:14,borderBottom:'2px solid #f97316',paddingBottom:8}}>Eligible (3)</div><div style={{color:'#94a3b8',fontSize:14}}>Pending (1)</div><div style={{color:'#94a3b8',fontSize:14}}>Discounted (2)</div></div><div style={{display:'grid',gap:12}}><InvoiceCard name='ABC Exports' no='INV-20250620-001' amount='₹1,20,000' risk='Medium' accent='#16a34a'/><InvoiceCard name='XYZ Traders' no='INV-20250620-002' amount='₹85,000' risk='High' accent='#f59e0b'/><div style={{...card,borderColor:'#2563eb'}}><div style={{display:'flex',justifyContent:'space-between',fontWeight:700}}>Awaiting financier offer <span style={{background:'#dbeafe',color:'#2563eb',padding:'2px 8px',borderRadius:4,fontSize:11}}>PENDING</span></div><button style={{...btn('#2563eb'),width:98,height:40,marginTop:12}}>View Offers</button></div></div><div style={{borderTop:'1px solid #e2e8f0',marginTop:20,paddingTop:12,fontWeight:700,fontSize:14,display:'flex',justifyContent:'space-between'}}>How it Works <span>⌄</span></div></div></>}
function InvoiceCard(p:{name:string;no:string;amount:string;risk:string;accent:string}){return <div style={{...card,borderColor:p.accent}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:12,color:'#64748b'}}>{p.no}</div><div style={{fontWeight:800,fontSize:16,marginTop:2}}>{p.name}</div></div><span style={{background:'#dcfce7',color:'#16a34a',padding:'2px 8px',borderRadius:4,fontSize:11,fontWeight:700}}>ELIGIBLE</span></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginTop:16}}><div><div style={{fontWeight:800,fontSize:18}}>{p.amount}</div><div style={{fontSize:12,color:'#64748b'}}>Due 5 Jul (15 days left)</div></div><div style={{textAlign:'right'}}><div style={{fontSize:11,color:'#64748b'}}>RISK: <span style={{color:p.risk==='High'?'#ef4444':'#16a34a'}}>{p.risk}</span></div><button style={{...btn('#f97316'),width:136,height:40,marginTop:6}}>Request Discount</button></div></div></div>}
function Financiers(){return <>{header('Financiers',<span style={{fontSize:24}}>⌯</span>)}<div style={{padding:16}}><div style={{background:'#f1f5f9',padding:12,borderRadius:8,display:'flex',gap:12,alignItems:'center'}}><div style={{width:32,height:32,background:'#94a3b8',borderRadius:4}}/><div><div style={{fontSize:11,color:'#64748b',fontWeight:700}}>INV-20250620-001</div><div style={{fontSize:14,fontWeight:800}}>₹1,20,000 • ABC Exports</div></div></div><div style={{display:'flex',gap:8,margin:'16px 0'}}><span style={pill(true)}>All</span><span style={pill(false)}>Banks</span><span style={pill(false)}>NBFCs</span><span style={pill(false)}>Lowest Rate</span></div><div style={{display:'grid',gap:12}}><FinCard title='HDFC Bank' sub='Bank • 4.9★' rate='1.2%–2.0%' limit='₹5,00,000' eligible/><FinCard title='Sharma Enterprises' sub='Commission Agent • 4.5★' rate='1.5% flat' limit='₹2,00,000'/></div><div style={{marginTop:16,background:'#eff6ff',padding:12,borderRadius:8,color:'#2563eb',fontSize:11}}>ⓘ Financiers pay you immediately (minus discount) and collect from buyer on due date.</div><button style={{...btn('#0f172a'),width:210,height:44,display:'block',margin:'205px auto 0',borderRadius:24}}>⚯ Compare Financiers</button></div></>}
function FinCard(p:{title:string;sub:string;rate:string;limit:string;eligible?:boolean}){return <div style={card}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{display:'flex',gap:12}}><div style={{width:40,height:40,background:'#f8fafc',border:'1px solid #e2e8f0',borderRadius:8}}/><div><div style={{fontWeight:800,fontSize:15}}>{p.title}</div><div style={{fontSize:12,color:'#64748b'}}>{p.sub}</div></div></div><div style={{textAlign:'right'}}><div style={{fontWeight:800,color:'#2563eb'}}>{p.rate}</div><div style={{fontSize:11,color:'#64748b'}}>Discount Rate</div></div></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'end',marginTop:12}}><div><div style={{fontSize:12,color:'#64748b'}}>Max Limit</div><div style={{fontWeight:700}}>{p.limit}</div></div><button style={{...btn('#2563eb'),width:84,height:40}}>Select</button></div>{p.eligible&&<div style={{marginTop:12,background:'#f0fdf4',padding:10,borderRadius:6,color:'#16a34a',fontSize:12}}>✓ Your buyer is eligible</div>}</div>}
function RequestPurchase(){return <>{header('Request Bill Purchase')}<div style={{padding:16,display:'grid',gap:20}}><div style={{display:'grid',gap:12}}><div style={{...card,display:'flex',justifyContent:'space-between'}}><div><b>ABC Exports</b><div style={{fontSize:11,color:'#64748b'}}>INV-20250620-001</div></div><b>₹1,20,000</b></div><div style={{...card,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{width:32,height:32,background:'#f1f5f9',borderRadius:4}}/><b>HDFC Bank</b></div><span style={{fontSize:12,color:'#64748b'}}>1.2%–2.0%</span></div></div><div><div style={{display:'flex',justifyContent:'space-between',fontWeight:700,fontSize:14}}><span>Proposed Discount Rate</span><span style={{color:'#f97316',fontSize:16}}>1.5%</span></div><div style={{marginTop:12,height:4,background:'#e2e8f0',borderRadius:2,position:'relative'}}><div style={{position:'absolute',left:'43%',top:-8,width:22,height:22,borderRadius:'50%',background:'#f97316',border:'2px solid #fff',boxShadow:'0 1px 3px rgba(0,0,0,.25)'}}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:'#64748b',marginTop:12}}><span>Min 1.2%</span><span>Max 2.0%</span></div></div><div><div style={{fontWeight:700,fontSize:14,marginBottom:8}}>Handling Fee</div><div style={{...card,padding:14}}>₹200</div></div><div style={{background:'#2563eb',color:'#fff',padding:20,borderRadius:16,boxShadow:'0 8px 10px rgba(37,99,235,.25)'}}>{[['Invoice Amount','₹1,20,000'],['Discount (1.5%)','−₹1,800'],['Handling Fee','−₹200']].map(([a,b])=><div style={{display:'flex',justifyContent:'space-between',marginBottom:16,fontSize:14}} key={a}><span style={{opacity:.8}}>{a}</span><b>{b}</b></div>)}<div style={{borderTop:'1px solid rgba(255,255,255,.2)',paddingTop:14,display:'flex',justifyContent:'space-between'}}><b>Net Payable to You</b><b style={{fontSize:22}}>₹1,18,000</b></div></div><div><div style={{fontWeight:700,fontSize:14,marginBottom:8}}>Notes to Financier (Optional)</div><div style={{...card,height:80,color:'#94a3b8'}}>Enter any specific details...</div></div><div style={{position:'relative'}}><div style={{background:'#111827',color:'#fff',padding:14,borderRadius:10,position:'absolute',top:70,left:0,right:0,zIndex:2,fontSize:13}}>✓ Request sent to HDFC Bank. Offer pending.</div><button style={{...btn('#f97316'),marginTop:0}}>Submit Request</button></div></div></>}
function DiscountOffer(){return <>{header('Discount Offer')}<div style={{padding:16}}><div style={{...card,display:'flex',justifyContent:'space-between'}}><div style={{display:'flex',gap:12}}><div style={{width:44,height:44,background:'#f8fafc',border:'1px solid #e2e8f0',borderRadius:8}}/><div><b>HDFC Bank</b><div style={{fontSize:12,color:'#64748b'}}>Financier Offer</div></div></div><span style={{background:'#fef2f2',color:'#ef4444',padding:'4px 8px',borderRadius:6,fontSize:11,fontWeight:700}}>⏱ 2D LEFT</span></div><div style={{...card,marginTop:16}}><b>Discount Terms</b><div style={{marginTop:12,display:'grid',gap:12}}>{[['Discount Rate (1.5%)','₹1,800'],['Processing Fee','₹200']].map(x=><div style={{display:'flex',justifyContent:'space-between',fontSize:14}} key={x[0]}><span style={{color:'#64748b'}}>{x[0]}</span><b>{x[1]}</b></div>)}<div style={{borderTop:'1px solid #f1f5f9'}}/><div style={{display:'flex',justifyContent:'space-between'}}><b>Net Payable to You</b><b style={{color:'#2563eb',fontSize:18}}>₹1,18,000</b></div></div><div style={{background:'#f8fafc',padding:12,borderRadius:8,marginTop:12,fontSize:12,color:'#64748b'}}>🗓 Financier collects ₹1,20,000 from buyer by 5 Jul 2025</div></div><div style={{background:'#fffbeb',border:'1px solid #fef3c7',padding:12,borderRadius:8,marginTop:16,color:'#92400e',fontSize:12}}>⚠ Once accepted, financier has exclusive right to collect from buyer. You cannot claim this invoice again.</div><div style={{textAlign:'center',marginTop:24,fontWeight:700,color:'#64748b',fontSize:14}}>Enter 6-digit OTP sent to your mobile<div style={{display:'flex',gap:8,justifyContent:'center',margin:'12px 0 24px'}}>{[7,'','','','',''].map((x,i)=><div key={i} style={{width:42,height:48,border:'1px solid #e2e8f0',background:'#fff',borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',fontSize:20,fontWeight:800,color:'#0f172a'}}>{x}</div>)}</div></div><button style={btn('#2563eb')}>Accept Offer</button><button style={{...btn('#fff','#ef4444','1px solid #ef4444'),marginTop:12}}>Reject Offer</button></div></>}
function Receipt(){return <>{header('Discount Receipt',<span style={{fontSize:22}}>⇧</span>)}<div style={{padding:16}}><div style={{background:'#f0fdf4',padding:12,borderRadius:8,color:'#16a34a',fontWeight:700,fontSize:14}}>✓ Bill discounted successfully — 20 Jun 2025</div><div style={{...card,marginTop:20}}><div style={{display:'grid',gap:12,fontSize:13}}>{[['Transaction ID','TRD-BD-20250620-001'],['Invoice','INV-20250620-001'],['Buyer','ABC Exports'],['Financier','HDFC Bank']].map(x=><div style={{display:'flex',justifyContent:'space-between'}} key={x[0]}><span style={{color:'#64748b'}}>{x[0]}</span><b>{x[1]}</b></div>)}</div><div style={{borderTop:'1px dashed #e2e8f0',margin:'16px 0'}}/><div style={{display:'grid',gap:12,fontSize:13}}>{[['Invoice Amount','₹1,20,000'],['Discount (1.5%)','−₹1,800'],['Fees','−₹200']].map(x=><div style={{display:'flex',justifyContent:'space-between'}} key={x[0]}><span style={{color:'#64748b'}}>{x[0]}</span><b>{x[1]}</b></div>)}<div style={{display:'flex',justifyContent:'space-between',paddingTop:4}}><b style={{fontSize:16}}>Net Received</b><b style={{fontSize:20,color:'#16a34a'}}>₹1,18,000</b></div></div><div style={{borderTop:'1px dashed #e2e8f0',margin:'16px 0'}}/><div style={{display:'grid',gap:12,fontSize:13}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{color:'#64748b'}}>Payment Status</span><b style={{color:'#16a34a'}}>Credited ✓</b></div><div style={{display:'flex',justifyContent:'space-between'}}><span style={{color:'#64748b'}}>Reference</span><b>HDFC Ref #123456</b></div></div><div style={{borderTop:'1px dashed #e2e8f0',margin:'16px 0'}}/><div><div style={{fontSize:11,fontWeight:700,color:'#64748b',textTransform:'uppercase',marginBottom:8}}>Repayment Info</div><div style={{fontSize:12}}>Financier collects ₹1,20,000 from ABC Exports by 5 Jul 2025</div></div></div><div style={{marginTop:20,display:'grid',gap:12}}><button style={btn('#f97316')}>▤ Download PDF</button><button style={{...btn('#fff','#16a34a','1px solid #16a34a')}}>◯ Share via WhatsApp</button></div><div style={{display:'grid',gap:16,justifyItems:'center',padding:'12px 0',color:'#2563eb',fontWeight:700,fontSize:14}}><div>View Invoice</div><div>Track Collection Status</div></div><div style={{background:'#f1f5f9',padding:14,borderRadius:12,textAlign:'center',fontWeight:700,fontSize:16}}>Done</div></div></>}
