import React, { ReactNode, useMemo, useState } from 'react';

type ScreenId =
  | '2041:312' | '2041:313' | '2041:314' | '2041:315' | '2041:316' | '2041:317'
  | '2041:318' | '2041:320' | '2041:321' | '2041:322' | '2041:323' | '2041:324'
  | '2041:327' | '2041:328' | '2041:329' | '2041:330' | '2041:331' | '2041:332';

type Props = { screen?: ScreenId | string };

const C = {
  bg: '#f5f7f8', slate: '#455a64', slate2: '#546e7a', text: '#263238', border: '#cfd8dc', white: '#ffffff',
  blue: '#0277bd', blueBg: '#e1f5fe', green: '#43a047', greenBg: '#e8f5e9', amber: '#fb8c00', amberBg: '#fff3e0',
  red: '#e53935', redBg: '#ffebee', orange: '#e65100', orangeBg: '#fff3e0', shadow: '0 4px 6px rgba(0,0,0,.05)',
};

const A = (id: string) => `https://www.figma.com/api/mcp/asset/${id}`;

function Img({ src, size = 20, style }: { src: string; size?: number | string; style?: React.CSSProperties }) {
  return <img src={src} alt="" style={{ width: size, height: size, display: 'block', objectFit: 'contain', ...style }} />;
}

function StatusBar() {
  return <div style={{ height: 44, padding: '0 20px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', boxSizing: 'border-box', color: C.text, fontSize: 15, fontWeight: 600 }}><span>9:41</span><span style={{ fontSize: 11, letterSpacing: 2 }}>▮⌁▱</span></div>;
}

function Header({ title, back = true, leftIcon }: { title: string; back?: boolean; leftIcon?: ReactNode }) {
  return <div style={{ background: C.slate, height: 56, padding: '0 20px', display: 'flex', alignItems: 'center', gap: 12, color: C.white, boxSizing: 'border-box' }}>
    {back ? <span style={{ fontSize: 28, lineHeight: 1, marginTop: -2 }}>‹</span> : leftIcon ?? <span style={{ width: 24 }} />}
    <div style={{ fontSize: 18, fontWeight: 700, whiteSpace: 'nowrap' }}>{title}</div>
  </div>;
}

function BottomNav({ active = 'More' }: { active?: string }) {
  const items = ['Home', 'Inward', 'Outward', 'Bonds', 'More'];
  const icons = ['⌂', '⇩', '⇧', '▤', '▦'];
  return <div style={{ background: C.white, borderTop: `1px solid ${C.border}` }}>
    <div style={{ height: 80, padding: '12px 16px 0', display: 'flex', justifyContent: 'space-between', boxSizing: 'border-box' }}>
      {items.map((x, i) => <div key={x} style={{ width: 64, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, color: active === x ? C.slate : C.slate2 }}>
        <div style={{ fontSize: 24, lineHeight: '24px' }}>{icons[i]}</div><div style={{ fontSize: 11, fontWeight: active === x ? 600 : 500 }}>{x}</div>
      </div>)}
    </div>
    <div style={{ display: 'flex', justifyContent: 'center', padding: '21px 0 8px' }}><div style={{ width: 134, height: 5, borderRadius: 99, background: C.slate }} /></div>
  </div>;
}

function Page({ id, children, footer, noScroll = false }: { id: string; children: ReactNode; footer?: ReactNode; noScroll?: boolean }) {
  return <div data-node-id={id} style={{ width: 375, minHeight: 1091.333, margin: '0 auto', background: C.bg, color: C.text, fontFamily: 'Inter, Arial, sans-serif', boxSizing: 'border-box', display: 'flex', flexDirection: 'column', overflow: noScroll ? 'hidden' : 'visible' }}><div style={{ flex: 1, minHeight: 0 }}>{children}</div>{footer}</div>;
}

function Card({ children, style }: { children: ReactNode; style?: React.CSSProperties }) { return <div style={{ background: C.white, borderRadius: 16, padding: 20, boxShadow: C.shadow, boxSizing: 'border-box', ...style }}>{children}</div>; }
function Button({ children, secondary = false, danger = false, color }: { children: ReactNode; secondary?: boolean; danger?: boolean; color?: string }) {
  const bg = color ?? (secondary || danger ? C.white : C.slate); const fg = danger ? C.red : (secondary ? C.slate : C.white); const border = secondary || danger ? `1.5px solid ${fg}` : 'none';
  return <button type="button" style={{ height: 52, width: '100%', borderRadius: 12, background: bg, color: fg, border, fontSize: 14, fontWeight: 600 }}>{children}</button>;
}
function Pill({ children, active = false, bg, color }: { children: ReactNode; active?: boolean; bg?: string; color?: string }) { return <span style={{ background: bg ?? (active ? C.slate : C.white), color: color ?? (active ? C.white : C.slate2), border: active ? 'none' : `1px solid ${C.border}`, borderRadius: 20, padding: '7px 12px', fontSize: 12, fontWeight: 600, whiteSpace: 'nowrap' }}>{children}</span>; }
function Otp({ digits = ['1', '2', '8', '', '', ''], compact = false }: { digits?: string[]; compact?: boolean }) {
  return <div style={{ display: 'flex', gap: compact ? 8 : 8, justifyContent: 'center' }}>{digits.map((d, i) => <div key={i} style={{ width: compact ? 36 : 42, height: compact ? 44 : 52, border: `${i < 3 ? 2 : 1}px solid ${i < 3 ? C.slate : C.border}`, borderRadius: compact ? 6 : 8, background: C.white, display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: compact ? 18 : 20, fontWeight: 700 }}>{d}</div>)}</div>;
}

const assets = {
  storageDashboard: { avatar: A('d38dc962-5559-42a1-902a-fea2de36c419.png'), bell: A('81ec3bb3-224c-497b-9098-ca159a60163e.svg'), dotG: A('908b1036-357f-4354-8c9f-2221891c85eb.svg'), line: A('a4ee19d3-1526-4889-8043-c01d52b8a280.svg') },
  inwardList: { back: A('b3f098fe-6479-4d11-9699-54256c3f8720.svg'), clock: A('41c9f872-f81d-40a0-a46f-6f250279acfb.svg'), inbox: A('3c167404-ab30-4bfb-b24b-557696392f43.svg') },
  inwardScan: { qr: A('f7c32f0c-864f-493b-aa4a-05b00eb4784b.svg') },
  assign: {}, bond: { qr: A('36bf9524-8307-4276-979c-e4ab1d3ee64d.svg') },
  inventory: {}, lot: { shieldOff: A('e9de68e3-dbef-4ca4-ab0b-ab48ed0e5ab4.svg') },
  condition: { temp: A('c4ff3f27-6039-482c-a86c-2523629edcbc.svg'), drop: A('fbddff97-3429-4e6a-80b3-160117aa6c69.svg'), alert: A('78947f71-9c50-48c0-b66a-6c2d631e39ab.svg') },
  rating: { star: A('03a79990-f90e-45bd-b458-b2c238104437.svg'), starHalf: A('73bff8be-6cff-41a0-a542-b96b9a60ab5a.svg'), starSmall: A('01a8ed26-2a65-48e9-8c55-3a85182b193d.svg') },
};

function StorageDashboard() {
  const acts = [['Inward: TRD-123 (Rajesh)', '2h ago', C.green], ['Outward: Bond #B-456 released', '5h ago', C.blue], ['Sample request from CA Priya', '1d ago', C.amber]];
  return <Page id="2041:312" footer={<BottomNav active="Home" />}>
    <StatusBar /><div style={{ padding: '20px 20px 24px' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 20 }}><div><div style={{ color: C.slate2, fontSize: 14 }}>Good morning,</div><div style={{ color: C.slate, fontSize: 20, fontWeight: 700, marginTop: 4 }}>Guntur Cold Storage</div></div><div style={{ display: 'flex', gap: 12, alignItems: 'center' }}><div style={{ width: 40, height: 40, border: `1px solid ${C.border}`, borderRadius: 20, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>♧</div><img src={assets.storageDashboard.avatar} alt="" style={{ width: 40, height: 40, borderRadius: 20, objectFit: 'cover' }} /></div></div>
      <Card style={{ marginBottom: 20 }}><div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 14, color: C.slate2, fontWeight: 600 }}><span>Total Capacity</span><strong style={{ color: C.slate }}>10,000 bags</strong></div><div style={{ height: 10, background: C.bg, borderRadius: 5, overflow: 'hidden', marginTop: 12 }}><div style={{ height: '100%', width: '85%', background: C.slate }} /></div><div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 8, fontSize: 12 }}><span style={{ color: C.slate2 }}>Used: 8,500 bags</span><strong>85%</strong></div></Card>
      <div style={{ display: 'flex', gap: 12, marginBottom: 28 }}>{[['Pending Inward','3',C.amber,C.amberBg],['Pending Outward','2',C.amber,C.amberBg],['Rent Due','₹1.25L',C.red,C.redBg]].map(([t,v,fg,bg]) => <Card key={String(t)} style={{ width: 110, padding: 12 }}><div style={{ fontSize: 11, color: C.slate2, fontWeight: 600 }}>{t}</div><div style={{ display: 'inline-block', background: bg as string, color: fg as string, borderRadius: 6, padding: '4px 8px', marginTop: 8, fontSize: 12, fontWeight: 600 }}>{v}</div></Card>)}</div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}><div style={{ fontSize: 18, fontWeight: 700 }}>Recent Activity</div><span style={{ color: C.blue, fontWeight: 600, fontSize: 14 }}>See all</span></div>
      <Card style={{ marginBottom: 20 }}>{acts.map(([title,time,color], i) => <div key={title} style={{ display: 'flex', gap: 16, minHeight: i < acts.length - 1 ? 72 : 28 }}><div style={{ width: 8, position: 'relative', display: 'flex', flexDirection: 'column', alignItems: 'center' }}><div style={{ width: 8, height: 8, borderRadius: 8, background: color }} />{i < acts.length - 1 && <div style={{ width: 1, flex: 1, background: C.border, marginTop: 3 }} />}</div><div><div style={{ fontSize: 14, fontWeight: 600 }}>{title}</div><div style={{ color: C.slate2, fontSize: 12, marginTop: 2 }}>{time}</div></div></div>)}</Card>
      <div style={{ fontSize: 16, fontWeight: 700, marginBottom: 12 }}>Quick Actions</div><div style={{ display: 'flex', justifyContent: 'space-between' }}>{[['▣','Scan In'],['↗','Process Out'],['▤','Gen Bond'],['◔','Capacity']].map(([ic,txt]) => <div key={String(txt)} style={{ width: 72, display:'flex', flexDirection:'column', alignItems:'center', gap:8 }}><div style={{ width:56,height:56,borderRadius:16,background:'#607d8b',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:24 }}>{ic}</div><div style={{fontSize:11,color:C.slate2,fontWeight:600,textAlign:'center'}}>{txt}</div></div>)}</div>
    </div>
  </Page>;
}

function InwardRequests() {
  const rows = [['REQ #9021','TRD-CHL-089234','Rajesh Kumar','Chilli • 500 Bags • 25,000kg','Exp: Today, 04:30 PM'],['REQ #9018','TRD-MZ-012837','Suresh P.','Maize • 200 Bags • 10,000kg','Exp: Today, 06:00 PM'],['REQ #8992','TRD-WH-077421','Anil Reddy','Wheat • 150 Bags • 7,500kg','Exp: Tomorrow, 10:00 AM']];
  return <Page id="2041:313" footer={<div style={{padding:'0 20px 20px'}}><Button>Process Inward</Button><div style={{display:'flex',justifyContent:'center',paddingTop:21}}><div style={{width:134,height:5,borderRadius:99,background:C.slate}}/></div></div>}>
    <StatusBar/><Header title="Inward Requests"/><Tabs labels={['Pending (3)','In Progress (1)','Completed (5)']} active={0}/><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}>{rows.map(r=><Card key={r[0]} style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:16}}>{r[0]}</strong><span style={{background:C.bg,color:C.slate2,borderRadius:4,padding:'4px 8px',fontFamily:'monospace',fontSize:10}}>{r[1]}</span></div><div style={{marginTop:12}}><div style={{fontSize:14,fontWeight:600}}>{r[2]}</div><div style={{fontSize:13,color:C.slate2,marginTop:4}}>{r[3]}</div></div><div style={{display:'flex',gap:6,alignItems:'center',marginTop:10,color:C.blue,fontSize:12,fontWeight:600}}>◷ {r[4]}</div></Card>)}<div style={{opacity:.4,textAlign:'center',padding:24}}><div style={{fontSize:42}}>⌑</div><div style={{fontSize:14,color:C.slate2}}>End of list</div></div></div>
  </Page>;
}

function Tabs({ labels, active = 0 }: { labels: string[]; active?: number }) { return <div style={{ display:'flex', padding:'0 20px', borderBottom:`1px solid ${C.border}` }}>{labels.map((x,i)=><div key={x} style={{padding:'16px 24px',color:i===active?C.slate:C.slate2,fontSize:14,fontWeight:i===active?700:500,position:'relative'}}>{x}{i===active && <div style={{position:'absolute',height:3,width:40,bottom:-1,left:'50%',transform:'translateX(-50%)',background:C.slate,borderRadius:2}}/>}</div>)}</div>; }

function InwardScanning() { return <Page id="2041:314" footer={<div style={{padding:'0 20px 20px'}}><Button>Confirm Inward</Button><div style={{display:'flex',justifyContent:'center',paddingTop:21}}><div style={{width:134,height:5,borderRadius:99,background:C.slate}}/></div></div>}><StatusBar/><Header title="Inward Scanning" back={false} leftIcon={<span style={{fontSize:28}}>×</span>}/><div style={{padding:24,display:'flex',flexDirection:'column',alignItems:'center',gap:24}}><QrBox qr={A('f7c32f0c-864f-493b-aa4a-05b00eb4784b.svg')} /><div style={{textAlign:'center',fontSize:14,color:C.slate2}}>Scan token QR or transporter permit<div style={{color:C.blue,textDecoration:'underline',fontWeight:600,marginTop:2}}>Enter manually</div></div><Card style={{width:'100%',padding:20}}><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{[['Token ID','TRD-CHL-089234'],['Commodity','Chilli (Dry)'],['Bags Recv.','500'],['Weight (kg)','25,000']].map(([l,v])=><div key={l}><div style={{fontSize:12,color:C.slate2,marginBottom:6}}>{l}</div><div style={{height:l==='Bags Recv.'||l==='Weight (kg)'?44:40,border:`${l==='Bags Recv.'||l==='Weight (kg)'?'1px solid '+C.border:'0px'} solid ${C.border}`,background:l==='Bags Recv.'||l==='Weight (kg)'?C.white:C.bg,borderRadius:8,display:'flex',alignItems:'center',padding:'0 12px',fontSize:13,fontFamily:l==='Token ID'?'monospace':'Inter'}}>{v}</div></div>)}</div><div style={{fontSize:14,fontWeight:700,margin:'18px 0 12px'}}>Owner OTP Verification</div><Otp/></Card></div></Page>; }

function QrBox({qr}: {qr:string}) { return <div style={{width:200,height:200,border:`2px solid ${C.slate}`,borderRadius:24,position:'relative',display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(0,0,0,.04)',overflow:'hidden'}}><div style={{position:'absolute',left:0,right:0,top:'50%',height:2,background:C.blue,opacity:.6}}/><div style={{position:'absolute',left:10,top:10,width:22,height:22,borderLeft:'4px solid '+C.slate,borderTop:'4px solid '+C.slate}}/><div style={{position:'absolute',right:10,top:10,width:22,height:22,borderRight:'4px solid '+C.slate,borderTop:'4px solid '+C.slate}}/><div style={{position:'absolute',left:10,bottom:10,width:22,height:22,borderLeft:'4px solid '+C.slate,borderBottom:'4px solid '+C.slate}}/><div style={{position:'absolute',right:10,bottom:10,width:22,height:22,borderRight:'4px solid '+C.slate,borderBottom:'4px solid '+C.slate}}/><Img src={qr} size={80}/></div>; }

function AssignStorage() { const bins = ['A1','A2','A3','A4','A5','A6','A7','A8','A9','A10','A11','A12','A13','A14','A15','B1']; const full = new Set(['A1','A4','A7','A10','A13']); return <Page id="2041:315" footer={<div style={{padding:'0 20px 20px'}}><div style={{display:'flex',gap:12}}><Button secondary>Auto-Assign (AI)</Button><Button>Confirm</Button></div><div style={{display:'flex',justifyContent:'center',paddingTop:21}}><div style={{width:134,height:5,borderRadius:99,background:C.slate}}/></div></div>}><StatusBar/><Header title="Assign Storage Location"/><div style={{padding:20}}><Card><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><strong>Facility Map</strong><div style={{display:'flex',gap:12,fontSize:11,color:C.slate2}}><span>■ Avail</span><span>■ Full</span></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(5,50px)',gap:10,marginTop:16}}>{bins.map((b)=>{const selected=b==='B1'; const isFull=full.has(b); return <div key={b} style={{width:50,height:50,borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',background:selected?C.blueBg:(isFull?C.slate:C.greenBg),border:selected?`2px solid ${C.blue}`:(isFull?'none':`1px solid ${C.green}`),color:selected?C.blue:(isFull?C.white:C.green),fontWeight:700,fontSize:12}}>{b}</div>})}</div></Card><div style={{marginTop:20,background:C.blueBg,border:`1px solid ${C.blue}`,borderRadius:12,padding:20}}><div style={{color:C.blue,fontWeight:700,fontSize:14}}>Selected: Bin B-45 (Main Hall)</div><div style={{color:C.slate2,fontSize:12,marginTop:12}}>Supports: Up to 600 bags • 30,000kg. Climate controlled zone.</div></div></div></Page>; }

function BondGenerated() { return <Page id="2041:316" footer={<div style={{padding:'0 20px 20px'}}><Button>Done</Button><div style={{display:'flex',justifyContent:'center',paddingTop:21}}><div style={{width:134,height:5,borderRadius:99,background:C.slate}}/></div></div>}><StatusBar/><Header title="Bond Generated" back={false}/><div style={{padding:24,display:'flex',flexDirection:'column',alignItems:'center',gap:24}}><div style={{width:64,height:64,borderRadius:32,background:C.green,color:C.white,display:'flex',alignItems:'center',justifyContent:'center',fontSize:32}}>✓</div><Card style={{width:'100%',padding:24}}><div style={{color:C.slate2,fontSize:12}}>e-WHR Bond Number</div><div style={{fontSize:18,fontWeight:800,color:C.slate,marginTop:4}}>GCS-BOND-20250620-001</div><div style={{borderTop:`1px dashed ${C.border}`,margin:'20px 0'}}/>{[['Token ID','TRD-CHL-089234'],['Owner','Rajesh Kumar'],['Location','Bin B-45 (Main Hall)'],['Quantity','500 Bags (25,000kg)']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',fontSize:13,marginTop:12}}><span style={{color:C.slate2}}>{l}</span><strong style={{color:C.text}}>{v}</strong></div>)}<div style={{display:'flex',justifyContent:'center',paddingTop:20}}><div style={{background:C.bg,borderRadius:12,padding:10}}><Img src={assets.bond.qr} size={100}/></div></div></Card><div style={{display:'flex',gap:12,width:'100%'}}><Button secondary>⇩ PDF</Button><Button secondary>♧ Share</Button></div></div></Page>; }

function StorageInventory() { const data=[['BOND #8801','Chilli • Rajesh Kumar','500 Bags','12 days',C.green,C.greenBg],['BOND #8754','Maize • Suresh P.','200 Bags','42 days',C.amber,C.amberBg],['BOND #8421','Wheat • Anil Reddy','150 Bags','74 days',C.red,C.redBg],['BOND #8311','Chilli • Harish M.','300 Bags','8 days',C.green,C.greenBg]]; return <Page id="2041:317" footer={<BottomNav active="Bonds"/>}><StatusBar/><Header title="Storage Inventory" back={false} leftIcon={<span style={{fontSize:24}}>☰</span>}/><div style={{padding:20}}><div style={{display:'flex',gap:8,marginBottom:18,overflow:'hidden'}}>{['All','Chilli','Maize','Wheat'].map((x,i)=><Pill key={x} active={i===0}>{x}</Pill>)}</div><div style={{display:'flex',flexDirection:'column',gap:12}}>{data.map(([bond,owner,bags,days,fg,bg])=><Card key={String(bond)} style={{padding:16,display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:15,fontWeight:700,color:C.slate}}>{bond}</div><div style={{fontSize:13,color:C.slate2,marginTop:8}}>{owner}</div><div style={{display:'flex',gap:12,alignItems:'center',marginTop:8}}><strong style={{fontSize:13}}>{bags}</strong><span style={{background:bg as string,color:fg as string,borderRadius:6,padding:'4px 8px',fontSize:12,fontWeight:600}}>{days}</span></div></div><div style={{fontSize:28,color:C.border}}>›</div></Card>)}</div></div><div style={{padding:'0 20px 16px',display:'flex',justifyContent:'flex-end'}}><div style={{width:56,height:56,borderRadius:28,background:C.slate,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:28,boxShadow:C.shadow}}>+</div></div></Page>; }

function LotDetail() { return <Page id="2041:318" footer={<div style={{padding:'0 20px 20px'}}><div style={{display:'flex',gap:12}}><Button danger>Release Lot</Button><Button>Notify Owner</Button></div><BottomNav active="Bonds"/></div>}><StatusBar/><Header title="Lot Detail"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Bond Summary</h3>{[['Bond ID','GCS-001'],['Token ID','TRD-CHL-089234'],['Owner','Rajesh Kumar'],['Commodity','Chilli Teja Grade A'],['Quantity','50 bags / 2,480 kg'],['Location','Rack B-12'],['Inward Date','15 May 2025']].map(([l,v],i)=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize':'14px',marginBottom:12}}><span style={{color:C.slate2,fontSize:14}}>{l}</span><strong style={{color:i===0?C.blue:C.text,fontSize:i===1?11:14,fontFamily:i===1?'monospace':'inherit'}}>{v}</strong></div>)}</Card><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Condition Logs</h3><div style={{fontSize:14,color:C.slate2,lineHeight:1.8}}>● 20 Jun • 6°C • 65% humidity — <span style={{color:C.green,fontWeight:700}}>Normal</span><br/>● 18 Jun • 5.8°C • 64% humidity — <span style={{color:C.green,fontWeight:700}}>Normal</span></div></Card><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Rent Overview</h3>{[['Days Stored','25'],['Rate','₹5/bag/day'],['Subtotal','₹6,250'],['GST (18%)','₹1,125']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between',fontSize:14,margin:'0 0 12px'}}><span style={{color:C.slate2}}>{l}</span><strong>{v}</strong></div>)}<div style={{background:C.slate,color:C.white,borderRadius:8,padding:12,display:'flex',justifyContent:'space-between'}}><span>Total Due</span><strong>₹7,375</strong></div></Card><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Finance & Insurance</h3><div style={{textAlign:'center',padding:'8px 0',color:C.slate2,fontSize:14}}>◁<div style={{marginTop:8}}>No active loan or additional insurance</div></div></Card></div></Page>; }

function RentInvoice() { return <Page id="2041:320" footer={<BottomNav active="Bonds"/>}><StatusBar/><Header title="Rent Invoice"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:20}}><Card style={{padding:24}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><span style={{fontSize:12,color:C.slate2,textTransform:'uppercase'}}>Tax Invoice</span><span style={{background:C.amberBg,color:C.amber,borderRadius:6,padding:'4px 8px',fontSize:11,fontWeight:600}}>PENDING</span></div><div style={{marginTop:20}}><div style={{fontSize:12,color:C.slate2}}>Invoice Number</div><div style={{fontSize:16,fontWeight:700,marginTop:4}}>INV-GCS-2025-089</div></div><div style={{marginTop:18}}>{[['Bond','GCS-001'],['Billing Period','20 Jun – 20 Jul 2025'],['Storage Days','30'],['Bags Count','50'],['Rate/Bag','₹5.00']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize':'14px',marginBottom:8}}><span style={{color:C.slate2}}>{l}</span><strong>{v}</strong></div>)}</div><div style={{borderTop:`1px dashed ${C.border}`,margin:'8px 0 16px'}}/>{[['Subtotal','₹7,500.00'],['GST (18%)','₹1,350.00']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize:14,marginBottom:8}}><span style={{color:C.slate2}}>{l}</span><strong>{v}</strong></div>)}<div style={{display:'flex',justifyContent:'space-between,alignItems':'center',paddingTop:8}}><strong style={{fontSize:18}}>Total Payable</strong><strong style={{fontSize:24}}>₹8,850</strong></div></Card><Button>Send Invoice to Owner</Button><Button secondary>Download PDF</Button><div style={{border:`1px dashed ${C.border}`,borderRadius:12,padding:16}}><div style={{fontSize:11,textTransform:'uppercase',color:C.slate2,fontWeight:600,marginBottom:12}}>Invoice Timeline</div><div style={{fontSize:14,color:C.text,lineHeight:2.1}}>✓ Generated <span style={{color:C.slate2}}>20 Jul</span><br/>✉ Sent to Owner <span style={{color:C.slate2}}>21 Jul</span><br/>◉ Viewed by Owner <span style={{color:C.slate2}}>22 Jul</span></div></div></div></Page>; }

function OutwardRequests() { const rows=[['REQ #1024','DUES: ₹7,500','BOND #GCS-001','Owner: Rajesh Kumar','By: Priya Agencies','Est. Release: 24 Jun 2025',C.amber,C.amberBg],['REQ #1022','CLEARED','BOND #GCS-012','Owner: Suresh P.','By: Own Collection','Est. Release: Today',C.green,C.greenBg]]; return <Page id="2041:321" footer={<BottomNav active="Outward"/>}><StatusBar/><Header title="Outward Requests"/><Tabs labels={['Pending (2)','Cleared (4)','Released (10)']} active={0}/><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}>{rows.map(r=><Card key={r[0]} style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:16}}>{r[0]}</strong><span style={{background:r[7] as string,color:r[6] as string,borderRadius:6,padding:'4px 8px',fontSize:11,fontWeight:600}}>{r[1]}</span></div><div style={{marginTop:12,fontSize:14,fontWeight:600}}>{r[2]}</div><div style={{fontSize:13,color:C.slate2,marginTop:4}}>{r[3]}</div><div style={{fontSize:12,color:C.slate2,marginTop:14}}>▣ {r[4]}</div><div style={{fontSize:12,color:C.slate2,marginTop:8}}>▦ {r[5]}</div><div style={{marginTop:14}}><Button>Process Release</Button></div></Card>)}</div></Page>; }

function OutwardScanning() { return <Page id="2041:322" footer={<div style={{padding:'0 20px 20px'}}><Button>Confirm Outward</Button><BottomNav active="Outward"/></div>}><StatusBar/><Header title="Outward Scanning"/><div style={{padding:24,display:'flex',flexDirection:'column',alignItems:'center',gap:24}}><QrBox qr={A('1662bb66-8885-448f-a21d-de675f4873d4.svg')}/><Card style={{width:'100%',padding:20}}>{[['Bond Number','GCS-001'],['Owner','Rajesh Kumar'],['Quantity','50 bags / 2,480 kg']].map(([l,v],i)=><div key={l} style={{display:'flex',justifyContent:'space-between',fontSize:14,marginBottom:12}}><span style={{color:C.slate2}}>{l}</span><strong style={{color:i===0?C.blue:C.text}}>{v}</strong></div>)}</Card><Card style={{width:'100%'}}><h3 style={{margin:'0 0 16px',fontSize:16}}>Payment Check</h3><div style={{display:'flex',justifyContent:'space-between,fontSize':'14px',marginBottom:12}}><span style={{color:C.slate2}}>Rent Outstanding</span><strong style={{color:C.red}}>₹7,500</strong></div><div style={{display:'flex',justifyContent:'space-between,fontSize':'14px',marginBottom:12}}><span style={{color:C.slate2}}>Loan Dues</span><strong style={{color:C.green}}>₹0</strong></div><Button color={C.amber}>Clear Dues</Button></Card><div style={{width:'100%',border:`1px solid ${C.border}`,borderRadius:12,padding:16,boxSizing:'border-box',color:C.slate2}}>♙ &nbsp; NOC Status: Locked</div><div style={{width:'100%'}}><div style={{fontSize:14,fontWeight:700,marginBottom:12}}>Owner OTP for Release</div><Otp/></div></div></Page>; }

function NocGenerated() { return <Page id="2041:323" footer={<div style={{padding:'0 20px 20px'}}><Button secondary>Done</Button><BottomNav active="Bonds"/></div>}><StatusBar/><Header title="NOC Generated" back={false}/><div style={{padding:24,display:'flex',flexDirection:'column',alignItems:'center',gap:24}}><div style={{width:64,height:64,borderRadius:32,background:C.green,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:32}}>✓</div><Card style={{width:'100%',padding:32}}><div style={{textAlign:'center',fontSize:16,fontWeight:800,color:C.slate,marginBottom:24}}>NO OBJECTION CERTIFICATE</div>{[['Bond Number','GCS-001'],['Loan Account','HDFC-123456'],['Institution','HDFC Bank Ltd.'],['Amount Cleared','₹2,00,000'],['Issue Date','20 Jun 2025']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize':'14px',marginBottom:16}}><span style={{color:C.slate2}}>{l}</span><strong style={{color:l==='Amount Cleared'?C.green:C.text}}>{v}</strong></div>)}<p style={{fontSize:12,color:C.slate2,lineHeight:1.5,textAlign:'center',margin:'8px 0 20px'}}>This is to certify that all dues related to the mentioned bond have been cleared. The warehouse is authorized to release the lot.</p><div style={{display:'flex',justifyContent:'space-between,alignItems':'flex-end'}}><div style={{textAlign:'center'}}><div style={{width:80,height:80,border:`1px dashed ${C.border}`,display:'flex',alignItems:'center',justifyContent:'center',color:C.border,fontSize:10}}>OFFICIAL STAMP</div><div style={{fontFamily:'monospace',fontSize:9,marginTop:24}}>STAMP HERE</div></div><div style={{textAlign:'center'}}><div style={{width:120,height:30,borderBottom:`1px solid ${C.slate}`,fontStyle:'italic',fontSize:24,color:C.slate}}>⌁</div><div style={{fontSize:11,fontWeight:600,marginTop:8}}>Guntur Cold Storage</div></div></div></Card><div style={{display:'flex',gap:12,width:'100%'}}><Button>Download NOC PDF</Button><Button secondary>♧</Button></div></div></Page>; }

function SampleRequests() { return <Page id="2041:324" footer={<BottomNav active="More"/>}><StatusBar/><Header title="Sample Requests"/><Tabs labels={['Pending (2)','Approved (1)','Dispatched (3)']} active={0}/><div style={{padding:20}}><Card style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{display:'flex',gap:8,alignItems:'center'}}><strong style={{fontSize:14}}>Priya Agencies</strong><span style={{background:C.blueBg,color:C.blue,padding:'2px 6px',borderRadius:4,fontSize:10,fontWeight:700}}>CA</span></div><span style={{fontSize:12,color:C.slate2}}>Today, 10:45 AM</span></div>{[['Bond ID','GCS-001'],['Sample Qty','2 Bags (100 kg)'],['Purpose','Quality check for bidding']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize:14,marginTop:12}}><span style={{color:C.slate2}}>{l}</span><strong>{v}</strong></div>)}<div style={{background:C.bg,borderRadius:8,padding:12,marginTop:16}}><div style={{fontSize:12,marginBottom:10}}>Owner OTP required for approval</div><Otp compact/></div><div style={{display:'flex',gap:12,marginTop:16}}><Button danger>Reject</Button><Button secondary>Approve</Button></div></Card></div></Page>; }

function ConditionMonitoring() { return <Page id="2041:327" footer={<BottomNav active="More"/>}><StatusBar/><Header title="Condition Monitoring"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:20}}><div style={{display:'flex',gap:12}}>{[['6°C','Temperature','Range: 4–8°C'],['65%','Humidity','Range: 60–70%']].map(([v,l,r])=><Card key={l} style={{flex:1,padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><span style={{fontSize:20,color:C.slate2}}>{l==='Temperature'?'⊗':'♧'}</span><span style={{background:C.greenBg,color:C.green,padding:'4px 8px',borderRadius:6,fontSize:11,fontWeight:600}}>NORMAL</span></div><div style={{fontSize:28,fontWeight:800,marginTop:12}}>{v}</div><div style={{fontSize:12,color:C.slate2,marginTop:2}}>{l}</div><div style={{fontSize:11,color:C.slate2,marginTop:12}}>{r}</div></Card>)}</div><div style={{background:C.amberBg,border:`1px solid #ffe0b2`,borderRadius:12,padding:16,color:C.orange,fontSize:13,fontWeight:600}}>⚠ Humidity approaching upper limit – monitor closely</div><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>7-Day Trends</h3><div style={{height:190,position:'relative'}}><svg viewBox="0 0 300 170" style={{width:'100%',height:'100%'}}><polyline fill="none" stroke={C.blue} strokeWidth="2" points="0,130 45,55 90,105 140,15 190,85 235,115 300,90"/><polyline fill="none" stroke={C.slate} strokeWidth="2" points="0,165 45,135 90,120 140,85 190,105 235,125 300,150"/></svg></div><div style={{display:'flex',justifyContent:'center',gap:16,fontSize:11,color:C.slate2}}><span><i style={{display:'inline-block',width:12,height:2,background:C.blue,verticalAlign:'middle',marginRight:6}}/>Temp</span><span><i style={{display:'inline-block',width:12,height:2,background:C.slate,verticalAlign:'middle',marginRight:6}}/>Humidity</span></div></Card><div style={{fontSize:13,color:C.slate2}}>● &nbsp; Sensor GCS-S01 — Active (last ping 2 min ago)</div></div></Page>; }

function StorageLedger() { const rows=[['20 Jun','Rent Invoice #INV-881','₹6,250','-','₹18,750'],['22 Jun','Payment received','-','₹15,000','₹3,750'],['30 Jun','System Adjustment','-','₹1,250','₹2,500']]; return <Page id="2041:328" footer={<div style={{padding:'0 20px 20px'}}><div style={{display:'flex',gap:12}}><Button secondary>Export PDF</Button><Button secondary>Export CSV</Button></div><BottomNav active="Bonds"/></div>}><StatusBar/><Header title="Storage Ledger"/><div style={{padding:20}}><Card style={{marginBottom:20}}><h3 style={{margin:'0 0 16px',fontSize:16}}>Balance Summary</h3>{[['Billed Amount','₹18,750'],['Total Paid','₹15,000']].map(([l,v])=><div key={l} style={{display:'flex',justifyContent:'space-between,fontSize':'13px',marginBottom:10}}><span style={{color:C.slate2}}>{l}</span><strong style={{color:l==='Total Paid'?C.green:C.text}}>{v}</strong></div>)}<div style={{borderTop:`1px dashed ${C.border}`,margin:'4px 0 10px'}}/><div style={{display:'flex',justifyContent:'space-between,fontSize:14}}><strong>Outstanding</strong><strong style={{color:C.red,fontSize:16}}>₹3,750</strong></div></Card><div style={{display:'flex',gap:8,marginBottom:16,overflow:'hidden'}}>{['All','Rent','Payments','Adjustments'].map((x,i)=><Pill key={x} active={i===0}>{x}</Pill>)}</div><div style={{display:'flex',flexDirection:'column',gap:12}}>{rows.map(r=><Card key={r[0]} style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between,fontSize':'12px',marginBottom:12}}><strong>{r[0]}</strong><span style={{color:C.slate2}}>{r[1]}</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16}}>{[['Debit',r[2],C.red],['Credit',r[3],C.green],['Balance',r[4],C.text]].map(([l,v,c])=><div key={l}><div style={{fontSize:10,color:C.slate2}}>{l}</div><div style={{fontSize:13,fontWeight:l==='Balance'?700:500,color:c}}>{v}</div></div>)}</div></Card>)}</div></div></Page>; }

function StorageRating() { const review='Excellent facility. The temperature controls are very reliable and the staff is quite professional. Bonds are generated instantly.'; return <Page id="2041:329" footer={<BottomNav active="More"/>}><StatusBar/><Header title="Storage Rating"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:20}}><Card><div style={{display:'flex',gap:24,alignItems:'center'}}><div style={{display:'flex',flexDirection:'column',alignItems:'center'}}><div style={{fontSize:40,fontWeight:800}}>4.7</div><div style={{color:C.amber,fontSize:18}}>★★★★★</div><div style={{fontSize:12,color:C.slate2}}>342 reviews</div></div><div style={{flex:1}}>{[108,45,18,5,4].map((w,i)=><div key={i} style={{display:'flex',gap:8,alignItems:'center',marginBottom:6}}><span style={{width:8,fontSize:11,color:C.slate2}}>{5-i}</span><div style={{height:4,background:C.bg,borderRadius:2,flex:1,overflow:'hidden'}}><div style={{width:w,height:4,background:C.amber}}/></div></div>)}</div></div></Card><div style={{display:'flex',flexWrap:'wrap',gap:8}}>{['Facilities 4.8','Maintenance 4.6','Compliance 5.0','Charges 4.5'].map(x=><span key={x} style={{background:C.white,boxShadow:C.shadow,borderRadius:12,padding:'8px 12px',fontSize:12,fontWeight:600}}>{x}</span>)}</div><div style={{display:'flex',justifyContent:'space-between,alignItems':'center'}}><strong style={{fontSize:16}}>Recent Reviews</strong><span style={{color:C.blue,fontSize:14,fontWeight:600}}>Filter</span></div>{[1,2].map(i=><Card key={i} style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{display:'flex',gap:10,alignItems:'center'}}><div style={{width:32,height:32,borderRadius:16,background:C.slate,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:12,fontWeight:700}}>RK</div><div><div style={{fontSize:14,fontWeight:600}}>Rajesh Kumar</div><div style={{color:C.amber,fontSize:12}}>★★★★★</div></div></div><span style={{fontSize:11,color:C.slate2}}>2 days ago</span></div><p style={{fontSize:13,color:C.slate2,lineHeight:1.4,margin:'10px 0 0'}}>{review}</p></Card>)}</div></Page>; }

function CapacityUpdate() { return <Page id="2041:330" footer={<BottomNav active="More"/>}><StatusBar/><Header title="Capacity Update"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:20}}><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Current Capacity</h3><div style={{display:'flex',justifyContent:'space-between,fontSize':'13px',marginBottom:12}}><span style={{color:C.slate2}}>Total 10,000 bags</span><strong>85% Full</strong></div><div style={{height:12,borderRadius:6,background:C.bg,overflow:'hidden'}}><div style={{height:'100%',width:'85%',background:C.slate}}/></div><div style={{display:'flex',justifyContent:'space-between,marginTop':'10px',fontSize':'12px',color:C.slate2}}><span>● Used: 8,500</span><span style={{color:C.slate2}}>● Available: 1,500</span></div></Card><Card><h3 style={{margin:'0 0 20px',fontSize:16}}>Update Section</h3><div style={{fontSize:12,color:C.slate2,fontWeight:600}}>New Total Capacity</div><div style={{height:42,border:`1px solid ${C.border}`,borderRadius:12,display:'flex',alignItems:'center',padding:'0 12px',marginTop:8,fontSize:14}}>10,000</div><div style={{fontSize:12,color:C.slate2,fontWeight:600,marginTop:16}}>Reason for Change</div><div style={{height:42,border:`1px solid ${C.border}`,borderRadius:12,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 12px',marginTop:8,fontSize:14}}>Expansion <span>⌄</span></div><div style={{background:C.redBg,color:C.red,borderRadius:8,padding:12,fontSize:12,fontWeight:600,marginTop:18}}>ⓘ Capacity changes require admin approval</div><div style={{marginTop:18}}><Button>Save Changes</Button></div></Card><div style={{fontSize:16,fontWeight:700}}>Change History</div><Card style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between'}}><strong style={{fontSize:13}}>15 May 2025</strong><span style={{background:C.greenBg,color:C.green,borderRadius:6,padding:'4px 8px',fontSize:11,fontWeight:600}}>APPROVED</span></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:20,marginTop:12}}>{[['Old Value','8,000 bags'],['New Value','10,000 bags'],['Approver','Admin User']].map(([l,v])=><div key={l}><div style={{fontSize:10,color:C.slate2}}>{l}</div><strong style={{fontSize:13}}>{v}</strong></div>)}</div></Card></div></Page>; }

function StorageSettings() { const [services,setServices]=useState({Insurance:true,'Loan Pledge':true,'QC Services':false}); return <Page id="2041:331" footer={<div style={{padding:'0 20px 20px'}}><Button>Save All Changes</Button><BottomNav active="More"/></div>}><StatusBar/><Header title="Settings"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}>{[['Profile','Guntur Cold Storage • Guntur, AP','◯','✎'],['Pricing','₹5/bag/day • Bulk Discounts Enabled','◇','✎'],['Bank Accounts','HDFC ****1234 • ICICI ****5678','⌂','⊕'],['KYC Status','Expiry: 20 Dec 2026','✓','VERIFIED']].map(([t,s,ic,act])=><Card key={t} style={{padding:16,display:'flex',gap:16,alignItems:'center'}}><div style={{width:40,height:40,borderRadius:20,background:C.bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:20,color:C.slate2}}>{ic}</div><div style={{flex:1}}><div style={{display:'flex',gap:8,alignItems:'center'}}><strong style={{fontSize:14}}>{t}</strong>{t==='KYC Status'&&<span style={{background:C.greenBg,color:C.green,borderRadius:6,padding:'4px 8px',fontSize:11,fontWeight:600}}>{act}</span>}</div><div style={{fontSize:12,color:C.slate2,marginTop:2}}>{s}</div></div>{t!=='KYC Status'&&<span style={{fontSize:22,color:C.border}}>{act}</span>}</Card>)}<Card><strong style={{fontSize:14}}>Services</strong><div style={{display:'flex',flexDirection:'column',gap:16,marginTop:18}}>{Object.entries(services).map(([k,v])=><div key={k} style={{display:'flex',justifyContent:'space-between,alignItems':'center'}}><span style={{fontSize:13,color:C.slate2}}>{k}</span><button onClick={()=>setServices(s=>({...s,[k]:!s[k]}))} type="button" style={{width:44,height:24,borderRadius:12,border:'none',background:v?C.blue:C.border,position:'relative'}}><span style={{width:20,height:20,borderRadius:10,background:'#fff',position:'absolute',top:2,left:v?22:2}}/></button></div>)}</div></Card></div></Page>; }

function StorageReports() { const bars=[92,99,120,113,106,120]; return <Page id="2041:332" footer={<div style={{padding:'0 20px 20px'}}><div style={{display:'flex',gap:12}}><Button secondary>Export CSV</Button><Button secondary>Export PDF</Button></div><BottomNav active="More"/></div>}><StatusBar/><Header title="Reports"/><div style={{padding:20,display:'flex',flexDirection:'column',gap:20}}><div style={{display:'flex',gap:8}}>{['This Month','Last 3 Months','Custom'].map((x,i)=><Pill key={x} active={i===0}>{x}</Pill>)}</div><Card><h3 style={{margin:'0 0 20px',fontSize:16}}>Occupancy Trend</h3><div style={{height:160,display:'flex',gap:8,alignItems:'flex-end'}}>{bars.map((h,i)=><div key={i} style={{flex:1,height:140,display:'flex',flexDirection:'column',justifyContent:'flex-end',alignItems:'center',gap:8}}><div style={{width:'100%',height:h,background:C.slate,borderRadius:'4px 4px 0 0'}}/><div style={{fontSize:10,color:C.slate2}}>{['Jan','Feb','Mar','Apr','May','Jun'][i]}</div></div>)}</div></Card><Card><div style={{fontSize:12,color:C.slate2}}>Total Revenue</div><div style={{fontSize:24,fontWeight:800,marginTop:4}}>₹45,000</div><div style={{marginTop:18}}>{[['Rajesh Kumar','₹15,000',97],['Priya Agencies','₹12,000',80],['Other Clients','₹18,000',118]].map(([n,v,w])=><div key={String(n)} style={{marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between,fontSize':'13px',marginBottom:7}}><span style={{color:C.slate2}}>{n}</span><strong>{v}</strong></div><div style={{height:4,background:C.bg,borderRadius:2}}><div style={{height:'100%',width:w as number,background:C.blue}}/></div></div>)}</div></Card><Card><h3 style={{margin:'0 0 16px',fontSize:16}}>Stock Aging</h3><div style={{display:'flex',gap:24,alignItems:'center'}}><div style={{width:120,height:120,borderRadius:60,background:'conic-gradient(#43a047 0 55%, #fb8c00 55% 80%, #e53935 80% 100%)',position:'relative'}}><div style={{position:'absolute',inset:20,borderRadius:50,background:C.white,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><span style={{fontSize:12,color:C.slate2}}>Total</span><strong style={{fontSize:18}}>100</strong></div></div><div style={{display:'flex',flexDirection:'column',gap:12,fontSize:11,color:C.slate2}}><span>■ 0-30 days</span><span>■ 30-60 days</span><span>■ 60+ days</span></div></div></Card></div></Page>; }

export default function StorageOperations18Screens({ screen = '2041:312' }: Props) {
  const id = screen as ScreenId;
  switch(id){
    case '2041:312': return <StorageDashboard/>;
    case '2041:313': return <InwardRequests/>;
    case '2041:314': return <InwardScanning/>;
    case '2041:315': return <AssignStorage/>;
    case '2041:316': return <BondGenerated/>;
    case '2041:317': return <StorageInventory/>;
    case '2041:318': return <LotDetail/>;
    case '2041:320': return <RentInvoice/>;
    case '2041:321': return <OutwardRequests/>;
    case '2041:322': return <OutwardScanning/>;
    case '2041:323': return <NocGenerated/>;
    case '2041:324': return <SampleRequests/>;
    case '2041:327': return <ConditionMonitoring/>;
    case '2041:328': return <StorageLedger/>;
    case '2041:329': return <StorageRating/>;
    case '2041:330': return <CapacityUpdate/>;
    case '2041:331': return <StorageSettings/>;
    case '2041:332': return <StorageReports/>;
    default: return <StorageDashboard/>;
  }
}
