import React from "react";

const green = "#16a34a";
const dark = "#1e293b";
const muted = "#64748b";
const bg = "#f8fafc";

function Shell({ title, children, footer = true }: { title: string; children: React.ReactNode; footer?: boolean }) {
  return (
    <div style={{ width: 375, minHeight: 812, background: bg, color: dark, fontFamily: "Inter, Arial, sans-serif", display: "flex", flexDirection: "column" }}>
      <div style={{ height: 44, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 20px", background: "#fff" }}><span style={{ fontSize: 13, fontWeight: 600 }}>9:41</span><span style={{ fontSize: 12 }}>▮▮ ◌ ▭</span></div>
      <div style={{ background: "#fff", padding: "14px 20px 16px", borderBottom: "1px solid #e2e8f0", fontSize: 19, fontWeight: 700 }}>{title}</div>
      <div style={{ flex: 1, padding: 20 }}>{children}</div>
      {footer && <div style={{ height: 72, background: "#fff", borderTop: "1px solid #e2e8f0", display: "flex", alignItems: "center", justifyContent: "space-around", color: muted, fontSize: 11 }}><span>Home</span><span style={{ color: green, fontWeight: 700 }}>KYC</span><span>Reports</span><span>More</span></div>}
    </div>
  );
}

const Field = ({ label, value }: { label: string; value: string }) => <div style={{ marginBottom: 14 }}><div style={{ fontSize: 11, fontWeight: 700, color: muted, textTransform: "uppercase", marginBottom: 6 }}>{label}</div><div style={{ background: "#fff", border: "1px solid #cbd5e1", borderRadius: 10, padding: "12px 14px", fontSize: 14 }}>{value}</div></div>;
const Button = ({ children, outline = false }: { children: React.ReactNode; outline?: boolean }) => <button style={{ width: "100%", height: 48, borderRadius: 10, border: outline ? `1.5px solid ${green}` : `1px solid ${green}`, background: outline ? "#fff" : green, color: outline ? green : "#fff", fontWeight: 700, fontSize: 15 }}>{children}</button>;
const Card = ({ children }: { children: React.ReactNode }) => <div style={{ background: "#fff", borderRadius: 14, padding: 16, boxShadow: "0 2px 8px rgba(15,23,42,.06)", marginBottom: 14 }}>{children}</div>;

function KycDashboard(){return <Shell title="KYC Verification"><div style={{fontSize:12,color:muted,marginBottom:12}}>Choose your KYC level. Higher tiers unlock better limits.</div><Card><div style={{fontWeight:700}}>Minimum KYC <span style={{float:"right",color:green,fontSize:11}}>ACTIVE</span></div><div style={{color:muted,fontSize:12,marginTop:6}}>Basic access</div><div style={{marginTop:10,fontSize:13}}>• Basic access<br/>• Limited payouts data</div></Card><Card><div style={{fontWeight:700}}>Gold KYC <span style={{float:"right",color:green,fontSize:11}}>SELECTED</span></div><div style={{marginTop:8,fontSize:13}}>• Higher limits<br/>• Priority verification<br/>• More services</div></Card><Card><div style={{fontWeight:700}}>Platinum KYC</div><div style={{marginTop:8,fontSize:13}}>• Advanced limits<br/>• Premium access</div></Card></Shell>}
function Identity(){return <Shell title="Identity Verification" footer={false}><div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:22}}><i style={{width:8,height:8,borderRadius:"50%",background:green}}/><i style={{width:8,height:8,borderRadius:"50%",background:green}}/><i style={{width:8,height:8,borderRadius:"50%",background:green}}/><i style={{width:8,height:8,borderRadius:"50%",background:"#cbd5e1"}}/></div><Card><div style={{height:180,borderRadius:14,background:"linear-gradient(135deg,#ecfdf5,#d1fae5)",display:"flex",alignItems:"center",justifyContent:"center",color:green,fontWeight:700}}>Tap to upload Aadhaar or ID card</div></Card><Button>Continue</Button></Shell>}
function Face(){return <Shell title="Face Verification" footer={false}><div style={{display:"flex",gap:8,justifyContent:"center",marginBottom:22}}>{[1,2,3,4].map((x,i)=><i key={x} style={{width:8,height:8,borderRadius:"50%",background:i<3?green:"#e2e8f0"}}/>)}</div><Card><div style={{height:300,borderRadius:20,background:"linear-gradient(135deg,#6b6256,#b6a38e)",display:"flex",alignItems:"center",justifyContent:"center",color:"#fff",position:"relative"}}><div style={{width:180,height:240,border:"2px dashed #fff",borderRadius:"50%"}}/><div style={{position:"absolute",bottom:14,left:0,right:0,textAlign:"center",fontSize:12}}>Position your face in the oval. Ensure good lighting.</div></div></Card><div style={{display:"flex",gap:8,justifyContent:"center",fontSize:11,color:muted,marginBottom:18}}><span>💡 Good light</span><span>🙂 Neutral expression</span><span>🚫 No glasses</span></div><div style={{textAlign:"center",color:muted,marginBottom:18}}>◌ Checking liveness...</div><div style={{textAlign:"center",marginBottom:30}}><span style={{background:"#dcfce7",color:green,fontWeight:700,padding:"8px 16px",borderRadius:8}}>Face matched ✓</span></div><Button>Continue</Button></Shell>}
function Address(){return <Shell title="Address Details"><Field label="Full Name" value="Ramesh Kumar"/><Field label="City / Town" value="Guntur"/><div style={{display:"flex",gap:10}}><div style={{flex:1}}><Field label="District" value="Guntur"/></div><div style={{flex:1}}><Field label="State" value="Andhra Pradesh"/></div></div><Field label="Pincode" value="522001"/><div style={{height:120,borderRadius:12,background:"#f1f5f9",display:"flex",alignItems:"center",justifyContent:"center",color:muted,marginBottom:14}}>Tap to pin on map</div><Button outline>Use current location</Button><div style={{height:10}}/><Button>Save Address</Button></Shell>}
function Bank(){return <Shell title="Bank Account"><Field label="Account Holder Name" value="Ramesh Kumar"/><Field label="Account Number" value="•••• 4821"/><Field label="IFSC Code" value="SBIN0001234"/><Field label="Bank Name" value="State Bank of India"/><Card><div style={{fontWeight:700}}>State Bank of India</div><div style={{color:muted,fontSize:12,marginTop:4}}>Branch verified • Account holder matched</div></Card><Button>Save Bank Account</Button></Shell>}
function Pending(){return <Shell title="KYC Verification Pending"><div style={{textAlign:"center",fontSize:46,marginTop:30}}>◔</div><div style={{fontWeight:700,fontSize:18,textAlign:"center",marginTop:14}}>KYC is under review</div><div style={{color:muted,fontSize:13,textAlign:"center",marginTop:8}}>We are validating your documents. This can take 1–2 business days.</div><Card><div style={{color:green,fontWeight:700}}>Identity Uploaded</div><div style={{color:green,fontWeight:700,marginTop:10}}>Selfie Verified</div><div style={{color:"#f59e0b",fontWeight:700,marginTop:10}}>Address Verification Pending</div><div style={{color:"#94a3b8",fontWeight:700,marginTop:10}}>Bank Account Verification</div></Card><Button>Go to Dashboard</Button></Shell>}
function Upgrade(){return <Shell title="Upgrade KYC"><Card><div style={{fontWeight:700}}>Current KYC</div><div style={{color:green,fontWeight:700,marginTop:4}}>Gold</div></Card><Card><div style={{fontWeight:700}}>Platinum KYC</div><div style={{marginTop:6,fontSize:13}}>Higher transaction limits and premium services.</div></Card><div style={{fontSize:13,color:muted,margin:"12px 0"}}>Upgrade fee: ₹2,432.50</div><Button>Pay ₹2,432 & Upgrade</Button></Shell>}
function Welcome(){return <Shell title="Identity Verification" footer={false}><div style={{marginTop:100,textAlign:"center"}}><div style={{width:64,height:64,borderRadius:"50%",background:green,color:"white",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px",fontWeight:800}}>TRD</div><div style={{fontSize:24,fontWeight:800}}>Welcome to TRADIE!</div><div style={{color:muted,fontSize:13,marginTop:8}}>You've successfully completed your KYC verification.</div><div style={{display:"flex",justifyContent:"center",gap:20,margin:"24px 0"}}><div><b>50</b><div style={{fontSize:11,color:muted}}>TRADIE Coins</div></div><div><b>₹50</b><div style={{fontSize:11,color:muted}}>Wallet Bonus</div></div></div><Button>Go to Dashboard</Button><div style={{height:10}}/><Button outline>Learn about TRADIE Coins</Button></div></Shell>}
function MarketPrices(){return <Shell title="Market Prices"><div style={{background:"#fff",border:"1px solid #dce5d8",borderRadius:12,padding:"12px 14px",color:"#72796f",marginBottom:12}}>⌕ Search commodity...</div><div style={{display:"flex",gap:8,overflow:"hidden",marginBottom:10}}>{["All","Chilli","Paddy","Turmeric","Cotton"].map((x,i)=><span key={x} style={{padding:"8px 14px",borderRadius:999,background:i===0?"#2e7d32":"#fff",color:i===0?"#fff":"#424940",border:i===0?"none":"1px solid #dce5d8",fontSize:12,fontWeight:700}}>{x}</span>)}</div>{[["Chilli","₹145","₹172","₹160"],["Paddy","₹2100","₹2350","₹2200"],["Turmeric","₹5800","₹6400","₹6150"],["Cotton","₹6800","₹7400","₹7100"],["Soybean","₹4200","₹4800","₹4500"]].map(r=><Card key={r[0]}><div style={{display:"flex",justifyContent:"space-between",fontSize:13}}><b>{r[0]}</b><span>MIN {r[1]} &nbsp; MAX {r[2]} &nbsp; <b style={{color:green}}>AVG {r[3]}</b></span></div></Card>)}<Card><div style={{fontWeight:700,marginBottom:8}}>Historical Price (30 days)</div><div style={{height:140,borderRadius:12,background:"linear-gradient(180deg,#f8fafc,#fff)",display:"flex",alignItems:"center",justifyContent:"center",color:green}}>⌁╱╲╱╲╱⌁</div></Card><Button outline>Set Price Alert</Button></Shell>}

export function KycMarket14Screens(){return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(375px,1fr))",gap:20,padding:20,background:"#111"}}>{[KycDashboard,Identity,Face,Address,Bank,Pending,Upgrade,Welcome,MarketPrices].map((C,i)=><div key={i}><C/></div>)}</div>}

export default function KycMarket14Router(){const r=window.location.hash.replace(/^#/,'');const map:Record<string,React.FC>={"kyc-dashboard":KycDashboard,"kyc-identity":Identity,"kyc-face":Face,"kyc-address":Address,"kyc-bank":Bank,"kyc-pending":Pending,"kyc-upgrade":Upgrade,"kyc-welcome":Welcome,"market-prices":MarketPrices};const C=map[r]||KycDashboard;return <C/>}
