import React, { ReactNode, useState } from 'react';

type ScreenProps = { children: ReactNode; id: string; height?: number; footer?: ReactNode };
type IconProps = { src: string; size?: number; style?: React.CSSProperties };

const C = {
  bg: '#f5f7fa', white: '#ffffff', text: '#1a1a1a', muted: '#666666', border: '#e0e4e8',
  blue: '#283593', green: '#2e7d32', red: '#d32f2f', orange: '#ff8f00', cyan: '#00bcd4',
  lavender: '#e8eaf6', greenBg: '#e8f5e9', redBg: '#ffebee', orangeBg: '#fff8e1', track: '#e0e4e8'
};
const font = { fontFamily: 'DM Sans, Arial, sans-serif' } as React.CSSProperties;
const geist = { fontFamily: 'Geist, DM Sans, Arial, sans-serif' } as React.CSSProperties;
const inter = { fontFamily: 'Inter, DM Sans, Arial, sans-serif' } as React.CSSProperties;

function Img({src, size=20, style}: IconProps) {
  return <img src={src} alt="" style={{ width: size, height: size, display: 'block', objectFit: 'contain', ...style }} />;
}

function StatusBar({signal, wifi, battery, combined, compact=false}: {signal:string; wifi?:string; battery?:string; combined?:string; compact?:boolean}) {
  return <div style={{height:44,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',boxSizing:'border-box',...font}}>
    <span style={{fontSize:compact?14:16,fontWeight:compact?600:700,lineHeight:'1.4'}}>9:41</span>
    <div style={{display:'flex',alignItems:'center',gap:6,height:12}}>{combined ? <Img src={combined} size={70} style={{width:70,height:12}}/> : <><Img src={signal} size={18}/>{wifi && <Img src={wifi} size={16}/>} {battery && <Img src={battery} size={24}/>}</>}</div>
  </div>;
}

function TitleBar({title, arrow, right, center=false}: {title:string; arrow:string; right?:ReactNode; center?:boolean}) {
  return <div style={{height:56,padding:'0 20px',display:'flex',alignItems:'center',justifyContent:center?'space-between':'flex-start',gap:16,boxSizing:'border-box'}}>
    <Img src={arrow} size={24}/>
    <h1 style={{margin:0,fontSize:24,fontWeight:700,lineHeight:'1.2',color:C.text,...geist,flex:center?0:1,whiteSpace:'nowrap'}}>{title}</h1>
    {right ?? <div style={{width:24,height:24}}/>}
  </div>;
}

function Card({children, style}: {children:ReactNode; style?:React.CSSProperties}) {
  return <div style={{background:C.white,borderRadius:16,padding:16,boxSizing:'border-box',boxShadow:'0 4px 6px rgba(0,0,0,.04)',...style}}>{children}</div>;
}
function Badge({children, bg, color}: {children:ReactNode; bg:string; color:string}) {
  return <span style={{display:'inline-flex',alignItems:'center',padding:'4px 8px',borderRadius:6,background:bg,color,fontSize:11,fontWeight:700,lineHeight:1,...inter,whiteSpace:'nowrap'}}>{children}</span>;
}
function PrimaryButton({children, style, onClick}: {children:ReactNode;style?:React.CSSProperties;onClick?:()=>void}) {
  return <button onClick={onClick} style={{height:44,border:0,borderRadius:8,background:C.blue,color:C.white,padding:'0 16px',fontSize:13,fontWeight:600,cursor:'pointer',...inter,...style}}>{children}</button>;
}
function OutlineButton({children, style, onClick, red=false}: {children:ReactNode;style?:React.CSSProperties;onClick?:()=>void;red?:boolean}) {
  return <button onClick={onClick} style={{height:48,border:`1px solid ${red?C.red:C.blue}`,borderRadius:12,background:'transparent',color:red?C.red:C.blue,padding:'0 16px',fontSize:16,fontWeight:600,cursor:'pointer',...geist,...style}}>{children}</button>;
}
function Toggle({on=true, width=44}: {on?:boolean;width?:number}) {
  return <div style={{width,height:24,borderRadius:12,background:on?C.blue:'#cfd3d8',position:'relative',boxSizing:'border-box'}}><div style={{position:'absolute',top:2,left:on?width-22:2,width:20,height:20,borderRadius:10,background:C.white,boxShadow:'0 1px 2px rgba(0,0,0,.18)'}}/></div>;
}

const nav333 = {
  home:'https://www.figma.com/api/mcp/asset/4f5dd23b-c6f3-46f8-8576-00ed9f6179e5.svg',
  applications:'https://www.figma.com/api/mcp/asset/2464c073-17aa-4b7b-81a0-7521d2c179ae.svg',
  collateral:'https://www.figma.com/api/mcp/asset/44d33d5f-d7f1-4966-b4d2-00e22e469397.svg',
  bill:'https://www.figma.com/api/mcp/asset/95d6337d-42fa-4bad-a806-c7a8006123d7.svg',
  more:'https://www.figma.com/api/mcp/asset/ba4f1a95-6f58-40f6-be41-5071f4d2308f.svg'
};
const nav334 = {
  home:'https://www.figma.com/api/mcp/asset/1d41c540-0155-4aca-8802-333b4f7e92c1.svg',
  applications:'https://www.figma.com/api/mcp/asset/f3b539f7-093f-4266-9ee5-e0b838d2144c.svg',
  collateral:'https://www.figma.com/api/mcp/asset/634c49a6-42ea-4c5d-b771-f7fdffeed934.svg',
  bill:'https://www.figma.com/api/mcp/asset/535945cd-f6a8-4146-a1e8-019fec3c1327.svg',
  more:'https://www.figma.com/api/mcp/asset/2918524a-1606-4426-ab72-59f62b44b72e.svg'
};
const nav337 = {
  home:'https://www.figma.com/api/mcp/asset/88be375f-d976-48ab-933d-9b5a4217953c.svg',
  applications:'https://www.figma.com/api/mcp/asset/fa4d1972-c062-4aa7-9caa-5c53fc5f3aed.svg',
  collateral:'https://www.figma.com/api/mcp/asset/da11d006-7770-4d9a-a2b9-c040dd66ba2f.svg',
  bill:'https://www.figma.com/api/mcp/asset/c4232604-112f-44e2-9dd4-14779916b69c.svg',
  more:'https://www.figma.com/api/mcp/asset/0012552f-1421-4356-8ba5-f265eb35f60c.svg'
};
const nav339 = {
  home:'https://www.figma.com/api/mcp/asset/875053a3-3a37-43a1-bbd6-ba50146654c7.svg',
  applications:'https://www.figma.com/api/mcp/asset/1dc18c95-6c39-4ff7-a775-bcac16254337.svg',
  collateral:'https://www.figma.com/api/mcp/asset/86a92ab3-89dc-4408-b554-988a4e338ef3.svg',
  bill:'https://www.figma.com/api/mcp/asset/3f67b032-681a-47ac-afa2-745317479d6f.svg',
  more:'https://www.figma.com/api/mcp/asset/2a66e15c-a417-4987-941d-84e5e3d58ce8.svg'
};
const nav341 = {
  home:'https://www.figma.com/api/mcp/asset/b59e73de-93d7-4046-992c-dacf290b3043.svg',
  applications:'https://www.figma.com/api/mcp/asset/5158a26f-2da6-4356-9b43-46739fa04de2.svg',
  collateral:'https://www.figma.com/api/mcp/asset/8bc720e6-b3c8-4f74-a4e7-76ce199e5e6f.svg',
  bill:'https://www.figma.com/api/mcp/asset/e06f6a7a-55d6-4e41-86c1-b2396ed519d3.svg',
  more:'https://www.figma.com/api/mcp/asset/592191bc-3772-4e20-b38d-f5d89378a40c.svg'
};
const nav343 = {
  home:'https://www.figma.com/api/mcp/asset/27f48ea8-e6db-48f0-af10-ebdd58fcdcf3.svg',
  applications:'https://www.figma.com/api/mcp/asset/81d4784d-5338-4fc8-8621-110536a4b851.svg',
  collateral:'https://www.figma.com/api/mcp/asset/d21dc9c9-3b40-4858-89d4-e15bb6da6ca4.svg',
  bill:'https://www.figma.com/api/mcp/asset/fcc86632-1e79-4a8e-8b89-a9acede4e133.svg',
  more:'https://www.figma.com/api/mcp/asset/6eb85320-a43d-4e3e-86b2-9cb66d6a3c6c.svg'
};
const nav344 = {
  home:'https://www.figma.com/api/mcp/asset/35c8ef54-f344-45fd-b491-63cfcd8ffc40.svg',
  applications:'https://www.figma.com/api/mcp/asset/21361006-bd28-4707-b9a9-5ec91330a1c4.svg',
  collateral:'https://www.figma.com/api/mcp/asset/59f8230a-25fc-423e-8b60-aab4329a35a1.svg',
  bill:'https://www.figma.com/api/mcp/asset/44bd4380-4b3c-46c8-8ee5-ef22075331e9.svg',
  more:'https://www.figma.com/api/mcp/asset/8681fc42-10ef-4229-a364-a92a25cf9121.svg'
};

function BottomNav({active, icons}:{active:string;icons:typeof nav333}) {
  const items:[keyof typeof icons,string][]=[['home','Home'],['applications','Applications'],['collateral','Collateral'],['bill','Bill'],['more','More']];
  return <div style={{background:C.white,borderTop:`1px solid ${C.border}`,width:'100%'}}>
    <div style={{height:84,padding:'12px 16px 0',display:'flex',justifyContent:'space-between',boxSizing:'border-box'}}>
      {items.map(([key,label])=><div key={label} style={{width:68,display:'flex',flexDirection:'column',alignItems:'center',gap:4}}><Img src={icons[key]} size={24}/><span style={{fontSize:10,fontWeight:600,color:active===label?C.blue:C.muted,...inter,whiteSpace:'nowrap'}}>{label}</span></div>)}
    </div>
    <div style={{height:24,display:'flex',alignItems:'flex-start',justifyContent:'center',paddingBottom:8,boxSizing:'border-box'}}><div style={{width:134,height:5,borderRadius:99,background:'rgba(0,0,0,.13)'}}/></div>
  </div>;
}
function Screen({children,id,height=812,footer}:ScreenProps) {
  return <div data-node-id={id} style={{width:375,minHeight:height,background:C.bg,color:C.text,...font,display:'flex',flexDirection:'column',boxSizing:'border-box',margin:'0 auto',overflow:'hidden'}}><div style={{flex:1,minHeight:0}}>{children}</div>{footer}</div>;
}

const s333={signal:'https://www.figma.com/api/mcp/asset/4537564f-38e1-4034-adf5-6c81a3c7ca6e.svg',wifi:'https://www.figma.com/api/mcp/asset/84950eba-8556-4a5f-a5d2-d3807d9eb60b.svg',bell:'https://www.figma.com/api/mcp/asset/b28efe11-3ab2-4d9a-a292-15942a1d9359.svg',alert:'https://www.figma.com/api/mcp/asset/a864f7dc-3e60-4021-aede-7a451666ad10.svg',plus:'https://www.figma.com/api/mcp/asset/424f0412-4194-4579-93be-ba689b0330f1.svg',avatar:'https://www.figma.com/api/mcp/asset/b121ea90-e004-43f7-b014-c5333271ff3a.png'};
function Dashboard(){return <Screen id="2041:333" footer={<BottomNav active="Home" icons={nav333}/>}> <StatusBar signal={s333.signal} wifi={s333.wifi}/><div style={{padding:'12px 20px 20px'}}>
  <div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:14}}><div><div style={{color:C.blue,fontSize:12,fontWeight:600,textTransform:'uppercase',...font}}>TRADIE FI</div><div style={{fontSize:20,fontWeight:600,lineHeight:1.2,...geist}}>HDFC – Agri Lending</div></div><div style={{display:'flex',gap:16,alignItems:'center'}}><Img src={s333.bell} size={24}/><div style={{width:36,height:36,borderRadius:18,overflow:'hidden'}}><Img src={s333.avatar} size={36}/></div></div></div>
  <div style={{display:'flex',gap:12,overflow:'hidden'}}>{[['Total Disbursed','₹5.00 Cr',C.blue],['Active Loans','342',C.blue],['Overdue 30+','12',C.red]].map(([label,value,color],i)=><Card key={String(label)} style={{width:160,flex:'0 0 160px',padding:16,boxShadow:'0 2px 2px rgba(0,0,0,.02)'}}><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>{label}</div><div style={{fontSize:20,fontWeight:600,color:String(color),marginTop:8,...geist}}>{value}</div>{i===2&&<div style={{marginTop:8}}><Badge bg={C.redBg} color={C.red}>High Risk</Badge></div>}</Card>)}</div>
  <section style={{marginTop:20}}><div style={{display:'flex',justifyContent:'space-between',marginBottom:16}}><div style={{fontSize:16,fontWeight:600,...geist}}>Pending Applications</div><div style={{fontSize:14,fontWeight:600,color:C.blue}}>View All</div></div><Card style={{padding:16}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{minWidth:0}}><div style={{fontSize:16,fontWeight:600,...geist}}>Rajesh Kumar (Producer)</div><div style={{fontSize:12,color:C.muted,lineHeight:1.4}}>TRD-CHL-089234 (Chilli)</div></div><div style={{fontSize:16,fontWeight:600,color:C.blue,...geist}}>₹2,50,000</div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:12}}><div style={{display:'flex',alignItems:'center',gap:6,fontSize:12,color:C.muted}}>AI Risk Score: <Badge bg={C.orangeBg} color={C.orange}>7.2/10 Medium</Badge></div><PrimaryButton style={{height:32,padding:'0 16px'}}>Review</PrimaryButton></div></Card></section>
  <div style={{marginTop:20,display:'flex',gap:12,alignItems:'flex-start',border:`1px solid ${C.red}`,background:C.redBg,borderRadius:12,padding:12,color:C.red,fontSize:12,lineHeight:1.4}}><Img src={s333.alert} size={20}/><span>Token TRD-123 value dropped 12% – margin call triggered</span></div>
  <section style={{marginTop:20}}><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',marginBottom:12}}>Quick Actions</div><div style={{display:'flex',gap:12}}>{['New App','Bill Purchase','Reports'].map(x=><div key={x} style={{flex:1,background:C.white,border:`1px solid ${C.border}`,borderRadius:12,padding:12,textAlign:'center',boxSizing:'border-box'}}><div style={{width:40,height:40,borderRadius:20,background:C.lavender,display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto'}}><Img src={s333.plus} size={20}/></div><div style={{fontSize:11,fontWeight:600,marginTop:8,...inter,whiteSpace:'nowrap'}}>{x}</div></div>)}</div></section>
</div></Screen>}

const s334={signal:'https://www.figma.com/api/mcp/asset/0be9a906-0a25-45ab-b764-da636b10f537.svg',wifi:'https://www.figma.com/api/mcp/asset/c1832319-7d4d-4dca-85dd-974fcf6f488b.svg',battery:'https://www.figma.com/api/mcp/asset/f5978dba-c061-4f81-aa4e-72e77eaf683a.svg',arrow:'https://www.figma.com/api/mcp/asset/e6168f1b-f63a-4aeb-8a90-fb6ee1db2a94.svg',filter:'https://www.figma.com/api/mcp/asset/4b6fae67-c9da-46cc-ad21-fc8a7e1998b1.svg'};
function LoanApplications(){const rows=[['Priya Agencies (CA)','Working Capital · 3 Tokens','₹5,00,000','6.5/10 Amber',C.orangeBg,C.orange,true],['Sunil Traders','Term Loan · TRD-Paddy-01','₹8,20,000','8.1/10 High',C.redBg,C.red,false],['Agro Exports','Bill Discount · INV-442','₹15,00,000','4.2/10 Low',C.greenBg,C.green,false]] as const;return <Screen id="2041:334" footer={<BottomNav active="Applications" icons={nav334}/>}> <StatusBar signal={s334.signal} wifi={s334.wifi} battery={s334.battery}/><TitleBar title="Loan Applications" arrow={s334.arrow} right={<Img src={s334.filter} size={24}/>} center/><div style={{height:46,borderBottom:`1px solid ${C.border}`,display:'flex',gap:20,padding:'0 20px',boxSizing:'border-box'}}>{[['Pending (8)',true],['Approved (12)',false],['Rejected (3)',false]].map(([x,a])=><div key={String(x)} style={{height:46,paddingTop:12,boxSizing:'border-box',borderBottom:a?`3px solid ${C.blue}`:'none',color:a?C.blue:C.muted,fontSize:16,fontWeight:500,...font,whiteSpace:'nowrap'}}>{x}</div>)}</div><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}>{rows.map((r,i)=><div key={r[0]} style={{borderLeft:i===0?`4px solid ${C.orange}`:'none',borderRadius:i===0?'4px 16px 16px 4px':16}}><Card style={{padding:16}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div style={{minWidth:0}}><div style={{fontSize:16,fontWeight:600,...geist}}>{r[0]}</div><div style={{fontSize:12,color:C.muted,lineHeight:1.4}}>{r[1]}</div></div><div style={{fontSize:16,fontWeight:600,color:C.blue,...geist}}>{r[2]}</div></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:12}}><div style={{display:'flex',alignItems:'center',gap:6,fontSize:12,color:C.muted}}>AI Risk Score: <Badge bg={r[4]} color={r[5]}>{r[3]}</Badge></div><PrimaryButton style={{height:32,padding:'0 16px'}}>Review</PrimaryButton></div></Card></div>)}</div></Screen>}

const s335={signal:'https://www.figma.com/api/mcp/asset/f46c723c-37ff-4403-b1b7-aadb7d7be1a4.svg',wifi:'https://www.figma.com/api/mcp/asset/3193d142-7c93-48a2-8141-feb0d3b32644.svg',battery:'https://www.figma.com/api/mcp/asset/ac6aae87-bf6c-4b87-93b0-1614fd12a0be.svg',arrow:'https://www.figma.com/api/mcp/asset/d7cdd001-5785-47b7-9bf1-5636b73b2c2f.svg'};
function ApplicationReview(){return <Screen id="2041:335" height={951}><StatusBar signal={s335.signal} wifi={s335.wifi} battery={s335.battery}/><div style={{padding:'0 20px'}}><TitleBar title="Application Review" arrow={s335.arrow}/><div style={{display:'flex',flexDirection:'column',gap:16}}><Card><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>Priya Agencies</div><div style={{fontSize:14,color:C.muted,lineHeight:1.5}}>Commission Agent</div></div><Badge bg={C.lavender} color={C.blue}>KYC Platinum</Badge></div><div style={{display:'flex',gap:24,marginTop:12}}><div><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>Past Loans</div><div style={{fontSize:16,fontWeight:500,marginTop:2}}>3</div></div><div><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>Repaid</div><div style={{fontSize:16,fontWeight:500,color:C.green,marginTop:2}}>2</div></div></div></Card>
<Card><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',marginBottom:12}}>Loan Details</div><div style={{display:'flex',flexWrap:'wrap',columnGap:24,rowGap:12}}>{[['Amount','₹5,00,000',C.text],['Tenure','12 Months',C.text],['Interest','11% p.a.',C.blue]].map(([a,b,c])=><div key={String(a)} style={{width:100}}><div style={{fontSize:12,color:C.muted}}>{a}</div><div style={{fontSize:16,fontWeight:600,color:String(c),marginTop:2,...geist}}>{b}</div></div>)}</div><div style={{fontSize:14,color:C.muted,marginTop:12,lineHeight:1.5}}>Purpose: working capital for chilli procurement</div></Card>
<div style={{background:C.blue,color:C.white,borderRadius:16,padding:16}}><div style={{fontSize:12,fontWeight:600,opacity:.7,textTransform:'uppercase',marginBottom:12}}>Collateral Overview</div><div style={{display:'flex',flexDirection:'column',gap:8,fontSize:14,lineHeight:1.5}}><div style={{display:'flex',justifyContent:'space-between'}}><span>Chilli (120MT)</span><b>₹33.6L</b></div><div style={{display:'flex',justifyContent:'space-between'}}><span>Paddy (50MT)</span><b>₹11.0L</b></div><div style={{height:1,background:'rgba(255,255,255,.2)'}}/><div style={{display:'flex',justifyContent:'space-between',color:C.cyan,fontSize:16,fontWeight:600,...geist}}><span>Total Value / LTV</span><span>₹44.6L / 11%</span></div></div></div>
<Card style={{display:'flex',gap:16,alignItems:'center'}}><div style={{width:64,height:64,borderRadius:32,border:`4px solid ${C.orange}`,display:'flex',alignItems:'center',justifyContent:'center',boxSizing:'border-box',flex:'0 0 64px'}}><div style={{fontSize:20,fontWeight:600,...geist}}>6.5</div></div><div><div style={{fontSize:16,fontWeight:600,...geist}}>Medium Risk</div><div style={{fontSize:12,color:C.muted,lineHeight:1.4,marginTop:4}}>Market volatility is currently medium</div></div></Card>
<div style={{paddingTop:4,display:'flex',flexDirection:'column',gap:12}}><PrimaryButton style={{height:56,borderRadius:12,background:C.green,fontSize:16,...geist}}>Approve Application</PrimaryButton><div style={{display:'flex',gap:12}}><OutlineButton red style={{flex:1}}>Reject</OutlineButton><OutlineButton style={{flex:1,borderColor:C.muted,color:C.muted}}>Request Info</OutlineButton></div></div></div></div></Screen>}

const s336={signal:'https://www.figma.com/api/mcp/asset/eac8ceea-789d-4a90-894e-6010fe144921.svg',wifi:'https://www.figma.com/api/mcp/asset/4090c813-59c1-41d4-8256-8289f1d79016.svg',battery:'https://www.figma.com/api/mcp/asset/2b0b9388-e963-46c2-8fc2-25fafe56af65.svg',arrow:'https://www.figma.com/api/mcp/asset/e70a5bf4-db11-46da-b03e-58f9e8b3e163.svg',check:'https://www.figma.com/api/mcp/asset/6aefce07-3e57-4225-bd9e-86689253813a.svg'};
function Disburse(){return <Screen id="2041:336"><StatusBar signal={s336.signal} wifi={s336.wifi} battery={s336.battery}/><div style={{padding:'0 20px'}}><TitleBar title="Disburse Loan" arrow={s336.arrow}/><div style={{display:'flex',flexDirection:'column',gap:24}}><div style={{background:C.lavender,borderRadius:16,padding:16}}><div style={{fontSize:12,fontWeight:600,color:C.blue,textTransform:'uppercase'}}>Loan Summary</div><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginTop:8}}><div style={{fontSize:20,fontWeight:600,...geist}}>₹5,00,000</div><div style={{fontSize:14,color:C.muted}}>Priya Agencies</div></div></div><div><div style={{fontSize:16,fontWeight:600,...geist,marginBottom:16}}>Disbursement Method</div><div style={{display:'flex',gap:8,marginBottom:16}}>{['Bank Transfer','UPI','TRD Wallet'].map((x,i)=><div key={x} style={{background:i===0?C.blue:C.white,color:i===0?C.white:C.text,border:`1px solid ${C.border}`,borderRadius:99,padding:'10px 16px',fontSize:13,fontWeight:600,...inter,whiteSpace:'nowrap'}}>{x}</div>)}</div><div style={{background:C.white,border:`1px solid ${C.border}`,borderRadius:12,padding:16}}><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>HDFC Account</div><div style={{fontSize:16,fontWeight:500,marginTop:4}}>XXXX XXXX 4521</div></div></div><div style={{display:'flex',flexDirection:'column',gap:12}}><PrimaryButton style={{height:56,borderRadius:12,fontSize:16,...geist}}>Confirm Disbursement</PrimaryButton><div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12}}><div style={{fontSize:14,color:C.muted}}>Enter OTP sent to registered number</div><div style={{display:'flex',gap:8}}>{Array.from({length:6}).map((_,i)=><div key={i} style={{width:44,height:52,background:C.white,border:`1px solid ${C.border}`,borderRadius:8,display:'flex',alignItems:'center',justifyContent:'center',fontSize:20,fontWeight:600,...geist}}>•</div>)}</div></div></div><div style={{background:C.greenBg,borderRadius:20,padding:24,display:'flex',flexDirection:'column',alignItems:'center',gap:12}}><div style={{width:56,height:56,borderRadius:28,background:C.green,display:'flex',alignItems:'center',justifyContent:'center'}}><Img src={s336.check} size={28}/></div><div style={{fontSize:16,fontWeight:600,color:C.green,...geist}}>Loan Disbursed Successfully</div><div style={{fontSize:12,color:C.green}}>Borrower notified via TRADIE App</div></div></div></div></Screen>}

const s337={signal:'https://www.figma.com/api/mcp/asset/fdeacc58-09ce-46ae-8d06-5baeb1b2380d.svg',wifi:'https://www.figma.com/api/mcp/asset/48276dc6-66cf-4933-8b93-9be3d4951371.svg',battery:'https://www.figma.com/api/mcp/asset/97dd0eea-0763-4481-b957-e2d7ee2bcae0.svg',arrow:'https://www.figma.com/api/mcp/asset/f531c397-44de-407d-8a98-bd50c7b4dcb4.svg',search:'https://www.figma.com/api/mcp/asset/3b6d1999-db47-4f36-b4ab-9985a1a6263a.svg'};
function Collateral(){return <Screen id="2041:337" footer={<BottomNav active="Collateral" icons={nav337}/>}> <StatusBar signal={s337.signal} wifi={s337.wifi} battery={s337.battery}/><TitleBar title="Collateral Monitoring" arrow={s337.arrow}/><div style={{padding:'0 20px',display:'flex',flexDirection:'column',gap:16}}><div style={{height:44,background:C.white,border:`1px solid ${C.border}`,borderRadius:12,display:'flex',alignItems:'center',gap:8,padding:'0 12px',boxSizing:'border-box'}}><Img src={s337.search} size={20}/><span style={{fontSize:14,color:C.muted}}>Search borrower or token ID</span></div><div style={{display:'flex',flexDirection:'column',gap:12}}><Card style={{borderLeft:`4px solid ${C.green}`,borderRadius:'4px 16px 16px 4px'}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontSize:16,fontWeight:600,...geist}}>TRD-CHL-089234</div><Badge bg={C.greenBg} color={C.green}>Healthy</Badge></div><div style={{marginTop:12}}><div style={{fontSize:12,color:C.muted}}>Owner: Rajesh Kumar</div><div style={{fontSize:16,color:C.blue,fontWeight:500,marginTop:4}}>₹33,60,000 (LTV 80%)</div></div><div style={{marginTop:12}}><Badge bg={C.orangeBg} color={C.orange}>Value dropped 5% – Within tolerance</Badge></div><div style={{display:'flex',gap:8,marginTop:12}}><div style={{flex:1,height:40,borderRadius:8,background:C.lavender,color:C.blue,display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:600,...inter}}>View Details</div><div style={{flex:1,height:40,borderRadius:8,border:`1px solid ${C.blue}`,display:'flex',alignItems:'center',justifyContent:'center',fontSize:13,fontWeight:600,color:C.blue,...inter}}>Margin Call</div></div></Card><Card style={{border:`2px solid ${C.red}`}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontSize:16,fontWeight:600,...geist}}>TRD-WHL-112</div><Badge bg={C.redBg} color={C.red}>CRITICAL</Badge></div><div style={{marginTop:12}}><div style={{fontSize:12,color:C.muted}}>Owner: Mehta Traders</div><div style={{fontSize:16,color:C.red,fontWeight:500,marginTop:4}}>Value dropped 22%!</div></div><PrimaryButton style={{width:'100%',height:40,marginTop:12,background:C.red}}>Trigger Margin Call</PrimaryButton></Card></div></div></Screen>}

const s338={signal:'https://www.figma.com/api/mcp/asset/d5ee7a6b-fbfa-49d2-bc38-aed90de4b83b.svg',wifi:'https://www.figma.com/api/mcp/asset/87967380-284e-4339-8ed2-0841c9893ab3.svg',battery:'https://www.figma.com/api/mcp/asset/e2a4068f-e173-4da5-9e4c-0653f1709f25.svg',arrow:'https://www.figma.com/api/mcp/asset/816f68c9-f984-4d5c-9640-aaed0b9d7a57.svg',close:'https://www.figma.com/api/mcp/asset/6561a92d-4109-493c-9a9b-bd21aa26c2c0.svg'};
function BillPurchase(){const [open,setOpen]=useState(true);return <Screen id="2041:338"><StatusBar signal={s338.signal} wifi={s338.wifi} battery={s338.battery}/><TitleBar title="Bill Purchase" arrow={s338.arrow}/><div style={{padding:'0 20px',display:'flex',flexDirection:'column',gap:12}}>{[['INV-001','Priya Agencies → ABC Exports','₹1,20,000','7.2/10'],['INV-002','Sunil Traders → Global Rice','₹85,000','6.1/10']].map(r=><Card key={r[0]}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontSize:16,fontWeight:600,...geist}}>{r[0]}</div><Badge bg={C.greenBg} color={C.green}>{r[3]}</Badge></div><div style={{fontSize:14,marginTop:10}}>{r[1]}</div><div style={{fontSize:20,fontWeight:600,color:C.blue,marginTop:2,...geist}}>{r[2]}</div><div style={{fontSize:12,color:C.muted,marginTop:2}}>Due in 15 days</div><PrimaryButton onClick={()=>setOpen(true)} style={{width:'100%',height:44,marginTop:12}}>Offer Discount</PrimaryButton></Card>)}</div>{open&&<div style={{position:'fixed',inset:0,width:'100%',height:'100%',background:'rgba(0,0,0,.25)',display:'flex',alignItems:'flex-end',justifyContent:'center',zIndex:20}}><div style={{width:375,background:C.white,borderRadius:'32px 32px 0 0',padding:24,boxSizing:'border-box',boxShadow:'0 -8px 12px rgba(0,0,0,.2)'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div style={{fontSize:20,fontWeight:600,...geist}}>Send Discount Offer</div><button onClick={()=>setOpen(false)} style={{border:0,background:'transparent',padding:0}}><Img src={s338.close} size={24}/></button></div><div style={{marginTop:24,display:'flex',flexDirection:'column',gap:12}}><div style={{fontSize:14,color:C.muted}}>Selected Discount: 3.0%</div><div style={{height:8,background:C.lavender,borderRadius:4,position:'relative'}}><div style={{height:8,width:100,background:C.blue,borderRadius:4}}/><div style={{position:'absolute',left:88,top:-8,width:24,height:24,borderRadius:12,border:`2px solid ${C.blue}`,background:C.white}}/></div><div style={{display:'flex',justifyContent:'space-between',fontSize:14,lineHeight:1.5}}><span>Invoice Amt: ₹1,20,000</span><b style={{color:C.blue}}>Net: ₹1,16,400</b></div></div><div style={{display:'flex',flexDirection:'column',gap:12,marginTop:20}}><PrimaryButton style={{height:56,borderRadius:12,fontSize:16,...geist}}>Send Offer</PrimaryButton><button onClick={()=>setOpen(false)} style={{height:48,border:0,background:'transparent',color:C.muted,fontSize:16,fontWeight:600,...geist}}>Cancel</button></div><div style={{width:134,height:5,borderRadius:99,background:'rgba(0,0,0,.06)',margin:'12px auto 0'}}/></div></div>}</Screen>}

const s339={signal:'https://www.figma.com/api/mcp/asset/dd10de89-3c81-447d-ae39-dca36598fb49.svg',arrow:'https://www.figma.com/api/mcp/asset/b5d1f13d-b406-43db-b659-bdb9889c868e.svg'};
function Repayments(){return <Screen id="2041:339" footer={<BottomNav active="Home" icons={nav339}/>}> <StatusBar signal={s339.signal} combined={s339.signal} compact/><TitleBar title="Repayments" arrow={s339.arrow}/><div style={{padding:'0 20px'}}><div style={{background:C.blue,color:C.white,borderRadius:16,padding:16}}><div style={{fontSize:12,fontWeight:600,opacity:.7,textTransform:'uppercase'}}>Total Due This Month</div><div style={{fontSize:28,fontWeight:700,marginTop:12,...geist}}>₹1,27,000</div><div style={{display:'flex',gap:24,marginTop:16}}><div><div style={{fontSize:11,opacity:.7}}>Collected</div><div style={{fontSize:16,fontWeight:600,color:C.cyan,...geist}}>₹82,000</div></div><div><div style={{fontSize:11,opacity:.7}}>Outstanding</div><div style={{fontSize:16,fontWeight:600,...geist}}>₹45,000</div></div></div></div><div style={{height:44,border:`1px solid ${C.border}`,display:'flex',gap:20,margin:'0 -20px',padding:'0 20px',boxSizing:'border-box'}}>{[['Current',true],['1–30 Overdue',false],['30+',false]].map(([x,a])=><div key={String(x)} style={{padding:'12px 0',height:44,boxSizing:'border-box',border:a?`1px solid ${C.blue}`:'none',color:a?C.blue:C.muted,fontSize:14,fontWeight:600,whiteSpace:'nowrap'}}>{x}</div>)}</div><div style={{display:'flex',flexDirection:'column',gap:12,paddingTop:20}}>{[['Priya Agencies','Loan #L-001 · Due 15 Jul','₹45,000','Overdue 5 days',C.orangeBg,C.orange,'Remind'],['Rajesh Kumar','Loan #L-002 · Due 20 Jul','₹22,000','Upcoming',C.lavender,C.blue,'Notify'],['Mehta Traders','Loan #L-003 · Due 10 Jul','₹60,000','Paid',C.greenBg,C.green,'']].map(r=><Card key={r[0]}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>{r[0]}</div><div style={{fontSize:11,color:C.muted,marginTop:2}}>{r[1]}</div></div><div style={{fontSize:16,fontWeight:600,color:C.blue,...geist}}>{r[2]}</div></div><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginTop:12}}><Badge bg={r[4]} color={r[5]}>{r[3]}</Badge>{r[6]&&<OutlineButton style={{height:40,borderRadius:8,fontSize:13,...inter}}>{r[6]}</OutlineButton>}</div></Card>)}</div><div style={{background:C.lavender,borderRadius:12,padding:16,marginTop:20,display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:14,fontWeight:600,color:C.blue}}>Auto-deduct from sale proceeds<Toggle/></div></div></Screen>}

const s340={signal:'https://www.figma.com/api/mcp/asset/a0c202a4-6884-4474-9196-c814e492e98e.svg',arrow:'https://www.figma.com/api/mcp/asset/332d8315-6dd8-41c7-ae1e-3a907e4f6aed.svg',ring1:'https://www.figma.com/api/mcp/asset/242b57fa-8acd-425c-85be-d78f7801954e.svg',ring2:'https://www.figma.com/api/mcp/asset/1dfbecf9-dab3-4bbb-a8e8-155cd799c685.svg'};
function Risk(){const bars=[['Payment History (40%)','Good',268,C.green],['Collateral Quality (30%)','High',302,C.green],['Market Conditions (20%)','Moderate',184,C.orange],['Reputation Score (10%)','Excellent',318,C.green]] as const;return <Screen id="2041:340" height={844}><StatusBar signal={s340.signal} combined={s340.signal} compact/><TitleBar title="AI Risk Score" arrow={s340.arrow}/><div style={{padding:'0 20px 20px'}}><Card style={{border:`1px solid ${C.border}`,boxShadow:'none'}}><div style={{fontSize:16,fontWeight:600,...geist}}>Priya Agencies</div><div style={{fontSize:14,color:C.muted,marginTop:8}}>Working Capital · ₹5,00,000</div></Card><div style={{height:220,display:'flex',alignItems:'center',justifyContent:'center',paddingTop:10}}><div style={{position:'relative',width:160,height:160}}><Img src={s340.ring1} size={160}/><Img src={s340.ring2} size={160} style={{position:'absolute',left:0,top:0}}/><div style={{position:'absolute',inset:0,display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{fontSize:36,fontWeight:700,...geist}}>6.5</div><div style={{fontSize:11,color:C.orange,fontWeight:500}}>Medium Risk</div></div></div></div><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',marginBottom:16}}>Score Breakdown</div>{bars.map(b=><div key={b[0]} style={{display:'flex',flexDirection:'column',gap:6,marginBottom:10}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11}}><span style={{color:C.muted}}>{b[0]}</span><b style={{color:b[3]}}>{b[1]}</b></div><div style={{height:8,background:C.track,borderRadius:4,overflow:'hidden'}}><div style={{height:8,width:b[2],background:b[3],borderRadius:4}}/></div></div>)}<div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',marginTop:36,marginBottom:12}}>AI Recommendations</div><div style={{display:'flex',gap:12,overflow:'hidden'}}>{['Consider reducing LTV to 70%','Request documents'].map(x=><div key={x} style={{background:C.lavender,color:C.blue,borderRadius:12,padding:12,whiteSpace:'nowrap',fontSize:13,flex:'0 0 200px',...inter}}>{x}</div>)}</div><OutlineButton style={{width:'100%',height:48,borderRadius:12,fontSize:14,marginTop:40,...font}}>Export Risk Report</OutlineButton></div></Screen>}

const s341={signal:'https://www.figma.com/api/mcp/asset/0cf2e7c9-7da7-4e61-849b-5b6b67130736.svg',arrow:'https://www.figma.com/api/mcp/asset/12535e82-7ae0-44e5-a1b7-6285fc9b1b92.svg',download:'https://www.figma.com/api/mcp/asset/59acd685-a5b8-42e6-8480-298576b422fc.svg',calendar:'https://www.figma.com/api/mcp/asset/5cb9a1dd-5dc5-41fa-9a02-79dc6637495f.svg',filter:'https://www.figma.com/api/mcp/asset/eb1903c2-bbf6-483e-b317-3a0eb2e83753.svg'};
function Ledger(){const rows=[['Mehta Traders','10 Jul · Disbursal','– ₹3,00,000','Bal: ₹65.0L',C.red],['Rajesh Kumar','05 Jul · Repayment','+ ₹22,000','Bal: ₹62.0L',C.green],['Priya Agencies','01 Jul · Disbursal','– ₹5,00,000','Bal: ₹62.2L',C.red]] as const;return <Screen id="2041:341" footer={<BottomNav active="Bill" icons={nav341}/>}> <StatusBar signal={s341.signal} combined={s341.signal} compact/><TitleBar title="FI Ledger" arrow={s341.arrow} right={<Img src={s341.download} size={24}/>} center/><div style={{padding:'0 20px'}}><div style={{background:C.white,border:`2px solid ${C.cyan}`,borderRadius:16,padding:16}}><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>Outstanding Balance</div><div style={{fontSize:32,fontWeight:700,color:C.cyan,marginTop:4,...geist}}>₹65,00,000</div><div style={{display:'flex',justifyContent:'space-between',marginTop:16}}><div><div style={{fontSize:11,color:C.muted}}>Disbursed</div><div style={{fontSize:14,fontWeight:600,marginTop:4}}>₹2.50 Cr</div></div><div><div style={{fontSize:11,color:C.muted}}>Repaid</div><div style={{fontSize:14,fontWeight:600,marginTop:4}}>₹1.85 Cr</div></div></div></div><div style={{display:'flex',gap:12,padding:'20px 0'}}><div style={{background:C.white,border:`1px solid ${C.border}`,borderRadius:12,padding:'12px',display:'flex',alignItems:'center',gap:8,fontSize:14,color:C.muted}}><Img src={s341.calendar} size={18}/>Jul 01 - Jul 15</div><div style={{width:48,height:48,borderRadius:12,background:C.white,border:`1px solid ${C.border}`,display:'flex',alignItems:'center',justifyContent:'center'}}><Img src={s341.filter} size={24}/></div></div></div><div style={{borderTop:`1px solid ${C.border}`,borderBottom:`1px solid ${C.border}`}}>{rows.map(r=><div key={r[0]} style={{background:C.white,borderBottom:`1px solid ${C.border}`,padding:'20px',display:'flex',alignItems:'center',justifyContent:'space-between',boxSizing:'border-box'}}><div style={{width:180}}><div style={{fontSize:14,fontWeight:600}}>{r[0]}</div><div style={{fontSize:11,color:C.muted,marginTop:2}}>{r[1]}</div></div><div style={{textAlign:'right'}}><div style={{fontSize:14,fontWeight:600,color:r[4],...geist}}>{r[2]}</div><div style={{fontSize:11,color:C.muted,marginTop:2}}>{r[3]}</div></div></div>)}</div></Screen>}

const s342={signal:'https://www.figma.com/api/mcp/asset/9009bdfc-6e3a-4f6d-b2fc-a488adc23621.svg',arrow:'https://www.figma.com/api/mcp/asset/7a3b47f3-f710-4c69-8cc9-b34e2115f73b.svg'};
function Overdue(){return <Screen id="2041:342"><div style={{minHeight:812,display:'flex',flexDirection:'column'}}><StatusBar signal={s342.signal} combined={s342.signal} compact/><TitleBar title="Overdue Accounts" arrow={s342.arrow}/><div style={{paddingBottom:12,background:C.red,color:C.white,textAlign:'center',fontSize:14,fontWeight:600,paddingTop:12}}>12 accounts overdue – ₹45,00,000 at risk</div><div style={{padding:20,display:'flex',flexDirection:'column',gap:16}}><Card><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>Rajesh Kumar</div><div style={{fontSize:14,color:C.muted,lineHeight:1.4}}>Loan: ₹2,50,000</div></div><Badge bg={C.orangeBg} color={C.orange}>Overdue 45 days</Badge></div><div style={{display:'flex',gap:8,marginTop:12}}><PrimaryButton style={{height:36,padding:'0 10px'}}>Send Reminder</PrimaryButton><button style={{height:36,border:`1px solid ${C.muted}`,background:C.white,color:C.muted,borderRadius:8,padding:'0 10px',fontSize:13,fontWeight:600,...inter}}>Escalate</button></div></Card><Card style={{border:`2px solid ${C.red}`}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>Mehta Traders</div><div style={{fontSize:14,color:C.muted}}>Loan: ₹8,00,000</div></div><Badge bg={C.redBg} color={C.red}>Overdue 95 days</Badge></div><div style={{background:C.redBg,color:C.red,borderRadius:8,padding:10,fontSize:11,fontWeight:700,marginTop:12}}>AUTO-ESCALATED TO LEGAL</div><PrimaryButton style={{width:'100%',height:44,marginTop:12}}>View Case</PrimaryButton></Card><div style={{display:'flex',alignItems:'center',justifyContent:'space-between',fontSize:14}}>Block new loans for &gt;90d<Toggle/></div></div><div style={{marginTop:'auto',background:C.white,border:`1px solid ${C.border}`,padding:20,display:'flex',gap:12}}><button style={{height:48,background:C.white,border:`1px solid ${C.border}`,borderRadius:8,flex:1,fontSize:14,fontWeight:600,...inter}}>Select All</button><button style={{height:48,background:C.blue,color:C.white,border:0,borderRadius:8,flex:1,fontSize:14,fontWeight:600,...inter}}>Bulk Reminder</button></div></div></Screen>}

const s343={signal:'https://www.figma.com/api/mcp/asset/6679b0a4-8e06-4cc9-b96f-e95b9453c922.svg',arrow:'https://www.figma.com/api/mcp/asset/ed476e53-0ab3-4679-864d-eb83dce3fd7e.svg',alert:'https://www.figma.com/api/mcp/asset/0c509c89-59ad-4324-8ea2-d4e2b90c8d7a.svg',file:'https://www.figma.com/api/mcp/asset/5af1ea2d-4d21-4fd4-9788-c56350e92d85.svg',activity:'https://www.figma.com/api/mcp/asset/75af7e38-4a66-460c-8b7f-aa582f5233c1.svg',bar:'https://www.figma.com/api/mcp/asset/765fb1a7-bbbe-440d-a75a-edf91c64a677.svg',loader:'https://www.figma.com/api/mcp/asset/119912d1-ad05-4fca-bd4d-815376f9720a.svg'};
function Compliance(){const tiles=[['NPA Report',s343.alert,'rgba(211,47,47,.1)'],['Portfolio Quality',s343.file,'rgba(40,53,147,.1)'],['Risk Exposure',s343.activity,'rgba(255,143,0,.1)'],['Loan Disbursal',s343.bar,'rgba(46,125,50,.1)']];return <Screen id="2041:343" footer={<BottomNav active="More" icons={nav343}/>}> <StatusBar signal={s343.signal} combined={s343.signal} compact/><TitleBar title="Compliance Reports" arrow={s343.arrow}/><div style={{padding:20,display:'flex',flexWrap:'wrap',gap:12,boxSizing:'border-box'}}>{tiles.map(([label,icon,bg])=><Card key={label} style={{width:161,padding:16,boxShadow:'0 4px 6px rgba(0,0,0,.04)'}}><div style={{width:40,height:40,borderRadius:20,background:bg,display:'flex',alignItems:'center',justifyContent:'center'}}><Img src={icon} size={20}/></div><div style={{fontSize:11,fontWeight:700,marginTop:12,...font}}>{label}</div></Card>)}</div><div style={{display:'flex',gap:12,padding:'0 20px'}}>{['Month','Quarter','Year'].map((x,i)=><div key={x} style={{padding:'8px 16px',borderRadius:20,border:`1px solid ${i===1?C.blue:C.border}`,background:i===1?C.blue:C.white,color:i===1?C.white:C.muted,fontSize:13,fontWeight:600,...inter}}>{x}</div>)}</div><div style={{padding:20}}><Card style={{padding:20,borderRadius:20}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>NPA Report – Q2 2024</div><div style={{fontSize:11,color:C.muted,marginTop:4}}>Status: Generating...</div></div><Img src={s343.loader} size={20}/></div><div style={{height:1,background:C.border,margin:'20px 0'}}/><div style={{fontSize:11,color:C.muted,marginBottom:12}}>Last Generated: 01 Jul 2024</div><div style={{display:'flex',gap:12}}><PrimaryButton style={{height:40,padding:'0 8px'}}>PDF</PrimaryButton><button style={{height:40,border:`1px solid ${C.blue}`,background:C.white,color:C.blue,borderRadius:8,padding:'0 8px',fontSize:13,fontWeight:600,...inter}}>Excel</button></div></Card></div><div style={{padding:'0 20px 20px'}}><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase',marginBottom:12}}>Scheduled Reports</div><div style={{background:C.white,borderRadius:12,padding:16,display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:14,fontWeight:600}}>Monthly NPA</div><div style={{fontSize:11,color:C.muted,marginTop:2}}>Auto on 1st of month</div></div><Toggle/></div></div></Screen>}

const s344={signal:'https://www.figma.com/api/mcp/asset/9c0e1f97-966a-44ae-9371-f9c66bdcb845.svg',arrow:'https://www.figma.com/api/mcp/asset/eaa11d45-d9f1-41af-b80b-6328d0a680d2.svg',copy:'https://www.figma.com/api/mcp/asset/3f209b10-bc5f-44d9-9383-c57e7d9579ae.svg',chevron:'https://www.figma.com/api/mcp/asset/56b7df90-f6d7-4fa2-9410-1641504148c6.svg'};
function Settings(){const products=[['Working Capital','11% p.a. · LTV 80%'],['Term Loan','12.5% p.a. · LTV 70%'],['Bill Discounting','9.5% p.a. · LTV N/A']];return <Screen id="2041:344" height={1078} footer={<BottomNav active="More" icons={nav344}/>}> <StatusBar signal={s344.signal} combined={s344.signal} compact/><TitleBar title="Settings" arrow={s344.arrow}/><div style={{padding:'0 20px',display:'flex',flexDirection:'column',gap:12}}><Card style={{padding:16,boxShadow:'none'}}><div style={{display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:16,fontWeight:600,...geist}}>HDFC – Agri Lending</div><div style={{fontSize:11,color:C.muted,marginTop:4}}>RBI: RBI/2024/NBFC/001</div></div><div style={{fontSize:14,fontWeight:600,color:C.blue}}>Edit</div></div></Card><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>API Integration</div><div style={{background:C.white,borderRadius:12,padding:16,display:'flex',flexDirection:'column',gap:12}}><div style={{display:'flex',justifyContent:'space-between',fontSize:11,color:C.muted}}><span>Primary API Key</span><span style={{fontSize:14,color:C.blue,fontWeight:600}}>Regenerate</span></div><div style={{background:C.bg,borderRadius:8,padding:12,display:'flex',alignItems:'center',justifyContent:'space-between'}}><span style={{fontSize:14,...inter}}>****-****-4521</span><Img src={s344.copy} size={18}/></div></div><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>Loan Products</div><div style={{background:C.white,borderRadius:12,overflow:'hidden'}}>{products.map(([name,sub])=><div key={name} style={{border:`1px solid ${C.border}`,padding:16,display:'flex',alignItems:'center',justifyContent:'space-between'}}><div><div style={{fontSize:14,fontWeight:600}}>{name}</div><div style={{fontSize:11,color:C.muted,marginTop:2}}>{sub}</div></div><Img src={s344.chevron} size={18}/></div>)}</div><div style={{fontSize:12,fontWeight:600,color:C.muted,textTransform:'uppercase'}}>Notifications</div><div style={{background:C.white,borderRadius:12,overflow:'hidden'}}>{['New applications','Margin call alerts','Overdue reminders'].map(x=><div key={x} style={{border:`1px solid ${C.border}`,padding:16,display:'flex',alignItems:'center',justifyContent:'space-between'}}><span style={{fontSize:14}}>{x}</span><Toggle/></div>)}</div><div style={{display:'flex',justifyContent:'center',padding:'32px 0'}}><span style={{fontSize:16,fontWeight:600,color:C.red,...inter}}>Logout</span></div></div></Screen>}

export default function FigmaFI12Screens({screen}:{screen:string}) {
  switch(screen){
    case '2041:333': return <Dashboard/>;
    case '2041:334': return <LoanApplications/>;
    case '2041:335': return <ApplicationReview/>;
    case '2041:336': return <Disburse/>;
    case '2041:337': return <Collateral/>;
    case '2041:338': return <BillPurchase/>;
    case '2041:339': return <Repayments/>;
    case '2041:340': return <Risk/>;
    case '2041:341': return <Ledger/>;
    case '2041:342': return <Overdue/>;
    case '2041:343': return <Compliance/>;
    case '2041:344': return <Settings/>;
    default: return <Dashboard/>;
  }
}
