import React from 'react';

const C={bg:'#f5f5f5',card:'#fff',text:'#111827',muted:'#6b7280',orange:'#e65100',red:'#c62828',green:'#2e7d32',border:'#e5e7eb',amber:'#f57c00'};
const base={fontFamily:'DM Sans, Arial, sans-serif',background:C.bg,color:C.text,minHeight:'100vh'} as React.CSSProperties;
const btn=(background:string,color='#fff'):React.CSSProperties=>({background,color,border:'none',borderRadius:10,padding:'12px 16px',fontWeight:700,fontSize:14});
const card:React.CSSProperties={background:C.card,border:`1px solid ${C.border}`,borderRadius:14,padding:16};

export function BuyerList(){
 const buyers=[['AE','ABC Exports','Guntur · Exporter','3.2','HIGH RISK','₹1,20,000 · overdue 5 days',C.red],['SE','Sonia Enterprises','Vijayawada · Local Processor','6.5','MEDIUM RISK','₹2,50,000 · due 3 days',C.amber],['ST','Sharma Trading','Hyderabad · Wholesaler','8.9','LOW RISK','₹0 outstanding',C.green]];
 return <div style={base} data-node-id="2041:141"><div style={{padding:16,maxWidth:420,margin:'0 auto'}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',marginBottom:12}}><span>‹</span><h1 style={{fontSize:22,margin:0}}>Buyers</h1><div style={{display:'flex',gap:10}}><span>⚱</span><span style={{...btn(C.orange),borderRadius:20,padding:'7px 12px'}}>＋</span></div></div><input placeholder="Search by name, GST, or location" style={{width:'100%',boxSizing:'border-box',padding:14,border:0,borderRadius:24,background:'#f3f4f6',marginBottom:12}}/><div style={{display:'flex',gap:8,overflowX:'auto',paddingBottom:12}}>{['All','High Risk','Credit Hold','Export','Local'].map((x,i)=><span key={x} style={{padding:'8px 12px',borderRadius:999,border:`1px solid ${i===0?C.orange:C.border}`,color:i===0?'#fff':i===1?C.red:C.muted,background:i===0?C.orange:'#fff',fontSize:13,fontWeight:600}}>{x}</span>)}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginBottom:14}}>{[['Total Buyers','8'],['Outstanding','₹4,28,500'],['Overdue','2 buyers']].map(([a,b],i)=><div key={a} style={{...card,padding:12}}><div style={{fontSize:11,color:C.muted}}>{a}</div><div style={{fontSize:18,fontWeight:700,color:i===1?C.orange:i===2?C.red:C.text,marginTop:6}}>{b}</div></div>)}</div>{buyers.map(([ini,name,meta,riskScore,risk,amount,color])=><div key={name} style={{...card,display:'flex',gap:12,marginBottom:12,borderLeft:`4px solid ${color}`}}><div style={{width:40,height:40,borderRadius:20,background:color,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:700}}>{ini}</div><div style={{flex:1}}><div style={{display:'flex',justifyContent:'space-between'}}><div style={{fontWeight:700}}>{name}</div><span style={{fontSize:11,padding:'4px 8px',borderRadius:999,background:color,color:'#fff',fontWeight:700}}>{risk}</span></div><div style={{fontSize:13,color:C.muted,marginTop:4}}>{meta}</div><div style={{display:'flex',justifyContent:'space-between',marginTop:10,fontSize:13}}><span style={{fontWeight:700}}>{riskScore} ★</span><span style={{fontWeight:700,color}}>{amount}</span></div></div><div style={{alignSelf:'center',color:'#9ca3af'}}>›</div></div>)}<BottomNav active="Buyers"/></div></div>;
}

function AddBuyer(){return <FormShell title="Add Buyer"><Section title="Step 1 of 2: Basic Details"/><Field label="Business Name" placeholder="Enter business name"/><Field label="Buyer Type" placeholder="Local Wholesaler"/><Field label="GST Number" placeholder="Optional"/><Field label="Contact Person" placeholder="Full name"/><Field label="Mobile" placeholder="+91 9876543210"/><Field label="Email" placeholder="Optional"/><Field label="Address" placeholder="Street, city, state, pin"/><Field label="Payment Terms" placeholder="15 days"/><Field label="Credit Limit" placeholder="₹ Enter amount"/><button style={{...btn(C.orange),width:'100%',marginTop:8}}>Send Invite</button><div style={{...card,marginTop:12,background:'#fff8e1'}}>OTP sent to buyer's mobile</div><div style={{display:'flex',gap:8,marginTop:8}}>{Array.from({length:6}).map((_,i)=><input key={i} style={{width:38,height:42,border:`1px solid ${C.orange}`,borderRadius:6,textAlign:'center'}}/>)}</div><button style={{...btn(C.orange),width:'100%',marginTop:10}}>Verify OTP</button></FormShell>}

function BuyerProfile(){return <FormShell title="Buyer Profile"><div style={{...card,textAlign:'center'}}><div style={{width:64,height:64,borderRadius:32,background:C.red,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 10px',fontWeight:800,fontSize:22}}>AE</div><h2 style={{margin:'6px 0'}}>ABC Exports</h2><div style={{color:C.muted,fontSize:13}}>Exporter · Since Jan 2025</div><div style={{marginTop:10}}><span style={{color:C.green,fontWeight:700}}>KYC: Gold ✓</span> <span style={{color:C.red,fontWeight:700,marginLeft:12}}>Risk: 3.2/10</span></div></div><InfoCard title="Contact"><Row a="Contact" b="+91 98765 43210"/><Row a="GST" b="36AABCA1234B1Z2"/><Row a="Address" b="Guntur, AP"/><Row a="Payment Terms" b="15 days"/><Row a="Credit Limit" b="₹5,00,000"/><Row a="Credit usage" b="24%"/></InfoCard><button style={{...btn(C.orange),width:'100%'}}>Match with My Lots</button></FormShell>}

function RiskAssessment(){return <FormShell title="Risk Assessment"><InfoCard title="ABC Exports"><div style={{color:C.muted,fontSize:13}}>Exporter · Since Jan 2025</div></InfoCard><div style={{...card,textAlign:'center'}}><div style={{width:180,height:180,borderRadius:'50%',margin:'0 auto',background:'conic-gradient(#2e7d32 0 35%, #f57c00 35% 60%, #c62828 60% 100%)',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:150,height:150,borderRadius:'50%',background:'#fff',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{fontSize:40,fontWeight:800,color:C.red}}>3.2</div><div style={{fontSize:12,color:C.red,fontWeight:700}}>HIGH RISK</div></div></div><div style={{marginTop:8,fontSize:12,color:C.muted}}>Score updated: Today</div></div><div style={{...card,borderColor:C.orange,color:C.orange,fontWeight:600}}>🔒 Visible only to you. Other CAs see only the risk category.</div><InfoCard title="Score breakdown"><Metric title="Payment History · 40% weight" score="2/10" desc="On-time: 40% · Avg delay: 8 days · Max overdue: 15 days" color={C.red}/><Metric title="Purchase Volume · 25% weight" score="7/10" desc="₹12,00,000 in 6 months · Consistency: Moderate" color={C.green}/><Metric title="Dispute History · 20% weight" score="3/10" desc="2 disputes raised · 1 resolved" color={C.red}/><Metric title="Credit Utilization · 15% weight" score="8/10" desc="Used 24% of limit (healthy)" color={C.green}/></InfoCard><button style={{...btn(C.orange),width:'100%'}}>Export Report PDF</button></FormShell>}

function BuyerRequirements(){return <FormShell title="Buyer Requirements"><div style={{display:'flex',gap:8,marginBottom:12}}>{['Chilli','A','B','C','₹14k–18k'].map(x=><span key={x} style={{...card,padding:'8px 10px',fontSize:12}}>{x}</span>)}</div><div style={{...card,borderColor:C.orange}}><b>3 lots match current requirements</b><div style={{fontSize:13,color:C.muted,marginTop:4}}>Potential: ₹8,50,000</div><button style={{...btn(C.orange),marginTop:10}}>Match My Lots</button></div>{[['ABC Exports','Chilli - Teja','200 quintals (20 MT)','₹15,000–16,000/quintal','85% High Match',C.red],['Sonia Enterprises','Chilli - S4','Remaining 50 of 150 quintals','62% Medium Match','',C.amber],['Sharma Trading','Turmeric - Rajapuri','100 quintals','Expired 18 Jun 2025','Expired',C.red]].map(r=><div key={r[0]} style={{...card,marginBottom:12}}><div style={{display:'flex',justifyContent:'space-between'}}><b>{r[0]}</b><span style={{color:r[5],fontWeight:700,fontSize:12}}>{r[4]||r[3]}</span></div><div style={{fontSize:13,color:C.muted,marginTop:8}}>{r[1]}</div><div style={{marginTop:6}}>{r[2]}</div><div style={{marginTop:6,color:r[5],fontWeight:700}}>{r[3]}</div><button style={{...btn(C.orange),width:'100%',marginTop:10}}>Match Lots</button></div>)}</FormShell>}

function FormShell({title,children}:{title:string;children:React.ReactNode}){return <div style={base}><div style={{maxWidth:420,margin:'0 auto',padding:16}}><div style={{display:'flex',alignItems:'center',gap:12,marginBottom:14}}><span>‹</span><h1 style={{fontSize:20,margin:0}}>{title}</h1></div>{children}</div></div>}
function Section({title}:{title:string}){return <div style={{...card,background:'#fff8e1',color:C.orange,fontWeight:700,marginBottom:12}}>{title}</div>}
function Field({label,placeholder}:{label:string;placeholder:string}){return <label style={{display:'block',marginBottom:12,fontSize:12,fontWeight:700}}>{label}<input placeholder={placeholder} style={{display:'block',width:'100%',boxSizing:'border-box',marginTop:6,padding:12,border:`1px solid ${C.border}`,borderRadius:9}}/></label>}
function InfoCard({title,children}:{title:string;children:React.ReactNode}){return <div style={{...card,marginBottom:12}}><h3 style={{fontSize:16,margin:'0 0 10px'}}>{title}</h3>{children}</div>}
function Row({a,b}:{a:string;b:string}){return <div style={{display:'flex',justifyContent:'space-between',fontSize:13,padding:'7px 0',borderBottom:`1px solid #f0f0f0`}}><span style={{color:C.muted}}>{a}</span><b>{b}</b></div>}
function Metric({title,score,desc,color}:{title:string;score:string;desc:string;color:string}){return <div style={{marginBottom:14}}><div style={{display:'flex',justifyContent:'space-between',fontWeight:700,fontSize:13}}><span>{title}</span><span style={{color}}>{score}</span></div><div style={{fontSize:12,color:C.muted,margin:'5px 0'}}> {desc}</div><div style={{height:6,borderRadius:8,background:'#f3f4f6'}}><div style={{height:'100%',width:score.startsWith('8')?'80%':score.startsWith('7')?'70%':score.startsWith('3')?'30%':'20%',background:color,borderRadius:8}}/></div></div>}
function BottomNav({active}:{active:string}){return <div style={{display:'flex',justifyContent:'space-between',marginTop:18,paddingTop:14,borderTop:`1px solid ${C.border}`,fontSize:11,color:C.muted}}>{['Home','Producers','Buyers','Listings','More'].map(x=><div key={x} style={{textAlign:'center',color:x===active?C.orange:C.muted,fontWeight:x===active?700:400}}>{x}</div>)}</div>}

export default function Buyer5ScreenRouter(){const route=window.location.hash.replace(/^#/,''); if(route==='buyer-add')return <AddBuyer/>; if(route==='buyer-profile')return <BuyerProfile/>; if(route==='buyer-risk')return <RiskAssessment/>; if(route==='buyer-requirements')return <BuyerRequirements/>; return <BuyerList/>;}
