import React, { useState } from "react";

const C = {
  bg: "#f5f7f8", text: "#1c1b1f", muted: "#938f99", body: "#49454f", teal: "#00897b", tealLight: "#e0f2f1", border: "#cac4d0", white: "#ffffff",
};

type ScreenProps = { onBack?: () => void };
const topBack = (title: string, onBack?: () => void) => <div className="flex h-14 items-center px-4"><button onClick={onBack} className="mr-3 text-2xl">‹</button><h1 className="text-[20px] font-bold">{title}</h1></div>;
const BottomNav = () => <div className="border-t" style={{borderColor:C.border}}><div className="flex h-16 items-center justify-between px-2 bg-white text-[10px]"><div className="w-[70px] text-center font-bold" style={{color:C.teal}}>Home</div><div className="w-[70px] text-center" style={{color:C.muted}}>Schedule</div><div className="w-[70px] text-center" style={{color:C.muted}}>Reports</div><div className="w-[70px] text-center" style={{color:C.muted}}>Earnings</div><div className="w-[70px] text-center" style={{color:C.muted}}>More</div></div><div className="h-6 flex items-start justify-center bg-white"><div className="mt-2 h-1.5 w-32 rounded-full bg-black/20" /></div></div>;
const App = ({children}: {children: React.ReactNode}) => <div className="mx-auto flex min-h-screen w-[375px] flex-col" style={{background:C.bg,color:C.text,fontFamily:"Arial, sans-serif"}}>{children}</div>;
const Btn = ({children, secondary=false, onClick}:any) => <button onClick={onClick} className="h-12 flex-1 rounded-lg font-bold" style={{background:secondary?C.white:C.teal,color:secondary?C.teal:C.white,border:secondary?`1.5px solid ${C.teal}`:undefined}}>{children}</button>;
const Card = ({children}:any)=><div className="rounded-xl border bg-white p-4" style={{borderColor:C.border}}>{children}</div>;

export function InspectorDashboard({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div><div className="px-4"><div className="flex items-center justify-between py-3"><div><h1 className="text-2xl font-extrabold">Hello, Sanjay</h1><span className="rounded bg-teal-50 px-2 py-1 text-xs font-bold" style={{background:C.tealLight,color:C.teal}}>850 TRD</span></div><div className="text-2xl">◌</div></div><div className="mb-5 flex gap-3 overflow-hidden"><div className="w-[180px] shrink-0 rounded-xl p-4 text-white" style={{background:C.teal}}><div>Assigned Today</div><div className="mt-1 text-4xl font-extrabold">3</div><div className="text-xs opacity-80">Pending visits: 2</div></div><div className="w-[180px] shrink-0 rounded-xl p-4 text-white" style={{background:C.teal}}><div>Completed (Mo)</div><div className="mt-1 text-4xl font-extrabold">28</div><div className="text-xs opacity-80">Earned: ₹12,500</div></div></div><section><h2 className="mb-3 text-lg font-bold">Pending Inspections</h2><Card><div className="font-bold">TRD-CHL-089234</div><div className="text-sm" style={{color:C.body}}>Chilli (Grade A) • Priya Agencies</div><div className="my-3 text-xs" style={{color:C.body}}>▣ Scheduled Today 3:00 PM &nbsp;⌖ 5km &nbsp;<span style={{color:C.teal}}>▣ ₹500</span></div><div className="flex gap-2"><Btn>Accept</Btn><Btn secondary>Reject</Btn></div></Card></section><section className="mt-5"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Today's Schedule</h2><span style={{color:C.teal}} className="font-semibold">View All</span></div><div className="mt-3 space-y-3">{[['10:00 AM','TRD-CHL-089234','Priya Agencies'],['12:00 PM','TRD-PAD-112234','Ram Traders']].map(r=><div className="flex items-center gap-4" key={r[0]}><div className="w-[70px] text-sm font-bold" style={{color:C.muted}}>{r[0]}</div><Card><div className="font-semibold">{r[1]}</div><div className="text-xs" style={{color:C.body}}>{r[2]}</div></Card></div>)}</div></section><section className="mt-5 pb-6"><h2 className="mb-3 text-lg font-bold">Quick Actions</h2><div className="flex gap-3">{['Start Visit','Upload Report','View Disputes'].map(t=><div key={t} className="flex flex-1 flex-col items-center gap-2 rounded-lg border bg-white p-4 text-center text-[11px] font-bold" style={{borderColor:C.border}}><div className="text-2xl" style={{color:C.teal}}>↗</div>{t}</div>)}</div></section></div><div className="mt-auto"><BottomNav/></div></App>}

export function AssignedInspections({onBack}:ScreenProps){const rows=[['TRD-CHL-089234','Chilli • Priya Agencies','Pending','Today 3:00 PM','5km','₹500'],['TRD-PAD-112234','Paddy • Ram Traders','In Progress','Today 12:00 PM','2km','₹300'],['TRD-MAZ-445566','Maize • Green Agros','Completed','Today 10:00 AM','8km','₹700']];return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Assigned Inspections',onBack)}<div className="border-b bg-white"><div className="grid grid-cols-4 text-center text-xs"><div className="border-b-2 py-4 font-bold" style={{borderColor:C.teal,color:C.teal}}>Pending(3)</div><div className="py-4">Accepted(2)</div><div className="py-4">In Progress(1)</div><div className="py-4">Completed(8)</div></div></div><div className="p-4"><div className="mb-3 flex items-center justify-between text-sm" style={{color:C.muted}}><span>6 Inspections Today</span><span>⌁</span></div><div className="space-y-3">{rows.map(r=><Card key={r[0]}><div className="flex justify-between"><div><div className="font-bold">{r[0]}</div><div className="text-sm" style={{color:C.body}}>{r[1]}</div></div><span className="rounded px-2 py-1 text-[10px] font-bold" style={{background:C.tealLight,color:C.teal}}>{r[2]}</span></div><div className="mt-3 text-xs" style={{color:C.body}}>▣ {r[3]} &nbsp;⌖ {r[4]} &nbsp;<span style={{color:C.teal}}>▣ {r[5]}</span></div></Card>)}</div></div><div className="mt-auto"><BottomNav/></div></App>}

export function VisitSchedule({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Visit Schedule',onBack)}<div className="p-4"><div className="mb-4 flex justify-between rounded-lg bg-white p-2 text-center text-sm"><div className="flex-1">12</div><div className="flex-1 rounded-lg py-2 text-white" style={{background:C.teal}}>13</div><div className="flex-1">14</div><div className="flex-1">15</div><div className="flex-1">16</div><div className="flex-1">17</div></div>{[['10:00 AM','TRD-122','Guntur'],['12:00 PM','TRD-456','Sadar']].map(x=><div className="mb-4 flex gap-3" key={x[1]}><div className="w-[52px] text-xs font-bold" style={{color:C.muted}}>{x[0]}</div><Card><div className="font-bold">{x[1]}</div><div className="text-sm" style={{color:C.body}}>{x[2]}</div><button className="mt-2 w-full rounded-md py-2 font-bold text-sm" style={{background:C.tealLight,color:C.teal}}>Navigate</button></Card></div>)}<Btn>Start Day</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export function InspectionDetail({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Inspection Detail',onBack)}<div className="p-4"><Card><div className="font-bold" style={{color:C.teal}}>TRD-CHL-089234</div><div className="text-xs mt-1">CHILLI</div><div className="mt-2 text-sm">Rajesh Kumar • Priya Agencies</div><div className="mt-3 text-xs" style={{color:C.body}}>50 bags / 2500 kg</div></Card><div className="my-4 flex gap-2"><span className="rounded bg-white px-2 py-1 text-xs border" style={{borderColor:C.border}}>Moisture 8%</span><span className="rounded bg-white px-2 py-1 text-xs border" style={{borderColor:C.border}}>Grade A</span><span className="rounded bg-white px-2 py-1 text-xs border" style={{borderColor:C.border}}>Impurities &lt;2%</span></div><Card><div className="font-bold">Inspection History</div><div className="mt-3 space-y-4 text-sm">{['Assigned','Accepted','Scheduled'].map((x,i)=><div key={x} className="flex justify-between"><span>{x}</span><span style={{color:C.muted}}>{['Now','Today 9:40 AM','Tomorrow'][i]}</span></div>)}</div></Card><Btn>Start Inspection</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export function SampleCollection({onBack}:ScreenProps){const selected=[4,12,25,33,41,48]; return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Sample Collection',onBack)}<div className="p-4"><h2 className="mb-3 font-bold">Sampling Method</h2><div className="flex gap-2"><Btn>Random (6 of 50)</Btn><Btn secondary>Full</Btn><Btn secondary>Custom</Btn></div><div className="mt-5 flex items-center justify-between"><h2 className="font-bold">Bag Selection</h2><span className="rounded px-2 py-1 text-xs font-bold" style={{background:C.tealLight,color:C.teal}}>6 bags selected</span></div><div className="mt-3 grid grid-cols-5 gap-1">{Array.from({length:50},(_,i)=>i+1).map(n=><button key={n} className="h-9 rounded border text-xs font-semibold" style={{background:selected.includes(n)?C.teal:C.white,color:selected.includes(n)?C.white:C.muted,borderColor:selected.includes(n)?C.teal:C.border}}>{n}</button>)}</div><h2 className="mt-5 font-bold">Photo Capture</h2><div className="mt-3 flex gap-3">{[1,2,3].map(i=><div className="flex h-[75px] w-[75px] items-center justify-center rounded-lg border border-dashed" style={{borderColor:C.border}} key={i}>◌</div>)}<div className="flex h-[75px] w-[75px] items-center justify-center rounded-lg" style={{background:C.tealLight,color:C.teal,fontSize:28}}>+</div></div><Card><div className="text-xs" style={{color:C.muted}}>Collected By</div><div className="font-semibold">Sanjay Kumar (Auto)</div></Card><Btn>Next</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export function EvidencePhotos({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Evidence Photos',onBack)}<div className="p-4"><div className="flex gap-2 overflow-hidden">{['Bulk lot','Damaged bags','Moisture meter','Pests'].map((x,i)=><span key={x} className="shrink-0 rounded-full border px-3 py-2 text-xs font-semibold" style={{background:i===0?C.teal:C.white,color:i===0?C.white:C.body,borderColor:i===0?C.teal:C.border}}>{x}</span>)}</div><div className="mt-5 flex items-center justify-between"><h2 className="font-bold">Bulk lot photos</h2><span className="text-xs text-red-600">* Minimum 3 required</span></div><div className="mt-3 grid grid-cols-3 gap-2">{[1,2,3].map(i=><div key={i} className="aspect-square overflow-hidden rounded-lg border" style={{borderColor:C.border}}><img className="h-full w-full object-cover" src={['https://www.figma.com/api/mcp/asset/5208ba65-3ee9-4874-9429-e454c58ced6e.png','https://www.figma.com/api/mcp/asset/3416fb65-1897-49e5-95e4-388b596e89de.png','https://www.figma.com/api/mcp/asset/1db29c51-326b-43c0-ab6f-23b7b0cc0098.png'][i-1]} /></div>)}</div><div className="mt-4 flex gap-2">{[1,2,3].map(i=><div className="flex h-8 flex-1 items-center justify-center rounded" style={{background:C.tealLight,color:C.teal,fontSize:22}} key={i}>+</div>)}</div><div className="mt-5 flex justify-between text-sm font-semibold"><span>Uploading Evidence...</span><span style={{color:C.teal}}>60%</span></div><div className="mt-2 h-1.5 rounded-full" style={{background:C.tealLight}}><div className="h-1.5 w-[60%] rounded-full" style={{background:C.teal}} /></div><Btn>Next</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export function QualityChecklist({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Quality Checklist',onBack)}<div className="p-4 space-y-3">{[['Moisture %','8.2','PASS'],['Foreign matter %','1.5','PASS'],['Broken grains %','3.2','PASS']].map(r=><Card key={r[0]}><div className="flex items-center justify-between"><span className="font-semibold">{r[0]}</span><div className="flex gap-2"><span>{r[1]}</span><span className="rounded px-2 py-1 text-[10px]" style={{background:C.tealLight,color:C.teal}}>{r[2]}</span></div></div></Card>)}<Card><div className="font-semibold mb-3">Color/Appearance</div><div className="rounded border p-2 text-sm" style={{borderColor:C.border}}>Excellent</div><div className="mt-3 font-semibold">Odor</div><div className="text-sm" style={{color:C.teal}}>● Normal</div><div className="mt-3 font-semibold">Observations</div><div className="mt-2 rounded border p-3 text-sm" style={{borderColor:C.border,color:C.muted}}>No specific issues observed.</div></Card><div className="flex gap-2"><Btn secondary>Save Draft</Btn><Btn>Next</Btn></div></div><div className="mt-auto"><BottomNav/></div></App>}

export function SubmitGrade({onBack}:ScreenProps){const [grade,setGrade]=useState('A'); return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Submit Grade',onBack)}<div className="p-4"><h2 className="mb-4 text-lg font-bold">Select Overall Grade</h2><div className="grid grid-cols-2 gap-3">{[['A','☆','Grade A'],['B','♧','Grade B'],['C','⊖','Grade C'],['R','⊗','Reject']].map(r=><button key={r[0]} onClick={()=>setGrade(r[0])} className="flex flex-col items-center gap-2 rounded-xl border p-5" style={{background:grade===r[0]?C.tealLight:C.white,borderColor:grade===r[0]?C.teal:C.border,borderWidth:grade===r[0]?2:1}}><div className="text-3xl" style={{color:grade===r[0]?C.teal:'#ff8a00'}}>{r[1]}</div><div className="font-bold">{r[2]}</div></button>)}</div><h2 className="mt-6 mb-3 font-bold">Report Preview</h2><Card><div className="flex items-center gap-3"><div className="flex h-14 w-12 items-center justify-center rounded" style={{background:'#f9dedc',color:'#b3261e'}}>PDF</div><div className="flex-1"><div className="font-bold">Inspection Report</div><div className="text-xs" style={{color:C.muted}}>TRD-CHL-089234 • 1.2 MB</div></div><span className="text-2xl" style={{color:C.teal}}>◉</span></div></Card><Btn>Submit Report</Btn><div className="text-center text-xs" style={{color:C.muted}}>OTP confirmation required from stakeholder</div></div><div className="mt-auto"><BottomNav/></div></App>}

export function OTPConfirmation({onBack}:ScreenProps){const [otp,setOtp]=useState(''); return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div><div className="flex flex-1 flex-col items-center justify-center p-6 text-center"><div className="mb-4 flex h-20 w-20 items-center justify-center rounded-full" style={{background:C.tealLight,color:C.teal,fontSize:34}}>♢</div><h1 className="text-2xl font-extrabold">Confirm Inspection</h1><p className="mt-2 max-w-[320px] text-sm" style={{color:C.body}}>Ask the producer/CA for the OTP sent to their registered mobile number ending in •••• 8823</p><div className="mt-8 flex gap-2">{Array.from({length:6}).map((_,i)=><input key={i} maxLength={1} className="h-[52px] w-[44px] rounded-lg border text-center text-lg" style={{borderColor:i===0?C.teal:C.border}} onChange={e=>{const v=e.target.value; setOtp(p=>p+v)}} />)}</div><div className="mt-6 text-sm font-semibold" style={{color:C.body}}>◷ 02:30 remaining</div><button className="mt-8 h-12 w-full max-w-[327px] rounded-lg font-bold text-white" style={{background:C.teal}}>Verify</button><button className="mt-4 font-bold" style={{color:C.teal}}>Resend OTP</button></div><div className="mt-auto w-full"><BottomNav/></div></App>}

export function DisputeReinspection({onBack}:ScreenProps){const [reason,setReason]=useState('Quality mismatch');return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Dispute or Reinspection',onBack)}<div className="p-4 space-y-6"><div><h2 className="mb-3 font-bold">Dispute Reason</h2><div className="flex flex-wrap gap-2">{['Quality mismatch','Sampling error','Report error','Other'].map(x=><button key={x} onClick={()=>setReason(x)} className="rounded-full border px-3 py-2 text-xs font-semibold" style={{background:reason===x?C.tealLight:C.white,color:reason===x?C.teal:C.body,borderColor:reason===x?C.teal:C.border}}>{x}</button>)}</div></div><div><h2 className="mb-2 text-sm font-semibold">Description</h2><div className="h-24 rounded-lg border bg-white p-3 text-sm" style={{borderColor:C.border,color:C.muted}}>Explain the discrepancy in detail...</div></div><div><h2 className="mb-3 font-semibold">Evidence Photos</h2><div className="flex gap-2"><div className="h-20 w-20 rounded-lg bg-gray-200"/><div className="h-20 w-20 rounded-lg bg-gray-200"/><div className="h-20 w-20 rounded-lg bg-gray-200"/><div className="flex h-20 w-20 items-center justify-center rounded-lg" style={{background:C.tealLight,color:C.teal,fontSize:24}}>+</div></div></div><div><h2 className="mb-3 font-bold">Requested Action</h2><label className="flex gap-3"><input type="radio" checked readOnly/> <span className="text-sm">Request re-inspection (Free)</span></label><label className="mt-3 flex gap-3"><input type="radio"/> <span className="text-sm">Escalate to arbitrator (Fee split)</span></label></div><Btn>Submit Dispute</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export function EvidenceFlowStart({onBack}:ScreenProps){return <App><div className="flex h-11 items-center justify-between px-6 text-sm"><span>9:41</span><span>⌁  ◔</span></div>{topBack('Inspection Evidence',onBack)}<div className="p-4"><Card><div className="font-bold" style={{color:C.teal}}>TRD-CHL-089234</div><div className="mt-2 text-sm">Chilli (Grade A) • Priya Agencies</div></Card><Btn>Start Evidence Flow</Btn></div><div className="mt-auto"><BottomNav/></div></App>}

export const inspectorRoutes: Record<string, React.ComponentType<ScreenProps>> = {
  "inspector-dashboard": InspectorDashboard,
  "assigned-inspections": AssignedInspections,
  "visit-schedule": VisitSchedule,
  "inspection-detail": InspectionDetail,
  "sample-collection": SampleCollection,
  "evidence-photos": EvidencePhotos,
  "quality-checklist": QualityChecklist,
  "submit-grade": SubmitGrade,
  "otp-confirmation": OTPConfirmation,
  "dispute-reinspection": DisputeReinspection,
};
