import React from "react";
import { figmaBuyer35ScreenRegistry } from "./FigmaBuyer35ScreenRegistry";

const TEAL = "#00796b";
const DARK_TEAL = "#004d40";
const BG = "#f5f5f5";
const BORDER = "#e0e0e0";
const MUTED = "#666";
const RED = "#c62828";

export default function BuyerWorkflow35ScreensImpl({ screen = "2041:277" }: { screen?: string }) {
  const entry = figmaBuyer35ScreenRegistry.find(x => x.nodeId === screen) ?? figmaBuyer35ScreenRegistry[0];
  const title = entry.title;

  return (
    <div data-node-id={screen} style={{ minHeight: "100vh", width: 375, maxWidth: "100%", margin: "0 auto", background: BG, fontFamily: "Arial, sans-serif", color: "#1a1a1a" }}>
      <div style={{ height: 44, display: "flex", alignItems: "center", justifyContent: "space-between", padding: "0 20px" }}>
        <span style={{ fontWeight: 600, fontSize: 14 }}>9:41</span><span style={{ fontSize: 12 }}>▮⌁▣</span>
      </div>
      <div style={{ background: TEAL, color: "#fff", height: 48, display: "flex", alignItems: "center", padding: "0 16px", gap: 12 }}>
        <span style={{ fontSize: 28 }}>‹</span><h1 style={{ margin: 0, fontSize: 18 }}>{title}</h1>
      </div>
      <main style={{ padding: 20 }}>
        {screen === "2041:277" ? <>
          <div style={{ background: TEAL, color: "white", margin: "-20px -20px 20px", padding: 20 }}><div style={{ fontSize: 22, fontWeight: 800 }}>Hello, Sonia</div><div style={{ display: "inline-block", marginTop: 6, background: DARK_TEAL, padding: "4px 8px", borderRadius: 16, fontSize: 12 }}>◉ 1,200 TRD</div></div>
          <div style={{ display: "flex", gap: 12, overflowX: "auto" }}>{[["3","Active RFQs"],["5","Active Bids"],["2","In Transit"]].map(([n,l])=><div key={l} style={{ background: "#e0f2f1", borderRadius: 16, padding: 12, minWidth: 86 }}><div style={{ color: TEAL, fontSize: 24, fontWeight: 800 }}>{n}</div><div style={{ color: MUTED, fontSize: 11 }}>{l}</div></div>)}</div>
          <div style={{ margin: "24px 0" }}><div style={{ background: "#fff", borderLeft: `4px solid ${TEAL}`, borderRadius: 16, padding: 16 }}><b style={{ color: TEAL }}>ϟ GROK INSIGHT</b><p style={{ margin: "8px 0 0", fontSize: 14 }}>Chilli prices expected to drop next week. Wait before buying.</p></div></div>
          <h2 style={{ fontSize: 18 }}>Active RFQs</h2>
          {["Chilli – 200 quintals","Chilli – 200 quintals"].map((x,i)=><div key={i} style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 12, marginBottom: 8, display: "flex", alignItems: "center", justifyContent: "space-between" }}><div><b>{x}</b><div style={{ color: MUTED, fontSize: 12 }}>5 matches found</div></div><button type="button" style={{ border: 0, background: "#e0f2f1", color: TEAL, padding: "8px 12px", borderRadius: 8, fontWeight: 700 }}>View</button></div>)}
          <h2 style={{ fontSize: 18 }}>Recent Bids</h2><div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 12 }}>You bid <b>₹158/kg</b> on LOT-556<div style={{ marginTop: 10, color: "#2e7d32", fontSize: 11, fontWeight: 700 }}>LEADING <span style={{ float: "right", color: "#999", fontWeight: 400 }}>2m ago</span></div></div>
        </> : screen === "2041:278" ? <>
          {[["Commodity","Select Commodity"],["Grade","Premium"],["Quantity","200"],["Unit","quintal"]].map(([l,v])=><div key={l} style={{ marginBottom: 18 }}><b style={{ color: MUTED, fontSize: 14 }}>{l}</b><div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 12, padding: 14, marginTop: 8 }}>{v}{(l === "Commodity" || l === "Grade") && <span style={{ float: "right" }}>⌄</span>}</div></div>)}
          <div><b style={{ color: MUTED, fontSize: 14 }}>Moisture Tolerance (9%)</b><div style={{ marginTop: 10, display: "flex", gap: 12, alignItems: "center" }}><div style={{ width: 66, height: 4, background: "#ddd" }}/><b style={{ color: TEAL }}>9%</b></div></div>
          <div style={{ marginTop: 20 }}><b style={{ color: MUTED, fontSize: 14 }}>Packaging Preference</b><div style={{ display: "flex", gap: 8, marginTop: 10 }}>{["Jute Bag","PP Bag","Loose"].map((x,i)=><span key={x} style={{ padding: "8px 14px", borderRadius: 18, border: `1px solid ${i===0?TEAL:BORDER}`, background: i===0?"#e0f2f1":"#fff", color: i===0?TEAL:MUTED, fontSize: 13 }}>{x}</span>)}</div></div>
          <div style={{ marginTop: 20 }}><b style={{ color: MUTED, fontSize: 14 }}>Delivery Location</b><div style={{ marginTop: 10, border: `1px solid ${BORDER}`, borderRadius: 12, overflow: "hidden" }}><div style={{ height: 120, background: `url(https://www.figma.com/api/mcp/asset/faec602e-6b36-4e23-a040-2065b7bd974b.png) center/cover` }}/><div style={{ display: "flex", justifyContent: "space-between", padding: 12 }}>Guntur, Andhra Pradesh <b style={{ color: TEAL }}>Change</b></div></div></div>
          <button type="button" style={{ marginTop: 20, width: "100%", background: TEAL, color: "white", border: 0, padding: "13px 20px", borderRadius: 12, fontWeight: 700 }}>Publish RFQ</button>
        </> : screen === "2041:279" ? <>
          <div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, overflow: "hidden" }}><div style={{ background: TEAL, color: "white", padding: 16, display: "flex", justifyContent: "space-between" }}><b style={{ fontSize: 20 }}>⊗ Chilli</b><span style={{ background: "#26a69a", padding: "4px 8px", borderRadius: 4, fontSize: 11 }}>OPEN</span></div><div style={{ padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><div style={{ color: MUTED, fontSize: 12 }}>Quantity</div><b>200 Quintals</b></div><div><div style={{ color: MUTED, fontSize: 12 }}>Price Band</div><b>₹150–₹170/kg</b></div></div><div style={{ marginTop: 12, color: MUTED, fontSize: 12 }}>◷ Valid until 25 Oct 2024</div></div></div>
          <h2 style={{ fontSize: 18 }}>✣ AI Best Matches</h2>{[["Rahul Farms","Guntur","95% Match","₹158/kg"],["Kisan Direct","Kurnool","88% Match","₹162/kg"],["Red Spice Co","Warangal","76% Match","₹155/kg"]].map(([n,l,m,p])=><div key={n} style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 12, marginBottom: 12 }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><b>{n}</b><div style={{ color: MUTED, fontSize: 12 }}>{l}</div></div><span style={{ background: TEAL, color: "white", borderRadius: 4, padding: "4px 8px", fontSize: 11, fontWeight: 700 }}>{m}</span></div><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 12 }}><b>{p}</b><button type="button" style={{ width: 100, background: "#fff", border: `1.5px solid ${TEAL}`, color: TEAL, borderRadius: 12, minHeight: 42 }}>View Lot</button></div></div>)}
        </> : screen === "2041:280" ? <>
          <div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 12, padding: 12, color: "#999" }}>⌕ Search commodity or seller...</div><div style={{ display: "flex", gap: 8, margin: "12px 0", overflowX: "auto" }}>{["Commodity","Grade","Distance","Price"].map(x=><span key={x} style={{ border: `1px solid ${BORDER}`, borderRadius: 8, padding: "6px 12px", color: MUTED, fontSize: 12 }}>{x}⌄</span>)}</div><div style={{ fontSize: 14, color: MUTED, marginBottom: 12 }}>Showing 124 results <span style={{ float: "right", color: TEAL, fontWeight: 700 }}>↕ Relevance</span></div>{["77aa7746-329b-4db7-8ecd-91d512d10c94.png","322a8950-d39e-4d5a-9093-cd98fe31de21.png"].map((id,i)=><div key={id} style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, overflow: "hidden", marginBottom: 12 }}><div style={{ height: 140, background: `url(https://www.figma.com/api/mcp/asset/${id}) center/cover` }}/><div style={{ padding: 16 }}><div style={{ display: "flex", justifyContent: "space-between" }}><div><b>LOT-556 • Chilli</b><div style={{ color: MUTED, fontSize: 12 }}>Shiva Exports ★ 4.5</div></div><span style={{ background: "#e0f2f1", color: TEAL, padding: "4px 8px", borderRadius: 4, fontSize: 11, fontWeight: 700 }}>92% Match</span></div><div style={{ marginTop: 12, display: "flex", justifyContent: "space-between", alignItems: "center" }}><div style={{ color: MUTED, fontSize: 12 }}>₹160/kg • 150 Qtl available<br/>Guntur (12 km away)</div><button type="button" style={{ minWidth: 110, border: `1.5px solid ${TEAL}`, background: "#fff", color: TEAL, borderRadius: 12, minHeight: 42 }}>View Details</button></div></div></div>)}</>
        : screen === "2041:281" ? <>
          <div style={{ background: DARK_TEAL, color: "white", borderRadius: 16, padding: 16 }}><div style={{ color: "#26a69a", fontSize: 12 }}>Current Lot</div><b style={{ fontSize: 18 }}>Chilli – 150 Qtl</b><div style={{ color: "#26a69a", fontSize: 12 }}>Seller: Shiva Exports</div><span style={{ float: "right", fontSize: 28 }}>⌖</span></div><div style={{ textAlign: "center", margin: "20px 0" }}><div style={{ color: RED, fontSize: 14 }}>• AUCTION ENDING IN</div><div style={{ fontSize: 48, fontWeight: 900 }}>02:15:33</div></div><div style={{ display: "flex", gap: 8 }}>{[["STOP LOSS","₹150"],["HIGHEST","₹158"],["YOUR CAP","₹162"]].map(([a,b],i)=><div key={a} style={{ flex: 1, background: "#fff", border: `1px solid ${i===1?TEAL:BORDER}`, borderRadius: 12, padding: 12, textAlign: "center" }}><div style={{ color: "#999", fontSize: 10 }}>{a}</div><b style={{ color: i===1?TEAL:"#333" }}>{b}</b></div>)}</div><h3 style={{ color: MUTED, fontSize: 14 }}>Bid Ladder</h3>{[["#1","YOU","₹158/kg"],["#2","Anonymous","₹156/kg"],["#3","Anonymous","₹154/kg"]].map(([r,n,p],i)=><div key={r} style={{ background: i===0?"#e0f2f1":"#fff", border: `1px solid ${i===0?TEAL:BORDER}`, borderRadius: 12, padding: 12, display: "flex", justifyContent: "space-between", marginBottom: 8, fontWeight: 700 }}><span>{r} &nbsp; {n}</span><span style={{ color: i===0?TEAL:"#222" }}>{p}</span></div>)}<div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 16, marginTop: 16 }}><b>Auto-Bid (AI)</b><div style={{ color: MUTED, fontSize: 12 }}>Bid up to ₹162/kg</div><div style={{ float: "right", width: 44, height: 24, background: TEAL, borderRadius: 12, marginTop: -24 }}/></div><div style={{ marginTop: 16 }}><b style={{ color: MUTED, fontSize: 14 }}>Manual Bid Price</b><div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 12, padding: 14, margin: "8px 0" }}>Enter bid price ₹</div><button type="button" style={{ width: "100%", background: TEAL, color: "white", border: 0, borderRadius: 12, minHeight: 42, fontWeight: 700 }}>Place Bid</button><button type="button" style={{ width: "100%", background: "#fff", color: TEAL, border: `1.5px solid ${TEAL}`, borderRadius: 12, minHeight: 42, marginTop: 10, fontWeight: 700 }}>▣ Video Verify</button></div>
        </> : <><div style={{ background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 16 }}><h2 style={{ margin: 0, fontSize: 18 }}>{title}</h2><p style={{ color: MUTED, fontSize: 13 }}>Figma node {screen}</p></div><div style={{ marginTop: 12, background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 16, padding: 16 }}>{["Details","Status","Actions"].map((x,i)=><div key={x} style={{ padding: "12px 0", borderBottom: i<2?`1px solid ${BORDER}`:"none", display: "flex", justifyContent: "space-between" }}>{x}{i===0&&<span style={{color:TEAL,fontWeight:700,fontSize:12}}>ACTIVE</span>}</div>)}</div><button type="button" style={{ width: "100%", background: TEAL, color: "white", border: 0, borderRadius: 12, minHeight: 42, marginTop: 16, fontWeight: 700 }}>{title}</button></>}
      </main>
    </div>
  );
}
