import React from "react";
import { figmaBuyer35ScreenRegistry } from "./FigmaBuyer35ScreenRegistry";

const TEAL = "#00796b";
const DARK_TEAL = "#004d40";
const BG = "#f5f5f5";
const BORDER = "#e0e0e0";
const MUTED = "#666";
const RED = "#c62828";
const asset = (id: string) => `https://www.figma.com/api/mcp/asset/${id}`;
const IMAGES = { map: asset("faec602e-6b36-4e23-a040-2065b7bd974b.png"), lot1: asset("77aa7746-329b-4db7-8ecd-91d512d10c94.png"), lot2: asset("322a8950-d39e-4d5a-9093-cd98fe31de21.png"), avatar: asset("3a86e4f1-7a22-4ac8-b9bb-6882951eede6.png") };

function StatusBar({dark=false}:{dark?:boolean}){return <div style={{height:44,padding:"0 20px",display:"flex",alignItems:"center",justifyContent:"space-between",color:dark?"#fff":"#1a1a1a",fontSize:14,fontWeight:600}}><span>9:41</span><span>▮⌁▣</span></div>}
function Header({title,back=true}:{title:string;back?:boolean}){return <div style={{height:48,background:TEAL,color:"#fff",display:"flex",alignItems:"center",gap:12,padding:"0 16px"}}>{back&&<span style={{fontSize:28}}>‹</span>}<h1 style={{margin:0,fontSize:18}}>{title}</h1></div>}
function BottomNav({active="Home"}:{active?:string}){const items=["Home","Requirements","Browse","Orders","More"];const glyphs=["⌂","☷","⌕","▣","☰"];return <div style={{background:"#fff",borderTop:`1px solid ${BORDER}`,padding:"8px 8px 12px",display:"flex",justifyContent:"space-around",marginTop:"auto"}}>{items.map((x,i)=><div key={x} style={{width:64,textAlign:"center",color:x===active?TEAL:"#999",fontSize:10}}><div style={{fontSize:22}}>{glyphs[i]}</div>{x}</div>)}</div>}
function Btn({children,kind="primary"}:{children:React.ReactNode;kind?:"primary"|"secondary"|"danger"}){const p=kind==="danger"?{bg:"#fff",fg:RED,b:RED}:kind==="secondary"?{bg:"#fff",fg:TEAL,b:TEAL}:{bg:TEAL,fg:"#fff",b:TEAL};return <button type="button" style={{width:"100%",minHeight:42,borderRadius:12,border:`1.5px solid ${p.b}`,background:p.bg,color:p.fg,fontSize:14,fontWeight:700}}>{children}</button>}
function Card({children,dark=false}:{children:React.ReactNode;dark?:boolean}){return <div style={{background:dark?DARK_TEAL:"#fff",color:dark?"#fff":"#1a1a1a",border:dark?"none":`1px solid ${BORDER}`,borderRadius:16,padding:16,marginBottom:12,boxShadow:dark?"none":"0 4px 6px rgba(0,0,0,.04)"}}>{children}</div>}

export default function BuyerWorkflow35ScreensV2({screen="2041:277"}:{screen?:string}){
 const entry=figmaBuyer35ScreenRegistry.find(x=>x.nodeId===screen)??figmaBuyer35ScreenRegistry[0];
 const title=entry.title;
 const Generic=()=> <><StatusBar/><Header title={title}/><main style={{padding:20,minHeight:650}}><Card><h2 style={{margin:0,fontSize:18}}>{title}</h2><p style={{color:MUTED,fontSize:13}}>Figma node {screen}</p></Card>{["Details","Status","Actions"].map((x,i)=><Card key={x}><div style={{display:"flex",justifyContent:"space-between"}}>{x}{i===0&&<span style={{color:TEAL,fontWeight:700,fontSize:12}}>ACTIVE</span>}</div></Card>)}<Btn>{title}</Btn></main><BottomNav active="More"/></>;
 if(screen==="2041:277") return <div style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><Dashboard/><BottomNav/></div>;
 if(screen==="2041:278") return <div style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><PostRequirement/></div>;
 if(screen==="2041:279") return <div style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><RfqDetail/></div>;
 if(screen==="2041:280") return <div style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><BrowseLots/></div>;
 if(screen==="2041:281") return <div style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><LiveBidding/></div>;
 return <div data-node-id={screen} style={{width:375,maxWidth:"100vw",margin:"0 auto",background:BG,minHeight:"100vh"}}><Generic/></div>;
}

function Dashboard(){return <><div style={{background:TEAL,color:"#fff"}}><StatusBar dark/><div style={{padding:"8px 20px 16px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontSize:22,fontWeight:800}}>Hello, Sonia</div><span style={{display:"inline-block",marginTop:4,background:DARK_TEAL,padding:"4px 8px",borderRadius:16,fontSize:12}}>◉ 1,200 TRD</span></div><img src={IMAGES.avatar} alt="" style={{width:36,height:36,borderRadius:18,objectFit:"cover"}}/></div></div><main style={{padding:20}}><div style={{display:"flex",gap:12,overflowX:"auto"}}>{[["3","Active RFQs"],["5","Active Bids"],["2","In Transit"]].map(([n,l])=><div key={l} style={{background:"#e0f2f1",borderRadius:16,padding:12,minWidth:86}}><div style={{fontSize:24,fontWeight:800,color:TEAL}}>{n}</div><div style={{fontSize:11,color:MUTED}}>{l}</div></div>)}</div><div style={{display:"flex",gap:8,margin:"24px 0"}}>{["Post Req","Browse Lots","Track"].map(x=><div key={x} style={{flex:1}}><Btn kind="secondary">{x}</Btn></div>)}</div><Card><b style={{color:TEAL}}>ϟ GROK INSIGHT</b><p style={{margin:"8px 0 0"}}>Chilli prices expected to drop next week. Wait before buying.</p></Card><h2 style={{fontSize:18}}>Active RFQs</h2>{[IMAGES.lot1,IMAGES.lot2].map(src=><Card key={src}><div style={{display:"flex",alignItems:"center",gap:12}}><img src={src} alt="" style={{width:40,height:40,borderRadius:8,objectFit:"cover"}}/><div style={{flex:1}}><b>Chilli – 200 quintals</b><div style={{fontSize:12,color:MUTED}}>5 matches found</div></div><div style={{width:54}}><Btn kind="secondary">View</Btn></div></div></Card>)}<h2 style={{fontSize:18}}>Recent Bids</h2><Card>You bid <b>₹158/kg</b> on LOT-556<div style={{marginTop:10,fontSize:11,color:"#2e7d32",fontWeight:700}}>LEADING <span style={{float:"right",color:"#999",fontWeight:400}}>2m ago</span></div></Card></main></>}
function PostRequirement(){return <><StatusBar/><Header title="Post Requirement"/><main style={{padding:20}}>{[["Commodity","Select Commodity"],["Grade","Premium"],["Quantity","200"],["Unit","quintal"]].map(([l,v])=><div key={l} style={{marginBottom:18}}><b style={{color:MUTED,fontSize:14}}>{l}</b><div style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:12,padding:14,marginTop:8}}>{v}{(l==="Commodity"||l==="Grade")&&<span style={{float:"right"}}>⌄</span>}</div></div>)}<div><b style={{color:MUTED,fontSize:14}}>Moisture Tolerance (9%)</b><div style={{display:"flex",gap:12,alignItems:"center",marginTop:10}}><div style={{width:66,height:4,background:"#ddd"}}/><b style={{color:TEAL}}>9%</b></div></div><div style={{marginTop:20}}><b style={{color:MUTED,fontSize:14}}>Packaging Preference</b><div style={{display:"flex",gap:8,marginTop:10}}>{["Jute Bag","PP Bag","Loose"].map((x,i)=><span key={x} style={{padding:"8px 14px",borderRadius:18,border:`1px solid ${i===0?TEAL:BORDER}`,background:i===0?"#e0f2f1":"#fff",color:i===0?TEAL:MUTED,fontSize:13}}>{x}</span>)}</div></div><div style={{marginTop:20}}><b style={{color:MUTED,fontSize:14}}>Delivery Location</b><div style={{marginTop:10,border:`1px solid ${BORDER}`,borderRadius:12,overflow:"hidden"}}><div style={{height:120,background:`url(${IMAGES.map}) center/cover`}}/><div style={{display:"flex",justifyContent:"space-between",padding:12,fontSize:13}}>Guntur, Andhra Pradesh <b style={{color:TEAL}}>Change</b></div></div></div><div style={{marginTop:20}}><Btn>Publish RFQ</Btn></div></main></>}
function RfqDetail(){const m=[["Rahul Farms","Guntur","95% Match","₹158/kg"],["Kisan Direct","Kurnool","88% Match","₹162/kg"],["Red Spice Co","Warangal","76% Match","₹155/kg"]];return <><StatusBar/><Header title="RFQ Detail"/><main style={{padding:20}}><Card><div style={{background:TEAL,color:"#fff",margin:-16,padding:16,borderRadius:"16px 16px 0 0",display:"flex",justifyContent:"space-between"}}><b style={{fontSize:20}}>⊗ Chilli</b><span style={{background:"#26a69a",padding:"4px 8px",borderRadius:4,fontSize:11}}>OPEN</span></div><div style={{paddingTop:28,display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:12,color:MUTED}}>Quantity</div><b>200 Quintals</b></div><div><div style={{fontSize:12,color:MUTED}}>Price Band</div><b>₹150–₹170/kg</b></div></div><div style={{marginTop:12,fontSize:12,color:MUTED}}>◷ Valid until 25 Oct 2024</div></Card><h2 style={{fontSize:18}}>✣ AI Best Matches</h2>{m.map(([n,l,match,p])=><Card key={n}><div style={{display:"flex",justifyContent:"space-between"}}><div><b>{n}</b><div style={{fontSize:12,color:MUTED}}>{l}</div></div><span style={{background:TEAL,color:"white",padding:"4px 8px",borderRadius:4,fontSize:11,fontWeight:700}}>{match}</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:16}}><b>{p}</b><div style={{width:100}}><Btn kind="secondary">View Lot</Btn></div></div></Card>)}</main></>}
function BrowseLots(){return <><StatusBar/><Header title="Browse Lots" back={false}/><main style={{padding:16}}><div style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:12,padding:12,color:"#999"}}>⌕ Search commodity or seller...</div><div style={{display:"flex",gap:8,margin:"12px 0",overflowX:"auto"}}>{["Commodity","Grade","Distance","Price"].map(x=><span key={x} style={{border:`1px solid ${BORDER}`,borderRadius:8,padding:"6px 12px",fontSize:12,color:MUTED}}>{x}⌄</span>)}</div><div style={{fontSize:14,color:MUTED,marginBottom:12}}>Showing 124 results <span style={{float:"right",color:TEAL,fontWeight:700}}>↕ Relevance</span></div>{[IMAGES.lot1,IMAGES.lot2].map(src=><Card key={src}><div style={{height:140,margin:-16,marginBottom:16,background:`url(${src}) center/cover`,borderRadius:"16px 16px 0 0"}}/><div style={{display:"flex",justifyContent:"space-between"}}><div><b>LOT-556 • Chilli</b><div style={{fontSize:12,color:MUTED}}>Shiva Exports ★ 4.5</div></div><span style={{background:"#e0f2f1",color:TEAL,padding:"4px 8px",borderRadius:4,fontSize:11,fontWeight:700}}>92% Match</span></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12}}><div style={{fontSize:12,color:MUTED}}>₹160/kg • 150 Qtl available<br/>Guntur (12 km away)</div><div style={{width:110}}><Btn kind="secondary">View Details</Btn></div></div></Card>)}</main><BottomNav active="Browse"/></>}
function LiveBidding(){return <><StatusBar/><Header title="Live Bidding"/><main style={{padding:20}}><Card dark><div style={{fontSize:12,color:"#26a69a"}}>Current Lot</div><b style={{fontSize:18}}>Chilli – 150 Qtl</b><div style={{fontSize:12,color:"#26a69a"}}>Seller: Shiva Exports</div><span style={{float:"right",fontSize:28}}>⌖</span></Card><div style={{textAlign:"center",margin:"20px 0"}}><div style={{color:RED,fontSize:14}}>• AUCTION ENDING IN</div><div style={{fontSize:48,fontWeight:900}}>02:15:33</div></div><div style={{display:"flex",gap:8}}>{[["STOP LOSS","₹150"],["HIGHEST","₹158"],["YOUR CAP","₹162"]].map(([a,b],i)=><div key={a} style={{flex:1,background:"#fff",border:`1px solid ${i===1?TEAL:BORDER}`,borderRadius:12,padding:12,textAlign:"center"}}><div style={{color:"#999",fontSize:10}}>{a}</div><b style={{color:i===1?TEAL:"#333"}}>{b}</b></div>)}</div><h3 style={{color:MUTED,fontSize:14}}>Bid Ladder</h3>{[["#1","YOU","₹158/kg"],["#2","Anonymous","₹156/kg"],["#3","Anonymous","₹154/kg"]].map(([r,n,p],i)=><div key={r} style={{background:i===0?"#e0f2f1":"#fff",border:`1px solid ${i===0?TEAL:BORDER}`,borderRadius:12,padding:12,display:"flex",justifyContent:"space-between",marginBottom:8,fontWeight:700}}><span>{r}&nbsp;{n}</span><span style={{color:i===0?TEAL:"#222"}}>{p}</span></div>)}<Card><b>Auto-Bid (AI)</b><div style={{fontSize:12,color:MUTED}}>Bid up to ₹162/kg</div><div style={{float:"right",width:44,height:24,background:TEAL,borderRadius:12,marginTop:-24}}/></Card><div style={{marginTop:16}}><b style={{color:MUTED,fontSize:14}}>Manual Bid Price</b><div style={{background:"#fff",border:`1px solid ${BORDER}`,borderRadius:12,padding:14,margin:"8px 0"}}>Enter bid price ₹</div><Btn>Place Bid</Btn><div style={{marginTop:10}}><Btn kind="secondary">▣ Video Verify</Btn></div></div></main></>}
