import React from "react";

const O = "#e65100";
const G = "#2e7d32";
const BG = "#f5f5f5";
const M = "#757575";

function Shell({ title, right, children }: { title: string; right?: React.ReactNode; children: React.ReactNode }) {
  return (
    <div style={{ width: 375, minHeight: 812, background: BG, color: "#212121", fontFamily: "DM Sans, Arial, sans-serif", display: "flex", flexDirection: "column" }}>
      <div style={{ height: 44, display: "flex", justifyContent: "space-between", alignItems: "center", padding: "0 24px", fontSize: 14, fontWeight: 600 }}>9:41 <span>⌁⌁ ▱</span></div>
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", padding: "12px 16px" }}>
        <span style={{ display: "flex", gap: 12, alignItems: "center" }}><span style={{ fontSize: 24 }}>‹</span><b style={{ fontSize: 24 }}>{title}</b></span>{right}
      </div>
      <div style={{ flex: 1, overflowY: "auto" }}>{children}</div>
      <div style={{ height: 72, background: "#fff", borderTop: "1px solid #e0e0e0", display: "flex", justifyContent: "space-around", alignItems: "center", fontSize: 11, color: M }}>
        <span style={{ color: O }}>⌂<br/>HOME</span><span>▣<br/>ORDERS</span><span>₹<br/>ADVANCES</span><span>◈<br/>STOCK</span><span>♙<br/>ACCOUNT</span>
      </div>
    </div>
  );
}
const Card = ({ children, border = "1px solid transparent", opacity = 1 }: { children: React.ReactNode; border?: string; opacity?: number }) => <div style={{ background: "#fff", border, borderRadius: 12, padding: 16, marginBottom: 12, opacity, boxShadow: "0 2px 3px rgba(0,0,0,.04)" }}>{children}</div>;
const Btn = ({ children, outline = false }: { children: React.ReactNode; outline?: boolean }) => <button style={{ width: "100%", padding: "12px 16px", borderRadius: 9, border: outline ? `1px solid ${O}` : "1px solid transparent", background: outline ? "#fff" : O, color: outline ? O : "#fff", fontWeight: 700 }}>{children}</button>;

function Producers() {
  const rows = [
    ["RK", "Rajesh Kumar", "Guntur Rural", "₹50,000 outstanding", "₹3,29,650 pending", O, "ADVANCE TAKEN"],
    ["SR", "Suresh Reddy", "Tenali", "₹0 advance", "", G, "ACTIVE"],
    ["RN", "Ramesh Naidu", "Last sale: 3 months ago", "", "", M, "INACTIVE"],
  ];
  return <Shell title="Producers" right={<span style={{ display: "flex", gap: 18, fontSize: 25 }}>⊕ ⌕</span>}><div style={{ padding: "0 16px" }}>
    <div style={{ background: "#e0e0e0", borderRadius: 12, padding: 10, color: M, marginBottom: 12 }}>⌕ Search by name, village, or mobile</div>
    <div style={{ display: "flex", gap: 8, overflow: "hidden", marginBottom: 16 }}>{["ALL", "Advance Taken", "Active", "Inactive"].map((x,i)=><span key={x} style={{ padding: i===0?"2px 8px":"6px 12px", borderRadius: 999, border:i===0?"none":"1px solid #e0e0e0", background:i===0?"#fff3e0":"#fff", color:i===0?O:M, fontSize:11 }}>{x}</span>)}</div>
    <div style={{ display: "flex", gap: 8, marginBottom: 20 }}>{[["TOTAL PRODUCERS","12"],["ADVANCE O/S","₹2.5L"],["PENDING SETT.","₹3.8L"]].map(([k,v])=><div key={k} style={{ flex:1, background:"#fff", borderRadius:12, padding:12, boxShadow:"0 2px 2px rgba(0,0,0,.03)" }}><div style={{fontSize:10,color:M}}>{k}</div><b style={{fontSize:16}}>{v}</b></div>)}</div>
    {rows.map(r=><Card key={r[1]} border="1px solid #e0e0e0"><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{width:40,height:40,borderRadius:20,background:r[5]===G?"#e8f5e9":r[5]===M?"#eee":"#fff3e0",display:"flex",alignItems:"center",justifyContent:"center",color:r[5],fontWeight:700}}>{r[0]}</div><div style={{flex:1}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><b>{r[1]}</b><span style={{fontSize:10,color:r[5],background:r[5]===G?"#e8f5e9":r[5]===M?"#eee":"#fff3e0",padding:"3px 7px",borderRadius:4}}>{r[6]}</span></div><div style={{fontSize:13,color:M}}>{r[2]}</div>{r[3]&&<div style={{fontSize:13,color:r[5],fontWeight:700}}>{r[3]}</div>}{r[4]&&<div style={{fontSize:13,color:M}}>{r[4]}</div>}</div><span style={{fontSize:24,color:"#bdbdbd"}}>›</span></div></Card>)}
  </div></Shell>;
}

function Home(){return <Shell title="" right={null}><div style={{background:"#fff",padding:"12px 20px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",gap:12,alignItems:"center"}}><div style={{width:40,height:40,borderRadius:20,background:"#fff3e0",display:"flex",alignItems:"center",justifyContent:"center",color:O,fontWeight:800}}>PA</div><b>Good morning, Priya</b></div><div style={{display:"flex",gap:10,alignItems:"center"}}><span style={{background:BG,borderRadius:12,padding:"4px 8px",fontSize:12,fontWeight:700}}>2,450 TRD 🪙</span><span style={{fontSize:22}}>♧</span></div></div><div style={{padding:16}}><div style={{fontSize:11,color:M,marginBottom:14}}>Today, 20 Jun 2025 | Market Yard: Guntur ▼</div><div style={{display:"flex",gap:10,overflow:"hidden",marginBottom:14}}>{[["12","Active Producers","+2 this week"],["8","Active Buyers","+1 this week"]].map((r,i)=><div key={i} style={{minWidth:160,background:'#fff',borderRadius:16,padding:12}}><div style={{color:O,fontSize:20}}>{i?'▣':'♧'}</div><b style={{fontSize:18}}>{r[0]}</b><div style={{fontSize:11,color:M}}>{r[1]}</div><div style={{fontSize:11,color:G,fontWeight:700}}>{r[2]}</div></div>)}</div><div style={{display:"flex",gap:8,overflow:"hidden",marginBottom:18}}>{["⊕ Add Producer","▣ Create Listing","$ Request Bill"].map(x=><span key={x} style={{whiteSpace:"nowrap",border:`1px solid ${O}`,borderRadius:30,padding:"8px 12px",color:O,fontSize:12,background:'#fff'}}>{x}</span>)}</div><Card border={`4px solid ${O}`}><div><span style={{background:O,color:'#fff',padding:'2px 6px',borderRadius:4,fontSize:10}}>Grok AI</span> <b>Market Alert</b></div><p style={{fontSize:13,lineHeight:1.5}}>Buyer risk alert: 2 buyers have delayed payments. Review before extending credit.</p><b style={{color:O,fontSize:13}}>View Details →</b></Card><div style={{display:'flex',justifyContent:'space-between',margin:'16px 6px 8px'}}><b>Pending Tasks</b><span style={{color:O,fontWeight:700,fontSize:13}}>View All</span></div><Card border="4px solid #d32f2f"><b>Weighment pending for Token TRD-567</b><div style={{fontSize:11,color:'#d32f2f',margin:'4px 0 10px'}}>Due: Yesterday 5:00 PM | Assigned: Ramesh</div><div style={{width:115}}><Btn>Complete Now</Btn></div></Card><Card border={`4px solid ${O}`}><b>Settlement approval for Buyer Sharma</b><div style={{fontSize:11,color:M,margin:'4px 0 10px'}}>Due: Today 6:00 PM</div><div style={{width:90}}><Btn outline>Review</Btn></div></Card><div style={{marginTop:14}}><b>Recent Activity</b><div style={{marginTop:10,fontSize:13,lineHeight:2.1}}><div style={{color:G}}>● <span style={{color:'#212121'}}>Payment of ₹45,000 recorded for Producer Rao</span></div><div style={{color:'#ef6c00'}}>● <span style={{color:'#212121'}}>New weighment token generated: TRD-901</span></div><div style={{color:'#fbc02d'}}>● <span style={{color:'#212121'}}>Buyer ABC's bid rejected automatically</span></div></div></div></div></Shell>}

function Alerts(){return <Shell title="Alerts" right={<span style={{color:O,fontSize:13}}>Mark all read</span>}><div style={{padding:20}}><div style={{display:'flex',gap:8,overflow:'hidden',marginBottom:12}}>{['All','Unread','Bids','Payments','Disputes'].map((x,i)=><span key={x} style={{padding:'8px 16px',borderRadius:20,background:i===0?O:'#f5f5f5',color:i===0?'#fff':M,fontSize:12}}>{x}</span>)}</div><Card border={`4px solid #d32f2f`}><b>⚠️ Payment overdue from Buyer ABC</b><div style={{fontSize:13,color:M}}>₹1,20,000 | Due 3 days ago</div><div style={{marginTop:10,display:'flex',gap:14}}><button style={{border:`1px solid ${O}`,color:O,background:'#fff',padding:'6px 12px',borderRadius:6,fontWeight:700}}>Send Reminder</button><span style={{color:O,fontWeight:700,fontSize:12}}>View Invoice</span></div><small style={{color:M}}>• 1 hour ago • Unread</small></Card><Card border={`4px solid ${O}`}><b>🔔 New bid on listing TRD-123</b><div style={{fontSize:13,color:M}}>Bid: ₹160/kg | Buyer rank: A</div><div style={{marginTop:10,width:90}}><Btn>Review Bid</Btn></div><small style={{display:'block',color:M,marginTop:10}}>• 2 hours ago • Read</small></Card><Card border="4px solid #9e9e9e"><b>ⓘ Producer Rajesh updated activity</b><div style={{fontSize:13,color:M}}>View latest crop cycle data</div><small style={{display:'block',color:M,marginTop:10}}>• 1 day ago • Read</small></Card><div style={{textAlign:'center',color:M,padding:'36px 0'}}>▧<div>No more alerts for today</div></div></div></Shell>}

function Tasks(){return <Shell title="Tasks" right={<span style={{color:O}}>⌁</span>}><div style={{padding:20}}><div style={{display:'flex',justifyContent:'space-between',background:'#fff3e0',padding:12,borderRadius:12,color:O,fontWeight:600,fontSize:14}}><span>Total pending: 8</span><span>Completed today: 3</span></div><div style={{display:'flex',gap:8,overflow:'hidden',margin:'12px 0'}}>{['All','Weighment','Settlement','Sampling','Approvals'].map((x,i)=><span key={x} style={{padding:'8px 16px',borderRadius:20,background:i===0?O:'#f5f5f5',color:i===0?'#fff':M,fontSize:12}}>{x}</span>)}</div><Card border={`4px solid ${O}`}><b>Weighment for Token TRD-567</b><div style={{color:O,fontSize:13}}>Buyer: Sonia Enterprises</div><div style={{fontSize:12,color:M,lineHeight:1.6,margin:'8px 0'}}>Scheduled: Today 3:00 PM (in 2 hours)<br/>Location: Guntur Yard, Weighbridge 2<br/>Assigned: Ramesh</div><Btn>Start Weighment</Btn></Card><Card border={`4px solid ${O}`}><b>Settlement approval for Buyer Sharma</b><div style={{color:O,fontWeight:700}}>Amount: ₹3,95,000</div><div style={{fontSize:12,color:M,margin:'10px 0'}}>Due: Today 6:00 PM</div><Btn outline>Review &amp; Approve</Btn></Card><Card opacity={0.55}><div style={{color:'#9e9e9e',fontWeight:700}}>Sampling for Token TRD-234 — Completed by Sanjay ✓</div></Card></div></Shell>}

function Profile(){return <Shell title="" right={<span style={{fontSize:22}}>✎</span>}><div style={{padding:'8px 20px 20px'}}><div style={{textAlign:'center'}}><div style={{width:80,height:80,borderRadius:40,border:`2px solid ${O}`,background:'#fff3e0',display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto',color:O,fontSize:30,fontWeight:700}}>PA</div><h1 style={{fontSize:24,margin:'10px 0 4px'}}>Priya Agencies</h1><div style={{color:'#f9a825'}}>⭐ 4.8 <span style={{fontSize:11,color:M}}>(245 reviews)</span></div></div><div style={{margin:'20px 0',padding:16,border:`1px solid ${G}`,borderRadius:12,display:'flex',justifyContent:'space-between'}}><div><b>KYC Tier: Platinum ✓</b><div style={{fontSize:11,color:M}}>Verified: 15 Mar 2025</div></div><span style={{color:O,fontSize:12,fontWeight:700}}>Details</span></div><Card><b>Business Details</b>{[['Legal name','Priya Agencies Pvt Ltd'],['GST Number','37AAAAA0000A1Z5'],['PAN Number','AAAAA0000A'],['Registered Address','12-3-45, Main Road, Guntur, AP']].map(r=><div key={r[0]} style={{display:'flex',justifyContent:'space-between',padding:'9px 0',borderBottom:'1px solid #f0f0f0',fontSize:12}}><span style={{color:M}}>{r[0]}</span><b>{r[1]}</b></div>)}</Card><Card><b>Market Yards</b><div style={{marginTop:10}}><span style={{background:'#fff3e0',color:O,padding:'6px 10px',borderRadius:6,fontSize:12}}>Guntur (primary)</span> <span style={{background:'#f5f5f5',padding:'6px 10px',borderRadius:6,fontSize:12}}>Tenali</span></div><div style={{color:O,fontWeight:700,fontSize:13,marginTop:10}}>+ Add Market Yard</div></Card><Card><b>Bank Accounts</b><div style={{background:'#f5f5f5',padding:12,borderRadius:12,marginTop:10}}>🏦 ICICI Bank – XXXXXX1234 <span style={{float:'right',color:O,fontSize:11}}>Edit &nbsp; Remove</span><div style={{fontSize:11,color:M}}>Default for settlements</div></div><div style={{marginTop:10}}><Btn outline>+ Add Bank Account</Btn></div></Card><Card>You have 5 active staff members. <span style={{float:'right',color:O,fontWeight:700}}>Manage Staff →</span></Card><Btn>Save Changes</Btn><div style={{textAlign:'center',color:'#d32f2f',fontSize:12,margin:12}}>Delete Account</div></div></Shell>}

function Staff(){return <Shell title="Staff Management" right={<span style={{width:32,height:32,borderRadius:16,background:O,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center'}}>＋</span>}><div style={{padding:20}}><div style={{background:'#f5f5f5',padding:16,borderRadius:12,display:'flex',justifyContent:'space-between',fontSize:12,color:M,marginBottom:14}}><span>Total: <b style={{color:'#111'}}>5</b></span><span>Active: <b style={{color:G}}>4</b></span><span>Pending: <b style={{color:'#f9a825'}}>1</b></span></div><Card><div style={{display:'flex',gap:12}}><div style={{width:48,height:48,borderRadius:24,background:'#fff3e0',display:'flex',alignItems:'center',justifyContent:'center',color:O,fontWeight:700}}>RK</div><div style={{flex:1}}><b>Ramesh Kumar</b><span style={{float:'right',fontSize:10,color:O,background:'#fff3e0',padding:'2px 6px',borderRadius:4}}>Weighment Officer</span><div style={{color:G,fontSize:11}}>● Online</div><div style={{fontSize:11,color:M,marginTop:12}}>Permissions: Weighment only<br/>Last active: 5 min ago</div><div style={{color:O,fontWeight:700,fontSize:13,marginTop:12}}>Edit Permissions &nbsp;&nbsp; <span style={{color:'#d32f2f'}}>Deactivate</span></div></div></div></Card><Card opacity={0.7}><div style={{display:'flex',gap:12}}><div style={{width:48,height:48,borderRadius:24,background:'#f5f5f5',display:'flex',alignItems:'center',justifyContent:'center',color:M,fontWeight:700}}>S</div><div style={{flex:1}}><b>Suresh</b><span style={{marginLeft:8,fontSize:10,color:O,background:'#fff3e0',padding:'2px 6px',borderRadius:4}}>Sales Assistant</span><div style={{color:M,fontSize:11}}>● Offline</div><div style={{fontSize:11,color:M,marginTop:12}}>Last active: 3 days ago</div><div style={{color:O,fontWeight:700,fontSize:13,marginTop:12}}>Reactivate</div></div></div></Card><Card><div style={{display:'flex',gap:12,alignItems:'center'}}>✉ <div><b>Invite sent to +91 98765 43210</b><div style={{color:O,fontSize:11}}>Expires in 2 days</div></div></div><div style={{marginTop:12,color:O,fontWeight:700,fontSize:13}}>Resend &nbsp; Cancel</div></Card><Btn outline>Invite New Staff</Btn></div></Shell>}

function Discrepancy(){return <Shell title="Report Discrepancy"><div style={{padding:16}}><Card><div style={{fontSize:12,color:M}}>Token</div><b>TRD-CHL-089234</b><div style={{fontSize:12,color:M,marginTop:10}}>Producer</div><div>Rajesh Kumar</div><div style={{fontSize:12,color:M,marginTop:10}}>Expected Summary</div><div>50 bags / 2,500 kg</div></Card>{[['Expected','Actual','50 bags','48','Difference: -2 bags'],['Expected','Actual','2,500 kg','2,400','Difference: -100 kg'],['Expected Quality','Actual','≤10% Moisture','13%','']].map((r,i)=><Card key={i}><div style={{display:'flex',gap:16}}><div style={{flex:1,color:M,fontSize:12}}>{r[0]}<div style={{fontSize:15,color:'#212121',marginTop:4}}>{r[2]}</div></div><div style={{flex:1,color:M,fontSize:12}}>{r[1]}<div style={{border:`1px solid ${O}`,borderRadius:8,padding:10,color:'#111',marginTop:4}}>{r[3]} {i===2?'📷':''}</div></div></div>{r[4]&&<b style={{color:'#d32f2f',fontSize:13,display:'block',marginTop:12}}>{r[4]}</b>}</Card>)}<div style={{fontSize:13,color:M,marginBottom:8}}>Packaging Condition</div><div style={{display:'flex',gap:8,marginBottom:12}}>{['Damaged','Torn','Wet','✓ OK'].map((x,i)=><span key={x} style={{padding:'7px 12px',borderRadius:999,border:`1px solid ${i===3?G:'#e0e0e0'}`,color:i===3?G:M,fontSize:12,background:i===3?'#e8f5e9':'#fff'}}>{x}</span>)}</div><div style={{fontSize:13,color:M}}>Upload Evidence</div><div style={{display:'flex',gap:12,margin:'6px 0 12px'}}>{[1,2,3].map(x=><div key={x} style={{width:80,height:80,border:'1px dashed #e0e0e0',borderRadius:12,display:'flex',alignItems:'center',justifyContent:'center',flexDirection:'column',color:M}}>＋<small>Photo {x}</small></div>)}</div><Card>Add any additional notes...</Card><Card><div style={{textAlign:'center',color:O,fontSize:12}}>Enter producer OTP to confirm dispute notification</div><div style={{display:'flex',gap:8,marginTop:10}}>{[1,2,3,4,5,6].map(x=><div key={x} style={{flex:1,height:44,border:`1px solid ${O}`,borderRadius:7}}/> )}</div></Card><Btn>Submit Dispute</Btn><div style={{textAlign:'center',fontSize:11,color:M,marginTop:10}}>If unresolved in 48h, dispute escalates to market yard authority.</div></div></Shell>}

export function CommissionAgent8Screens(){return <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(375px,1fr))',gap:20,padding:20,background:'#111'}}><Home/><Alerts/><Tasks/><Profile/><Staff/><Discrepancy/><Producers/></div>}
export default function CommissionAgent8Router(){const r=window.location.hash.replace(/^#/,'');const map:Record<string,React.FC>={'ca-home':Home,'ca-alerts':Alerts,'ca-tasks':Tasks,'ca-profile':Profile,'ca-staff':Staff,'ca-discrepancy':Discrepancy,'producers':Producers};const C=map[r]||Producers;return <C/>;}
